In [1]:
#cell 1

import pandas as pd
import numpy as np
import re
from pathlib import Path
import openpyxl

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 100)
pd.set_option("display.width", 200)

In [2]:
#cell 2

from pathlib import Path

BASE_DIR = Path("..")

MASTER_FILE = (
    BASE_DIR
    / "data"
    / "master"
    / "Learning agility self assesment & superior_24.7.2026.xlsx"
)

SELF_FILE = (
    BASE_DIR
    / "data"
    / "raw"
    / "Self Assessment -Perilaku dalam Situasi Kerja(1-32).xlsx"
)

SUPERIOR_FILE = (
    BASE_DIR
    / "data"
    / "raw"
    / "Superior Assessment -Perilaku dalam Situasi Kerja(1-30).xlsx"
)

OUTPUT_DIR = (
    BASE_DIR
    / "data"
    / "processed"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print("BASE DIR     :", BASE_DIR.resolve())
print("MASTER FILE  :", MASTER_FILE)
print("SELF FILE    :", SELF_FILE)
print("SUPERIOR FILE:", SUPERIOR_FILE)
print("OUTPUT DIR   :", OUTPUT_DIR)

BASE DIR     : C:\Users\zerox\OneDrive\Documents\Desktop\learning
MASTER FILE  : ..\data\master\Learning agility self assesment & superior_24.7.2026.xlsx
SELF FILE    : ..\data\raw\Self Assessment -Perilaku dalam Situasi Kerja(1-32).xlsx
SUPERIOR FILE: ..\data\raw\Superior Assessment -Perilaku dalam Situasi Kerja(1-30).xlsx
OUTPUT DIR   : ..\data\processed

In [3]:
#cell 3
print("Master exists  :", MASTER_FILE.exists())
print("Self exists    :", SELF_FILE.exists())
print("Superior exists:", SUPERIOR_FILE.exists())

Master exists  : True
Self exists    : True
Superior exists: True

In [4]:
#cell 4

self_df = pd.read_excel(
    SELF_FILE
)

superior_df = pd.read_excel(
    SUPERIOR_FILE
)

print("SELF")
print("Rows :", self_df.shape[0])
print("Cols :", self_df.shape[1])

print("\nSUPERIOR")
print("Rows :", superior_df.shape[0])
print("Cols :", superior_df.shape[1])

SELF
Rows : 32
Cols : 110

SUPERIOR
Rows : 30
Cols : 109

In [5]:
#cell 5

self_df.head()

,ID,Start time,Completion time,Email,Name,Last modified time,Nama,Direktorat,Departemen,Unit,"Ketika ada dalam situasi yang mengharuskan pengambilan keputusan atas masalah yang dihadapi, sikap saya adalah..",Komentar,"Ketika menghadapi konsep baru yang rumit, sikap saya adalah..",Komentar2,"Ketika ada dalam yang situasi yang rumit dan belum memiliki kejelasan arah, sikap saya adalah..",Komentar3,"Dalam mengidentifikasi akar masalah dalam situasi kompleks, sikap saya adalah....",Komentar4,"Ketika menjelaskan ide atau masalah yang kompleks kepada orang lain, sikap saya adalah...",Komentar5,"Saat menghadapi ide - ide baru yang belum terbukti efektivitasnya, sikap saya adalah...",Komentar6,"Dalam menghadapi masalah lama menggunakan cara - cara baru , sikap saya adalah..",Komentar7,"Ketika menghadapi ketidakpastian dalam bekerja, sikap saya adalah..",Komentar8,"Saat menerima informasi, Sikap saya adalah...",Komentar9,"Ketika menghadapi konsep yang tampak tidak saling berkaitan, sikap saya adalah...",Komentar10,"Dalam situasi bekerja dengan orang yang memiliki latar belakang berbeda, sikap saya adalah...",Komentar11,"Dalam menghadapi konflik kerja, sikap saya adalah...",Komentar12,"Dalam hal menerima masukan atau umpan balik dari rekan kerja, sikap saya adalah...",Komentar13,"Saat menghadapi situasi konflik antarrekan kerja, sikap saya adalah...",Komentar14,"Dalam hal memahami emosi dan perasaan orang lain , sikap saya adalah...",Komentar15,"Dalam situasi munculnya perbedaan sudut pandang, sikap saya adalah...",Komentar16,"Dalam hal menjaga hubungan baik dengan individu yang sulit, sikap saya adalah...",Komentar17,"Dalam hal menghadapi pendapat orang lain yang berbeda dengan saya, sikap saya adalah...",Komentar18,"Dalam hal menyelesaikan tugas dan butuh berinteraksi dengan rekan kerja, sikap saya adalah...",Komentar19,"Dalam hal mendengarkan orang lain, sikap saya adalah...",Komentar20,"Ketika menghadapi perubahan mendadak, sikap saya adalah...",Komentar21,"Dalam hal menilai perubahan yang terjadi, sikap saya adalah...",Komentar22,"Dalam hal penerapan sistem atau prosedur baru, sikap saya adalah...",Komentar23,"Dalam hal perubahan karena ketidakpastian, sikap saya adalah...",Komentar24,"Ketika mencoba cara atau pendekatan baru, sikap saya adalah...",Komentar25,"Dalam hal menghadapi situasi yang tidak pasti, sikap saya adalah...",Komentar26,"Ketika diterapkan cara kerja baru, sikap saya adalah...",Komentar27,"Dalam hal inisiatif ide/cara baru, sikap saya adalah...",Komentar28,"Dalam hal rasa ingin tahu dan keinginan belajar, sikap saya adalah...",Komentar29,"Dalam hal mengatisipasi perubahan, sikap saya adalah...",Komentar30,"Ketika menghadapi tekanan atau hambatan, sikap saya adalah...",Komentar31,"Dalam hal pengambilan keputusan dalam situasi yang tidak jelas, sikap saya adalah...",Komentar32,"Dalam hal dorongan untuk mencapai hasil terbaik, sikap saya adalah....",Komentar33,"Ketika menghadapi tantangan berat, sikap saya adalah...",Komentar34,"Setelah mengalami keberhasilan atau kegagalan, sikap saya adalah...",Komentar35,Sikap saya terhadap tugas kerja adalah...,Komentar36,"Ketika strategi kerja tidak lagi efektif, sikap saya adalah...",Komentar37,"Dalam menilai keberhasilan kerja, sikap saya adalah...",Komentar38,"Dalam hal melihat peluang atau masalah, sikap saya adalah...",Komentar39,"Ketika menghadapi rintangan tak terduga, sikap saya adalah...",Komentar40,"Dalam hal evaluasi kekuatan dan kelemahan diri, sikap saya adalah...",Komentar41,"Setelah mengalami suatu pengalaman kerja, sikap saya adalah...",Komentar42,"Ketika menerima kritik atau masukan, sikap saya adalah...",Komentar43,Sikap saya terhadap pengembangan diri adalah...,Komentar44,"Dalam hal perilaku saya mempengaruhi orang lain, sikap saya adalah..",Komentar45,Sikap saya terhadap kinerja diri saya adalah..,Komentar46,"Ketika melakukan kesalahan, sikap saya adalah...",Komentar47,"Dalam menilai kemampuan diri, sikap saya adalah...",Komentar48,"Dalam hal refleksi diri, sikap saya adalah...",Komentar49,"Dalam situasi yang memicu emosi, sikap saya adalah...",Komentar50
0,2,2026-01-21 13:46:01,2026-01-21 14:12:57,rachma.deyana@fiberstar.co.id,Rachma Deyana,NaN,Rachma Deyana,CEO Office,Internal Audit & Risk Management,Internal Audit Non Network,Secara alami menghubungkan berbagai perspektif untuk menemukan pendekatan inovatif.,NaN,Cepat memahami konsep baru yang kompleks dan terdorong untuk mengkajinya lebih dalam.,AI sangat membantu saya jika kesulitan memahami konsep baru jd tinggal self learning dan penjela...,Menghadapi kerumitan dengan beberapa panduan.,kadang tergantung case,Menemukan akar masalah untuk situasi yang sederhana.,NaN,Menjelaskan konsep kompleks dengan cara yang mudah dipahami.,NaN,"Terbuka pada ide baru dalam konteks tertentu, terutama jika ada waktu dan sumber daya.",NaN,Mencari beberapa variasi solusi dan mencoba menggunakan cara baru.,NaN,Tetap bertumbuh dalam kondisi ketidakpastian dan memanfaatkannya untuk menciptakan solusi baru.,NaN,"Secara rutin bertanya ""mengapa"" dan ""bagaimana"" untuk memahami akar masalah.",NaN,Melihat hubungan yang jelas dan langsung antar konsep yang serupa.,NaN,Mudah beradaptasi dengan berbagai tipe orang dan menjaga kerja sama positif.,NaN,Mengelola konflik secara terbuka dan mencari solusi yang adil.,NaN,Secara aktif meminta masukan dan memanfaatkannya untuk berkembang lebih cepat.,NaN,Menjadi penengah yang dipercaya dan menyelesaikan konflik secara konstruktif.,NaN,Merasakan empati dan memahami perspektif orang lain secara mendalam.,NaN,Secara aktif mengeksplorasi dan mengintegrasikan sudut pandang berbeda untuk keputusan yang lebi...,NaN,Bekerja dengan orang berkepribadian sulit dengan menetapkan batasan yang jelas.,"selagi tidak merugikan, tetap bekerja dan berkomunikasi secara profesional",Mengintegrasikan berbagai pandangan untuk menciptakan solusi terbaik.,"jika menurut saya benar, tidak ada salahnya untuk meluruskan pandangan yg salah dr orang lain",Menunjukkan rasa ingin tahu yang tulus dan membangun hubungan bermakna.,NaN,"Fokus pada pembicara, menjaga kontak mata, dan merangkum poin-poin penting.",NaN,Beradaptasi dengan cepat dan tetap produktif dalam perubahan mendadak.,NaN,Melihat perubahan sebagai kesempatan belajar dan peningkatan diri.,NaN,Cepat menyesuaikan diri dan mengoptimalkan sistem atau prosedur baru.,NaN,Menerima perubahan dengan bantuan dan penjelasan tambahan.,NaN,Secara aktif mencari cara atau pendekatan baru dan mendorong inovasi.,NaN,Memanfaatkan ketidakpastian untuk mengambil langkah strategis.,NaN,Menyesuaikan diri setelah memahami dasar perubahan.,NaN,Secara konsisten mengusulkan ide baru yang relevan dan bermanfaat.,NaN,Memiliki keinginan untuk memiliki pengetahuan dan belajar lintas bidang.,NaN,"Tidak hanya mengantisipasi perubahan, tetapi secara aktif prediksi situasi kedepannya.",NaN,Tetap fokus dan produktif meskipun menghadapi tekanan yang berat.,NaN,Membuat keputusan yang sangat efektif dan tetap tenang dalam kondisi yang tidak jelas.,NaN,Menargetkan pencapaian luar biasa dan standar tinggi.,NaN,Mampu menyelesaikan tugas meskipun sulit.,NaN,Secara aktif belajar dari kegagalan dan keberhasilan.,NaN,Menyelesaikan tugas dengan kualitas yang cukup baik dan stabil.,NaN,Menyesuaikan strategi secara mandiri untuk hasil yang lebih baik.,NaN,Memahami pentingnya hasil tetapi masih fokus pada proses.,NaN,Secara aktif menciptakan peluang baru dan mengantisipasi masalah sebelum terjadi.,NaN,Secara proaktif mengantisipasi potensi rintangan dan menyiapkan rencana pencegahan sebelumnya.,NaN,Secara rutin mengevaluasi perkembangan kemampuan diri dan menyesuaikan diri berdasarkan refleksi...,NaN,Secara konsisten mengevaluasi diri dan meningkatkan kinerja berdasarkan pembelajaran.,NaN,Menerima kritik dengan baik dan menggunakannya untuk memperbaiki diri.,NaN,Memprioritaskan pengembangan diri dan mengambil inisiatif tanpa menunggu dorongan.,NaN,Sangat peka terhadap dampak perilaku dan mampu mengelolanya secara positif.,NaN,Cukup sering meminta pendapat untuk meningkatkan kinerja.,NaN,Secara konsisten mengakui kesalahan dan belajar darinya.,NaN,Menilai diri secara realistis dan objektif.,NaN,Memiliki refleksi diri yang mendalam dan berkelanjutan dalam pengambilan keputusan.,NaN,Dapat mengelola emosi secara baik,NaN
1,3,2026-01-21 13:42:50,2026-01-21 14:38:56,agung.sedayu@fiberstar.co.id,Agung Sedayu,NaN,Agung Sedayu,CEO Office,Internal Audit & Risk Management,Internal Audit & Risk Management Department Head Plt,Secara aktif mempertimbangkan banyak perspektif sebelum memutuskan sesuatu.,Diskusi dengan Unit Head maupun Division Head,Memahami konsep baru dengan baik jika ada penjelasan bertahap.,Mempelajari konsep baru dan mencari penjelasan tentang hal tersebut,Menghadapi kerumitan sebagai peluang untuk menciptakan terobosan.,Mencoba mencari jalan keluar dengan beberapa pilihan,Menemukan akar masalah setelah melakukan analisis.,Analisa penting agar tepat dalam mengidentifikasi akar masalah,Mengemas ide kompleks menjadi penjelasan yang sederhana dan inspiratif.,Menjelaskan dengan analogi dan contoh yang mudah dimengerti oleh team,Aktif mencari ide baru dan melihatnya sebagai peluang perbaikan dan inovasi.,Brainstorming dengan team untuk menggali ide ide baru yang dapat di implementasikan,Mencari beberapa variasi solusi dan mencoba menggunakan cara baru.,Dengan variasi solusi diharapkan menemukan pemecahan masalah yang lebih baik dari sebelumnya,Tetap bertumbuh dalam kondisi ketidakpastian dan memanfaatkannya untuk menciptakan solusi baru.,Tetap memberikan usaha yang terbaik untuk perusahaan,Secara sistematis menantang asumsi dan mencari perspektif berlawanan.,Informasi harus selalu di uji validitas nya dan manfaat nya,"Secara alami berpikir holistik, melihat pola dan keterkaitan antar konsep.",Melatih sudut pandang dr sisi yang berbeda untuk mendapatkan informasi secara lengkap,Mudah beradaptasi dengan berbagai tipe orang dan menjaga kerja sama positif.,Menjalin kerjasama dengan di dasari semangat teamwork,Mengelola konflik secara terbuka dan mencari solusi yang adil.,Mengatasi konflik secepat nya dan tidak menunda nunda untuk diselesaikan,Terbuka terhadap masukan jika disampaikan dengan jelas.,"Tidak menutup diri dari saran orang lain, siapa tau saran mereka justru tepat sasaran dan solutif",Menjadi penengah yang dipercaya dan menyelesaikan konflik secara konstruktif.,Mencari informasi dari kedua belah pihak secara bersamaan dan diselesaikan bersama,Peka terhadap emosi orang lain dan merespons secara penuh empati.,NaN,Terbuka dan fleksibel dalam memahami berbagai perspektif.,NaN,Menjaga hubungan yang harmonis dengan individu yang menantang,NaN,Menghargai dan mempertimbangkan pandangan yang berbeda.,NaN,"Menunjukkan ketertarikan pada orang lain diluar konteks kerja, terutama dengan rekan dekat.",NaN,"Fokus pada pembicara, menjaga kontak mata, dan merangkum poin-poin penting.",NaN,Beradaptasi dengan cepat dan tetap produktif dalam perubahan mendadak.,NaN,Melihat perubahan sebagai kesempatan belajar dan peningkatan diri.,NaN,Beradaptasi dengan cepat dengan sistem atau prosedur baru danmembantu orang lain beradaptasi.,NaN,Mendukung perubahan dan mendorong orang lain untuk berubah.,NaN,Mencoba pendekatan baru meskipun hasilnya belum jelas.,NaN,Tetap tenang dan mampu mengambil keputusan yang tepat dalam situasi yang tidak pasti.,NaN,Menyesuaikan diri setelah memahami dasar perubahan.,NaN,Secara konsisten mengusulkan ide baru yang relevan dan bermanfaat.,NaN,Belajar berbagai pengetahuan dan keterampilan lain untuk nilai tambah diri.,NaN,"Tidak hanya mengantisipasi perubahan, tetapi secara aktif prediksi situasi kedepannya.",NaN,Tetap fokus dan produktif meskipun menghadapi tekanan yang berat.,NaN,Membuat keputusan yang memadai dalam kondisi ketidakjelasan.,NaN,Secara konsisten mendorong diri untuk mencapai hasil optimal.,NaN,Bertahan dengan baik dalam tantangan yang cukup sulit.,NaN,Secara aktif belajar dari kegagalan dan keberhasilan.,NaN,Menyelesaikan tugas dengan kualitas yang cukup baik dan stabil.,NaN,Menyesuaikan strategi ketika ada arahan atau saran.,NaN,Menilai keberhasilan secara seimbang antara proses dan hasil.,NaN,Mengambil inisiatif untuk menangani masalah dalam area tanggung jawab.,NaN,"Tetap tenang saat menghadapi hambatan, mencoba beberapa alternatif sebelum meminta bantuan.",NaN,Menjadikan evaluasi diri sebagai kebiasaan dan mengintegrasikannya dalam setiap keputusan dan re...,NaN,Secara konsisten mengevaluasi diri dan meningkatkan kinerja berdasarkan pembelajaran.,NaN,Menerima kritik dengan baik dan menggunakannya untuk memperbaiki diri.,NaN,Memprioritaskan pengembangan diri dan mengambil inisiatif tanpa menunggu dorongan.,NaN,Cukup sadar bagaimana perilaku saya dapat memengaruhi orang lain.,NaN,Mau meminta pendapat tetapi hanya pada situasi tertentu.,NaN,Sangat terbuka mengakui kesalahan dan menjadikannya sumber pembelajaran.,NaN,Menilai diri secara realistis dan objektif.,NaN,Memiliki refleksi diri yang mendalam dan berkelanjutan dalam pengambilan keputusan.,NaN,Dapat mengelola emosi secara baik,NaN
2,4,2026-01-21 13:46:45,2026-01-21 14:59:17,kharisma.wulandhari@fiberstar.co.id,Kharisma Wulandhari,NaN,Kharisma Wulandhari,CEO Office,Internal Audit & Risk Management,Internal Audit Non Network,Secara aktif mempertimbangkan banyak perspektif sebelum memutuskan sesuatu.,NaN,Mengalami kesulitan memahami konsep baru tanpa panduan yang jelas.,NaN,Menghindari kerumitan dan memilih masalah yang lebih sederhana.,NaN,Mampu mengurai masalah kompleks dan menemukan akar penyebabnya.,NaN,Menjelaskan ide dengan menggunakan banyak contoh.,NaN,Secara alami tertarik pada ide baru dan memulai eksplorasi ide kreatif tanpa diminta.,NaN,Mencari beberapa variasi solusi dan mencoba menggunakan cara baru.,NaN,Mampu mengelola ketidakjelasan dengan bantuan.,NaN,"Mulai mengajukan pertanyaan dasar (""apa"", ""kapan"", ""di mana"") untuk klarifikasi fakta.",NaN,"Secara alami berpikir holistik, melihat pola dan keterkaitan antar konsep.",NaN,"Sangat cepat membangun hubungan kerja yang efektif dengan siapa pun, termasuk yang sangat berbeda.",NaN,Menangani konflik sederhana dengan beberapa dukungan.,NaN,Terbuka terhadap masukan jika disampaikan dengan jelas.,NaN,Berperan sebagai penengah ketika situasi tidak terlalu rumit.,NaN,Mampu membaca emosi dasar orang lain.,NaN,Secara aktif mengeksplorasi dan mengintegrasikan sudut pandang berbeda untuk keputusan yang lebi...,NaN,Secara efektif membangun hubungan positif bahkan dengan orang yang sangat sulit.,NaN,Menghargai dan mempertimbangkan pandangan yang berbeda.,NaN,"Menunjukkan ketertarikan pada orang lain diluar konteks kerja, terutama dengan rekan dekat.",NaN,"Fokus pada pembicara, menjaga kontak mata, dan merangkum poin-poin penting.",NaN,Nyaman dengan perubahan dan melihatnya sebagai peluang untuk berkembang.,NaN,Melihat perubahan dan menyesuaikan diri ketika diperlukan.,NaN,Beradaptasi dengan baik jika ada panduan yang jelas,NaN,Menolak perubahan dan merasa sulit beradaptasi.,NaN,Mengambil risiko yang terukur dalam situasi tertentu.,NaN,Berusaha tenang tetapi sering kehilangan fokus dalam situasi yang tidak pasti.,NaN,Menyesuaikan diri setelah memahami dasar perubahan.,NaN,Memberikan saran yang relevan untuk perbaikan proses.,NaN,Tertarik pada hal baru namun tidak mendalami.,NaN,Secara aktif memindai lingkungan dan menyiapkan rencana menghadapi perubahan.,NaN,Berusaha tetap fokus tetapi sering terganggu ketika tekanan meningkat.,NaN,Membuat keputusan yang sangat efektif dan tetap tenang dalam kondisi yang tidak jelas.,NaN,Termotivasi tetapi sering membutuhkan dorongan.,NaN,Mampu menyelesaikan tugas meskipun sulit.,NaN,Secara konsisten mengubah pembelajaran menjadi peningkatan kinerja nyata.,NaN,Menyelesaikan tugas dengan kualitas yang cukup baik dan stabil.,NaN,Menyesuaikan strategi secara mandiri untuk hasil yang lebih baik.,NaN,Memahami pentingnya hasil tetapi masih fokus pada proses.,NaN,Mengambil inisiatif untuk menangani masalah dalam area tanggung jawab.,NaN,Secara proaktif mengantisipasi potensi rintangan dan menyiapkan rencana pencegahan sebelumnya.,NaN,"Sesekali merefleksikan kekuatan dan kelemahan, terutama setelah pengalaman penting atau kegagalan.",NaN,Cukup sering melakukan evaluasi setelah pengalaman penting.,NaN,Terbuka terhadap kritik dan secara aktif mencarinya untuk berkembang.,NaN,Memprioritaskan pengembangan diri dan mengambil inisiatif tanpa menunggu dorongan.,NaN,Sangat memahami dampaknya dan menyesuaikan perilaku dengan baik.,NaN,Mau meminta pendapat tetapi hanya pada situasi tertentu.,NaN,Secara konsisten mengakui kesalahan dan belajar darinya.,NaN,Berusaha objektif tetapi masih mudah terpengaruh persepsi pribadi.,NaN,"Secara konsisten menganalisis pola pikir, nilai, dan pemicu emosi dibalik tindakan.",NaN,Dapat mengelola emosi secara baik,NaN

In [6]:
self_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Columns: 110 entries, ID to Komentar50
dtypes: datetime64[us](2), float64(1), int64(1), str(106)
memory usage: 227.3 KB

In [7]:
#cell 6

superior_df.head()

,ID,Start time,Completion time,Email,Name,Last modified time,Nama bawahan yang dinilai,Direktorat,Departemen,Unit,"Ketika ada dalam situasi yang mengharuskan pengambilan keputusan atas masalah yang dihadapi, sikap bawahan saya adalah..",Komentar,"Ketika menghadapi konsep baru yang rumit, sikap bawahan saya adalah..",Komentar2,"Ketika ada dalam yang situasi yang rumit dan belum memiliki kejelasan arah, sikap bawahan saya adalah..",Komentar3,"Dalam mengidentifikasi akar masalah dalam situasi kompleks, sikap bawahan saya adalah....",Komentar4,"Ketika menjelaskan ide atau masalah yang kompleks kepada orang lain, sikap bawahan saya adalah...",Komentar5,"Saat menghadapi ide - ide baru yang belum terbukti efektivitasnya, sikap bawahan saya adalah...",Komentar6,"Dalam menghadapi masalah lama menggunakan cara - cara baru, sikap bawahan saya adalah..",Komentar7,"Ketika menghadapi ketidakpastian dalam bekerja, sikap bawahan saya adalah..",Komentar8,"Saat menerima informasi, Sikap bawahan saya adalah...",Komentar9,"Ketika menghadapi konsep yang tampak tidak saling berkaitan, sikap bawahan saya adalah...",Komentar10,"Dalam situasi bekerja dengan orang yang memiliki latar belakang berbeda, sikap bawahan saya adalah...",Komentar11,"Dalam menghadapi konflik kerja, sikap bawahan saya adalah...",Komentar12,"Dalam hal menerima masukan atau umpan balik dari rekan kerja, sikap bawahan saya adalah...",Komentar13,"Saat menghadapi situasi konflik antarrekan kerja, sikap bawahan saya adalah...",Komentar14,"Dalam hal memahami emosi dan perasaan orang lain, sikap bawahan saya adalah...",Komentar15,"Dalam situasi munculnya perbedaan sudut pandang, sikap bawahan saya adalah...",Komentar16,"Dalam hal menjaga hubungan baik dengan individu yang sulit, sikap bawahan saya adalah...",Komentar17,"Dalam hal menghadapi pendapat orang lain yang berbeda dengan saya, sikap bawahan saya adalah...",Komentar18,"Dalam hal menyelesaikan tugas dan butuh berinteraksi dengan rekan kerja, sikap bawahan saya adalah...",Komentar19,"Dalam hal mendengarkan orang lain, sikap bawahan saya adalah...",Komentar20,"Ketika menghadapi perubahan mendadak, sikap bawahan saya adalah...",Komentar21,"Dalam hal menilai perubahan yang terjadi, sikap bawahan saya adalah...",Komentar22,"Dalam hal penerapan sistem atau prosedur baru, sikap bawahan saya adalah...",Komentar23,"Dalam hal perubahan karena ketidakpastian, sikap bawahan saya adalah...",Komentar24,"Ketika mencoba cara atau pendekatan baru, sikap bawahan saya adalah...",Komentar25,"Dalam hal menghadapi situasi yang tidak pasti, sikap bawahan saya adalah...",Komentar26,"Ketika diterapkan cara kerja baru, sikap bawahan saya adalah...",Komentar27,"Dalam hal inisiatif ide/cara baru, sikap bawahan saya adalah...",Komentar28,"Dalam hal rasa ingin tahu dan keinginan belajar, sikap bawahan saya adalah...",Komentar29,"Dalam hal mengatisipasi perubahan, sikap bawahan saya adalah...",Komentar30,"Ketika menghadapi tekanan atau hambatan, sikap bawahan saya adalah...",Komentar31,"Dalam hal pengambilan keputusan dalam situasi yang tidak jelas, sikap bawahan saya adalah...",Komentar32,"Dalam hal dorongan untuk mencapai hasil terbaik, sikap bawahan saya adalah....",Komentar33,"Ketika menghadapi tantangan berat, sikap bawahan saya adalah...",Komentar34,"Setelah mengalami keberhasilan atau kegagalan, sikap bawahan saya adalah...",Komentar35,Sikap bawahan saya terhadap tugas kerja adalah...,Komentar36,"Ketika strategi kerja tidak lagi efektif, sikap bawahan saya adalah...",Komentar37,"Dalam menilai keberhasilan kerja, sikap bawahan saya adalah...",Komentar38,"Dalam hal melihat peluang atau masalah, sikap bawahan saya adalah...",Komentar39,"Ketika menghadapi rintangan tak terduga, sikap bawahan saya adalah...",Komentar40,"Dalam hal evaluasi kekuatan dan kelemahan diri, sikap bawahan saya adalah...",Komentar41,"Setelah mengalami suatu pengalaman kerja, sikap bawahan saya adalah...",Komentar42,"Ketika menerima kritik atau masukan, sikap bawahan saya adalah...",Komentar43,Sikap bawahan saya terhadap pengembangan diri adalah...,Komentar44,"Dalam hal perilaku saya mempengaruhi orang lain, sikap bawahan saya adalah..",Komentar45,Sikap bawahan saya terhadap kinerja dirinya adalah..,Komentar46,"Ketika melakukan kesalahan, sikap bawahan saya adalah...",Komentar47,"Dalam menilai kemampuan diri, sikap bawahan saya adalah...",Komentar48,"Dalam hal refleksi diri, sikap bawahan saya adalah...",Komentar49,"Dalam situasi yang memicu emosi, sikap bawahan saya adalah..."
0,1,2026-01-21 15:07:03,2026-01-21 15:27:00,agung.sedayu@fiberstar.co.id,Agung Sedayu,NaN,Deddie Yunawan Wicaksono Drajat,CEO Office,Internal Audit & Risk Management,Risk Management,Melihat beberapa sudut pandang ketika situasi mengharuskan.,NaN,Memahami konsep baru dengan baik jika ada penjelasan bertahap.,NaN,Menghadapi kerumitan sebagai peluang untuk menciptakan terobosan.,NaN,Menemukan akar masalah setelah melakukan analisis.,NaN,Menjelaskan konsep kompleks dengan cara yang mudah dipahami.,NaN,Aktif mencari ide baru dan melihatnya sebagai peluang perbaikan dan inovasi.,NaN,Mencari beberapa variasi solusi dan mencoba menggunakan cara baru.,NaN,Tetap bertumbuh dalam kondisi ketidakpastian dan memanfaatkannya untuk menciptakan solusi baru.,NaN,Secara sistematis menantang asumsi dan mencari perspektif berlawanan.,NaN,"Secara alami berpikir holistik, melihat pola dan keterkaitan antar konsep.",NaN,Mudah beradaptasi dengan berbagai tipe orang dan menjaga kerja sama positif.,NaN,Menangani konflik dengan percaya diri dan mengubahnya menjadi kesempatan memperkuat hubungan.,NaN,Terbuka terhadap masukan jika disampaikan dengan jelas.,NaN,Menjadi mediator yang efektif dalam situasi konflik yang kompleks.,NaN,Peka terhadap emosi orang lain dan merespons secara penuh empati.,NaN,Terbuka dan fleksibel dalam memahami berbagai perspektif.,NaN,Secara efektif membangun hubungan positif bahkan dengan orang yang sangat sulit.,NaN,Menghargai dan mempertimbangkan pandangan yang berbeda.,NaN,Bertanya sebatas kebutuhan kerja dan cepat kembali ke tugas.,NaN,"Mendengarkan perasaan dan emosi di balik kata-kata, merespons dengan logis.",NaN,Beradaptasi dengan cepat dan tetap produktif dalam perubahan mendadak.,NaN,Melihat perubahan sebagai kesempatan belajar dan peningkatan diri.,NaN,Beradaptasi dengan cepat dengan sistem atau prosedur baru danmembantu orang lain beradaptasi.,NaN,Menerima perubahan dan mampu beradaptasi dengan baik.,NaN,Mengambil risiko yang terukur dalam situasi tertentu.,NaN,Tetap tenang dan mampu mengambil keputusan yang tepat dalam situasi yang tidak pasti.,NaN,Menyesuaikan diri setelah memahami dasar perubahan.,NaN,Memberikan saran yang relevan untuk perbaikan proses.,NaN,Memiliki keinginan untuk memiliki pengetahuan dan belajar lintas bidang.,NaN,Secara aktif memindai lingkungan dan menyiapkan rencana menghadapi perubahan.,NaN,Tetap fokus dan produktif meskipun menghadapi tekanan yang berat.,NaN,Membuat keputusan yang memadai dalam kondisi ketidakjelasan.,NaN,Selalu termotivasi untuk mencapai hasil yang baik.,NaN,Bertahan dengan baik dalam tantangan yang cukup sulit.,NaN,Secara aktif belajar dari kegagalan dan keberhasilan.,NaN,Menyelesaikan tugas dengan kualitas yang cukup baik dan stabil.,NaN,Secara proaktif menciptakan strategi baru yang meningkatkan hasil.,NaN,Menilai keberhasilan secara seimbang antara proses dan hasil.,NaN,Menunggu instruksi yang jelas dan spesifik sebelum bertindak.,NaN,"Tetap tenang saat menghadapi hambatan, mencoba beberapa alternatif sebelum meminta bantuan.",NaN,Menjadikan evaluasi diri sebagai kebiasaan dan mengintegrasikannya dalam setiap keputusan dan re...,NaN,Secara konsisten mengevaluasi diri dan meningkatkan kinerja berdasarkan pembelajaran.,NaN,Menerima kritik dengan baik dan menggunakannya untuk memperbaiki diri.,NaN,Menyadari pentingnya pengembangan diri tetapi belum memprioritaskannya.,NaN,Sangat memahami dampaknya dan menyesuaikan perilaku dengan baik.,NaN,Mau meminta pendapat tetapi hanya pada situasi tertentu.,NaN,Sangat terbuka mengakui kesalahan dan menjadikannya sumber pembelajaran.,NaN,Mampu mengevaluasi kemampuan diri secara objektifserta berbasis data.,NaN,Memiliki refleksi diri yang mendalam dan berkelanjutan dalam pengambilan keputusan.,NaN,Mengidentifikasi emosi yang muncul dan memilih respons yang lebih konstruktif.
1,2,2026-01-22 09:16:53,2026-01-22 09:43:55,rachma.deyana@fiberstar.co.id,Rachma Deyana,NaN,Ade Rizqie Fonna,CEO Office,Internal Audit & Risk Management,Internal Audit Non Network,Secara aktif mempertimbangkan banyak perspektif sebelum memutuskan sesuatu.,NaN,Memahami konsep baru dengan baik jika ada penjelasan bertahap.,NaN,"Mencoba menghadapi kerumitan, tetapi saat situasi membingungkan akan memilih masalah yang lebih...",NaN,Menemukan akar masalah untuk situasi yang sederhana.,NaN,Menjelaskan ide dengan menggunakan banyak contoh.,NaN,Hanya menggunakan metode yang sudah sangat familiar.,NaN,Secara kreatif menciptakan pendekatan inovatif untuk masalah berulang.,"contohnya jika ada masalah berulang, fonna akan membuat alur atau template agar masalah trsebut ...",Nyaman bekerja dalam situasi ambigu dan tetap produktif.,NaN,"Secara rutin bertanya ""mengapa"" dan ""bagaimana"" untuk memahami akar masalah.",NaN,Hanya melihat konsep secara terpisah satu sama lain.,NaN,"Sangat cepat membangun hubungan kerja yang efektif dengan siapa pun, termasuk yang sangat berbeda.",banyak temen dr divisi apapun,Menangani konflik sederhana dengan beberapa dukungan.,NaN,Menerima masukan tetapi memilih yang dianggap aman.,NaN,Menjadi penengah yang dipercaya dan menyelesaikan konflik secara konstruktif.,NaN,Merasakan empati dan memahami perspektif orang lain secara mendalam.,NaN,Menerima perspektif berbeda jika dijelaskan secara logis.,NaN,Mudah terganggu oleh orang berkepribadian sulit dan menjaga jarak.,NaN,Menghargai perbedaan pendapat dalam konteks kerja.,NaN,"Menunjukkan ketertarikan pada orang lain diluar konteks kerja, terutama dengan rekan dekat.",NaN,Mendengarkan dengan penuh empati dan merasa memahami pembicara.,NaN,Mampu beradaptasi jika perubahan dijelaskan dengan jelas.,NaN,Melihat perubahan dan menyesuaikan diri ketika diperlukan.,NaN,Cepat menyesuaikan diri dan mengoptimalkan sistem atau prosedur baru.,NaN,Menerima perubahan dan mampu beradaptasi dengan baik.,NaN,Secara aktif mencari cara atau pendekatan baru dan mendorong inovasi.,NaN,Memanfaatkan ketidakpastian untuk mengambil langkah strategis.,NaN,Nyaman bekerja dengan pendekatan baru dan cepat menyesuaikan diri.,NaN,Memberikan saran yang relevan untuk perbaikan proses.,NaN,Tertarik pada hal baru namun tidak mendalami.,NaN,Memperhatikan tanda-tanda perubahan dan mempersiapkan diri secara terbatas.,NaN,Tetap fokus dan produktif meskipun menghadapi tekanan yang berat.,NaN,Menghindari mengambil keputusan ketika informasi tidak lengkap.,NaN,Termotivasi tetapi sering membutuhkan dorongan.,NaN,Mampu menyelesaikan tugas meskipun sulit.,NaN,Cukup sering mengambil pelajaran dari kegagalan dan keberhasilan.,NaN,Secara konsisten menghasilkan pekerjaan berkualitas tinggi tepat waktu.,NaN,Menyesuaikan strategi secara mandiri untuk hasil yang lebih baik.,NaN,Sangat berorientasi pada hasil dan mengukur keberhasilan berdasarkan dampak nyata.,NaN,Secara aktif menciptakan peluang baru dan mengantisipasi masalah sebelum terjadi.,NaN,"Tetap tenang saat menghadapi hambatan, mencoba beberapa alternatif sebelum meminta bantuan.",NaN,"Sesekali merefleksikan kekuatan dan kelemahan, terutama setelah pengalaman penting atau kegagalan.",NaN,Sangat reflektif dan menjadikan evaluasi diri sebagai kebiasaan utama untuk berkembang.,NaN,Menerima kritik walau merasa tidak nyaman.,NaN,Melakukan pengembangan diri ketika dibutuhkan.,NaN,Sangat peka terhadap dampak perilaku dan mampu mengelolanya secara positif.,NaN,Mau meminta pendapat tetapi hanya pada situasi tertentu.,NaN,Secara konsisten mengakui kesalahan dan belajar darinya.,NaN,Berusaha objektif tetapi masih mudah terpengaruh persepsi pribadi.,NaN,"Secara konsisten menganalisis pola pikir, nilai, dan pemicu emosi dibalik tindakan.",NaN,"Memiliki kendali penuh atas respons emosional, bahkan dalam situasi yang sangat menekan."
2,3,2026-01-22 09:13:34,2026-01-22 10:08:13,agung.sedayu@fiberstar.co.id,Agung Sedayu,NaN,Ujang Yusup Sulaeman,CEO Office,Internal Audit & Risk Management,Internal Audit Network,Melihat beberapa sudut pandang ketika situasi mengharuskan.,NaN,Memahami konsep baru dengan baik jika ada penjelasan bertahap.,NaN,Menghadapi kerumitan sebagai peluang untuk menciptakan terobosan.,NaN,Menemukan akar masalah setelah melakukan analisis.,NaN,Menjelaskan konsep kompleks dengan cara yang mudah dipahami.,NaN,Aktif mencari ide baru dan melihatnya sebagai peluang perbaikan dan inovasi.,NaN,Mencari beberapa variasi solusi dan mencoba menggunakan cara baru.,NaN,Mampu mengelola ketidakjelasan dengan bantuan.,NaN,"Mulai mengajukan pertanyaan dasar (""apa"", ""kapan"", ""di mana"") untuk klarifikasi fakta.",NaN,"Secara alami berpikir holistik, melihat pola dan keterkaitan antar konsep.",NaN,Mudah beradaptasi dengan berbagai tipe orang dan menjaga kerja sama positif.,NaN,Menangani konflik sederhana dengan beberapa dukungan.,NaN,Menerima masukan dengan baik dan menggunakannya untuk memperbaiki diri.,NaN,Menjadi penengah yang dipercaya dan menyelesaikan konflik secara konstruktif.,NaN,Mampu membaca emosi dasar orang lain.,NaN,Terbuka dan fleksibel dalam memahami berbagai perspektif.,NaN,Menjaga hubungan yang harmonis dengan individu yang menantang,NaN,Menghargai dan mempertimbangkan pandangan yang berbeda.,NaN,"Menunjukkan ketertarikan pada orang lain diluar konteks kerja, terutama dengan rekan dekat.",NaN,Mendengarkan dengan penuh empati dan merasa memahami pembicara.,NaN,Mampu beradaptasi jika perubahan dijelaskan dengan jelas.,NaN,Melihat perubahan sebagai kesempatan belajar dan peningkatan diri.,NaN,Beradaptasi dengan baik jika ada panduan yang jelas,NaN,Menerima perubahan dan mampu beradaptasi dengan baik.,NaN,Mencoba pendekatan baru meskipun hasilnya belum jelas.,NaN,Mengelola diri dengan cukup baik dalam ketidakpastian.,NaN,Menyesuaikan diri setelah memahami dasar perubahan.,NaN,Secara proaktif menciptakan ide inovatif dan menginspirasi orang lain.,NaN,Belajar berbagai pengetahuan dan keterampilan lain untuk nilai tambah diri.,NaN,Memperhatikan tanda-tanda perubahan dan mempersiapkan diri secara terbatas.,NaN,Cukup mampu menjaga fokus dengan dukungan.,NaN,Membuat keputusan yang memadai dalam kondisi ketidakjelasan.,NaN,Selalu termotivasi untuk mencapai hasil yang baik.,NaN,Mampu menuntaskan tantangan berat hingga tuntas.,NaN,Secara aktif belajar dari kegagalan dan keberhasilan.,NaN,Menyelesaikan tugas dengan kualitas yang cukup baik dan stabil.,NaN,Secara proaktif menciptakan strategi baru yang meningkatkan hasil.,NaN,Sangat berorientasi pada hasil dan mengukur keberhasilan berdasarkan dampak nyata.,NaN,Mengidentifikasi peluang/ masalah tetapi menunggu persetujuan sebelum bertindak.,NaN,"Tetap tenang saat menghadapi hambatan, mencoba beberapa alternatif sebelum meminta bantuan.",NaN,Menjadikan evaluasi diri sebagai kebiasaan dan mengintegrasikannya dalam setiap keputusan dan re...,NaN,Sangat reflektif dan menjadikan evaluasi diri sebagai kebiasaan utama untuk berkembang.,NaN,Menerima kritik dengan baik dan menggunakannya untuk memperbaiki diri.,NaN,Menyadari pentingnya pengembangan diri tetapi belum memprioritaskannya.,NaN,Sangat memahami dampaknya dan menyesuaikan perilaku dengan baik.,NaN,Sangat proaktif mencari umpan balik dari berbagai sumber untuk pertumbuhan diri.,NaN,Sangat terbuka mengakui kesalahan dan menjadikannya sumber pembelajaran.,NaN,Menilai diri secara realistis dan objektif.,NaN,Memiliki refleksi diri yang mendalam dan berkelanjutan dalam pengambilan keputusan.,NaN,Mengidentifikasi emosi yang muncul dan memilih respons yang lebih konstruktif.
3,4,2026-01-22 10:08:47,2026-01-22 11:01:34,agung.sedayu@fiberstar.co.id,Agung Sedayu,NaN,Rachma Deyana,CEO Office,Internal Audit & Risk Management,Internal Audit Non Network,Secara aktif mempertimbangkan banyak perspektif sebelum memutuskan sesuatu.,NaN,Memahami konsep baru dengan baik jika ada penjelasan bertahap.,NaN,Menghadapi kerumitan sebagai peluang untuk menciptakan terobosan.,NaN,Menemukan akar masalah setelah melakukan analisis.,NaN,Menjelaskan konsep kompleks dengan cara yang mudah dipahami.,NaN,Secara alami tertarik pada ide baru dan memulai eksplorasi ide kreatif tanpa diminta.,NaN,Mencari beberapa variasi solusi dan mencoba menggunakan cara baru.,NaN,Tetap bertumbuh dalam kondisi ketidakpastian dan memanfaatkannya untuk menciptakan solusi baru.,NaN,"Mulai mengajukan pertanyaan dasar (""apa"", ""kapan"", ""di mana"") untuk klarifikasi fakta.",NaN,"Secara alami berpikir holistik, melihat pola dan keterkaitan antar konsep.",NaN,Mudah beradaptasi dengan berbagai tipe orang dan menjaga kerja sama positif.,NaN,Mengelola konflik secara terbuka dan mencari solusi yang adil.,NaN,Menerima masukan dengan baik dan menggunakannya untuk memperbaiki diri.,NaN,Menjadi penengah yang dipercaya dan menyelesaikan konflik secara konstruktif.,NaN,Peka terhadap emosi orang lain dan merespons secara penuh empati.,NaN,Terbuka dan fleksibel dalam memahami berbagai perspektif.,NaN,Menjaga hubungan yang harmonis dengan individu yang menantang,NaN,Mengintegrasikan berbagai pandangan untuk menciptakan solusi terbaik.,NaN,Berkomunikasi seperlunya dan menghindari percakapan personal.,NaN,"Fokus pada pembicara, menjaga kontak mata, dan merangkum poin-poin penting.",NaN,Mampu beradaptasi jika perubahan dijelaskan dengan jelas.,NaN,Melihat perubahan sebagai kesempatan belajar dan peningkatan diri.,NaN,Beradaptasi dengan baik jika ada panduan yang jelas,NaN,Menerima perubahan dan mampu beradaptasi dengan baik.,NaN,Secara aktif mencari cara atau pendekatan baru dan mendorong inovasi.,NaN,Mengelola diri dengan cukup baik dalam ketidakpastian.,NaN,Menyesuaikan diri setelah memahami dasar perubahan.,NaN,Memberikan saran yang relevan untuk perbaikan proses.,NaN,Memiliki keinginan untuk memiliki pengetahuan dan belajar lintas bidang.,NaN,Memperhatikan tanda-tanda perubahan dan mempersiapkan diri secara terbatas.,NaN,Cukup mampu menjaga fokus dengan dukungan.,NaN,Menunda pengambilan keputusan dan menunggu kejelasan lebih lanjut.,NaN,Selalu termotivasi untuk mencapai hasil yang baik.,NaN,Mampu menuntaskan tantangan berat hingga tuntas.,NaN,Cukup sering mengambil pelajaran dari kegagalan dan keberhasilan.,NaN,Menyelesaikan tugas dengan kualitas yang cukup baik dan stabil.,NaN,Menyesuaikan strategi ketika ada arahan atau saran.,NaN,Menilai keberhasilan secara seimbang antara proses dan hasil.,NaN,Mengambil inisiatif untuk menangani masalah dalam area tanggung jawab.,NaN,"Tetap tenang saat menghadapi hambatan, mencoba beberapa alternatif sebelum meminta bantuan.",NaN,Menjadikan evaluasi diri sebagai kebiasaan dan mengintegrasikannya dalam setiap keputusan dan re...,NaN,Secara konsisten mengevaluasi diri dan meningkatkan kinerja berdasarkan pembelajaran.,NaN,Menerima kritik dengan baik dan menggunakannya untuk memperbaiki diri.,NaN,Memprioritaskan pengembangan diri dan mengambil inisiatif tanpa menunggu dorongan.,NaN,Sangat memahami dampaknya dan menyesuaikan perilaku dengan baik.,NaN,Sangat proaktif mencari umpan balik dari berbagai sumber untuk pertumbuhan diri.,NaN,Sangat terbuka mengakui kesalahan dan menjadikannya sumber pembelajaran.,NaN,Menilai diri secara realistis dan objektif.,NaN,Memiliki refleksi diri yang mendalam dan berkelanjutan dalam pengambilan keputusan.,NaN,Dapat mengelola emosi secara baik

In [8]:
superior_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Columns: 109 entries, ID to Dalam situasi yang memicu emosi, sikap bawahan saya adalah...
dtypes: datetime64[us](2), float64(1), int64(1), str(105)
memory usage: 134.4 KB

In [9]:
#cell 7

for i, col in enumerate(self_df.columns, start=1):
    print(i, "->", col)

1 -> ID
2 -> Start time
3 -> Completion time
4 -> Email
5 -> Name
6 -> Last modified time
7 -> Nama
8 -> Direktorat
9 -> Departemen
10 -> Unit
11 -> Ketika ada dalam situasi yang mengharuskan pengambilan keputusan atas masalah yang dihadapi, sikap saya adalah..
12 -> Komentar
13 -> Ketika menghadapi konsep baru yang rumit, sikap saya adalah..
14 -> Komentar2
15 -> Ketika ada dalam yang situasi yang rumit dan belum memiliki kejelasan arah, sikap saya adalah..
16 -> Komentar3
17 -> Dalam mengidentifikasi akar masalah dalam situasi kompleks, sikap saya adalah....
18 -> Komentar4
19 -> Ketika menjelaskan ide atau masalah yang kompleks kepada orang lain, sikap saya adalah...
20 -> Komentar5
21 -> Saat menghadapi ide - ide baru yang belum terbukti efektivitasnya, sikap saya adalah...
22 -> Komentar6
23 -> Dalam menghadapi masalah lama menggunakan cara - cara baru , sikap saya adalah..
24 -> Komentar7
25 -> Ketika menghadapi ketidakpastian dalam bekerja, sikap saya adalah..
26 -> Komentar8
27 -> Saat menerima informasi, Sikap saya adalah...
28 -> Komentar9
29 -> Ketika menghadapi konsep yang tampak tidak saling berkaitan, sikap saya adalah...
30 -> Komentar10
31 -> Dalam situasi bekerja dengan orang yang memiliki latar belakang berbeda, sikap saya adalah...
32 -> Komentar11
33 -> Dalam menghadapi konflik kerja, sikap saya adalah...
34 -> Komentar12
35 -> Dalam hal menerima masukan atau umpan balik dari rekan kerja, sikap saya adalah...
36 -> Komentar13
37 -> Saat menghadapi situasi konflik antarrekan kerja, sikap saya adalah...
38 -> Komentar14
39 -> Dalam hal memahami emosi dan perasaan orang lain , sikap saya adalah...
40 -> Komentar15
41 -> Dalam situasi munculnya perbedaan sudut pandang, sikap saya adalah...
42 -> Komentar16
43 -> Dalam hal menjaga hubungan baik dengan individu yang sulit, sikap saya adalah...
44 -> Komentar17
45 -> Dalam hal menghadapi pendapat orang lain yang berbeda dengan saya, sikap saya adalah...
46 -> Komentar18
47 -> Dalam hal menyelesaikan tugas dan butuh berinteraksi dengan rekan kerja, sikap saya adalah...
48 -> Komentar19
49 -> Dalam hal mendengarkan orang lain, sikap saya adalah...
50 -> Komentar20
51 -> Ketika menghadapi perubahan mendadak, sikap saya adalah...
52 -> Komentar21
53 -> Dalam hal menilai perubahan yang terjadi, sikap saya adalah...
54 -> Komentar22
55 -> Dalam hal penerapan sistem atau prosedur baru, sikap saya adalah...
56 -> Komentar23
57 -> Dalam hal perubahan karena ketidakpastian, sikap saya adalah...
58 -> Komentar24
59 -> Ketika mencoba cara atau pendekatan baru, sikap saya adalah...
60 -> Komentar25
61 -> Dalam hal menghadapi situasi yang tidak pasti, sikap saya adalah...
62 -> Komentar26
63 -> Ketika diterapkan cara kerja baru, sikap saya adalah...
64 -> Komentar27
65 -> Dalam hal inisiatif ide/cara baru, sikap saya adalah...
66 -> Komentar28
67 -> Dalam hal rasa ingin tahu dan keinginan belajar, sikap saya adalah...
68 -> Komentar29
69 -> Dalam hal mengatisipasi perubahan, sikap saya adalah...
70 -> Komentar30
71 -> Ketika menghadapi tekanan atau hambatan, sikap saya adalah...
72 -> Komentar31
73 -> Dalam hal pengambilan keputusan dalam situasi yang tidak jelas, sikap saya adalah...
74 -> Komentar32
75 -> Dalam hal dorongan untuk mencapai hasil terbaik, sikap saya adalah....
76 -> Komentar33
77 -> Ketika menghadapi tantangan berat, sikap saya adalah...
78 -> Komentar34
79 -> Setelah mengalami keberhasilan atau kegagalan, sikap saya adalah...
80 -> Komentar35
81 -> Sikap saya terhadap tugas kerja adalah...
82 -> Komentar36
83 -> Ketika strategi kerja tidak lagi efektif, sikap saya adalah...
84 -> Komentar37
85 -> Dalam menilai keberhasilan kerja, sikap saya adalah...
86 -> Komentar38
87 -> Dalam hal melihat peluang atau masalah, sikap saya adalah...
88 -> Komentar39
89 -> Ketika menghadapi rintangan tak terduga, sikap saya adalah...
90 -> Komentar40
91 -> Dalam hal evaluasi kekuatan dan kelemahan diri, sikap saya adalah...
92 -> Komentar41
93 -> Setelah mengalami suatu pengalaman kerja, sikap saya adalah...
94 -> Komentar42
95 -> Ketika menerima kritik atau masukan, sikap saya adalah...
96 -> Komentar43
97 -> Sikap saya terhadap pengembangan diri adalah...
98 -> Komentar44
99 -> Dalam hal perilaku saya mempengaruhi orang lain, sikap saya adalah..
100 -> Komentar45
101 -> Sikap saya terhadap kinerja diri saya adalah..
102 -> Komentar46
103 -> Ketika melakukan kesalahan, sikap saya adalah...
104 -> Komentar47
105 -> Dalam menilai kemampuan diri, sikap saya adalah...
106 -> Komentar48
107 -> Dalam hal refleksi diri, sikap saya adalah...
108 -> Komentar49
109 -> Dalam situasi yang memicu emosi, sikap saya adalah...
110 -> Komentar50

In [10]:
#cell 8

for i, col in enumerate(superior_df.columns, start=1):
    print(i, "->", col)

1 -> ID
2 -> Start time
3 -> Completion time
4 -> Email
5 -> Name
6 -> Last modified time
7 -> Nama bawahan yang dinilai
8 -> Direktorat
9 -> Departemen
10 -> Unit
11 -> Ketika ada dalam situasi yang mengharuskan pengambilan keputusan atas masalah yang dihadapi, sikap bawahan saya adalah..
12 -> Komentar
13 -> Ketika menghadapi konsep baru yang rumit, sikap bawahan saya adalah..
14 -> Komentar2
15 -> Ketika ada dalam yang situasi yang rumit dan belum memiliki kejelasan arah, sikap bawahan saya adalah..
16 -> Komentar3
17 -> Dalam mengidentifikasi akar masalah dalam situasi kompleks, sikap bawahan saya adalah....
18 -> Komentar4
19 -> Ketika menjelaskan ide atau masalah yang kompleks kepada orang lain, sikap bawahan saya adalah...
20 -> Komentar5
21 -> Saat menghadapi ide - ide baru yang belum terbukti efektivitasnya, sikap bawahan saya adalah...
22 -> Komentar6
23 -> Dalam menghadapi masalah lama menggunakan cara - cara baru, sikap bawahan saya adalah..
24 -> Komentar7
25 -> Ketika menghadapi ketidakpastian dalam bekerja, sikap bawahan saya adalah..
26 -> Komentar8
27 -> Saat menerima informasi, Sikap bawahan saya adalah...
28 -> Komentar9
29 -> Ketika menghadapi konsep yang tampak tidak saling berkaitan, sikap bawahan saya adalah...
30 -> Komentar10
31 -> Dalam situasi bekerja dengan orang yang memiliki latar belakang berbeda, sikap bawahan saya adalah...
32 -> Komentar11
33 -> Dalam menghadapi konflik kerja, sikap bawahan saya adalah...
34 -> Komentar12
35 -> Dalam hal menerima masukan atau umpan balik dari rekan kerja, sikap bawahan saya adalah...
36 -> Komentar13
37 -> Saat menghadapi situasi konflik antarrekan kerja, sikap bawahan saya adalah...
38 -> Komentar14
39 -> Dalam hal memahami emosi dan perasaan orang lain, sikap bawahan saya adalah...
40 -> Komentar15
41 -> Dalam situasi munculnya perbedaan sudut pandang, sikap bawahan saya adalah...
42 -> Komentar16
43 -> Dalam hal menjaga hubungan baik dengan individu yang sulit, sikap bawahan saya adalah...
44 -> Komentar17
45 -> Dalam hal menghadapi pendapat orang lain yang berbeda dengan saya, sikap bawahan saya adalah...
46 -> Komentar18
47 -> Dalam hal menyelesaikan tugas dan butuh berinteraksi dengan rekan kerja, sikap bawahan saya adalah...
48 -> Komentar19
49 -> Dalam hal  mendengarkan orang lain, sikap bawahan saya adalah...
50 -> Komentar20
51 -> Ketika menghadapi perubahan mendadak, sikap bawahan saya adalah...
52 -> Komentar21
53 -> Dalam hal menilai perubahan yang terjadi, sikap bawahan saya adalah...
54 -> Komentar22
55 -> Dalam hal penerapan sistem atau prosedur baru, sikap bawahan saya adalah...
56 -> Komentar23
57 -> Dalam hal perubahan karena ketidakpastian, sikap bawahan saya adalah...
58 -> Komentar24
59 -> Ketika mencoba cara atau pendekatan baru, sikap bawahan saya adalah...
60 -> Komentar25
61 -> Dalam hal menghadapi situasi yang tidak pasti, sikap bawahan saya adalah...
62 -> Komentar26
63 -> Ketika diterapkan cara kerja baru, sikap bawahan saya adalah...
64 -> Komentar27
65 -> Dalam hal inisiatif ide/cara baru, sikap bawahan saya adalah...
66 -> Komentar28
67 -> Dalam hal rasa ingin tahu dan keinginan belajar, sikap bawahan saya adalah...
68 -> Komentar29
69 -> Dalam hal mengatisipasi perubahan, sikap bawahan saya adalah...
70 -> Komentar30
71 -> Ketika menghadapi tekanan atau hambatan, sikap bawahan saya adalah...
72 -> Komentar31
73 -> Dalam hal pengambilan keputusan dalam situasi yang tidak jelas, sikap bawahan saya adalah...
74 -> Komentar32
75 -> Dalam hal dorongan untuk mencapai hasil terbaik, sikap bawahan saya adalah....
76 -> Komentar33
77 -> Ketika menghadapi tantangan berat, sikap bawahan saya adalah...
78 -> Komentar34
79 -> Setelah mengalami keberhasilan atau kegagalan, sikap bawahan saya adalah...
80 -> Komentar35
81 -> Sikap bawahan saya terhadap tugas kerja adalah...
82 -> Komentar36
83 -> Ketika strategi kerja tidak lagi efektif, sikap bawahan saya adalah...
84 -> Komentar37
85 -> Dalam menilai keberhasilan kerja, sikap bawahan saya adalah...
86 -> Komentar38
87 -> Dalam hal melihat peluang atau masalah, sikap bawahan saya adalah...
88 -> Komentar39
89 -> Ketika menghadapi rintangan tak terduga, sikap bawahan saya adalah...
90 -> Komentar40
91 -> Dalam hal evaluasi kekuatan dan kelemahan diri, sikap bawahan saya adalah...
92 -> Komentar41
93 -> Setelah mengalami suatu pengalaman kerja, sikap bawahan saya adalah...
94 -> Komentar42
95 -> Ketika menerima kritik atau masukan, sikap bawahan saya adalah...
96 -> Komentar43
97 -> Sikap bawahan saya terhadap pengembangan diri adalah...
98 -> Komentar44
99 -> Dalam hal perilaku saya mempengaruhi orang lain, sikap bawahan saya adalah..
100 -> Komentar45
101 -> Sikap bawahan saya terhadap kinerja dirinya adalah..
102 -> Komentar46
103 -> Ketika melakukan kesalahan, sikap bawahan saya adalah...
104 -> Komentar47
105 -> Dalam menilai kemampuan diri, sikap bawahan saya adalah...
106 -> Komentar48
107 -> Dalam hal refleksi diri, sikap bawahan saya adalah...
108 -> Komentar49
109 -> Dalam situasi yang memicu emosi, sikap bawahan saya adalah...

In [11]:
#cell 9

SELF_META_COLS = [
    "ID",
    "Start time",
    "Completion time",
    "Email",
    "Name",
    "Last modified time",
    "Nama",
    "Direktorat",
    "Departemen",
    "Unit"
]

SUPERIOR_META_COLS = [
    "ID",
    "Start time",
    "Completion time",
    "Email",
    "Name",
    "Last modified time",
    "Nama",
    "Nama bawahan yang dinilai",
    "Direktorat",
    "Departemen",
    "Unit"
]

print("Self metadata:")
print(SELF_META_COLS)

print("\nSuperior metadata:")
print(SUPERIOR_META_COLS)

Self metadata:
['ID', 'Start time', 'Completion time', 'Email', 'Name', 'Last modified time', 'Nama', 'Direktorat', 'Departemen', 'Unit']

Superior metadata:
['ID', 'Start time', 'Completion time', 'Email', 'Name', 'Last modified time', 'Nama', 'Nama bawahan yang dinilai', 'Direktorat', 'Departemen', 'Unit']

In [12]:
#cell 10

self_comment_cols = [
    col
    for col in self_df.columns
    if str(col).strip().lower().startswith("komentar")
]

superior_comment_cols = [
    col
    for col in superior_df.columns
    if str(col).strip().lower().startswith("komentar")
]

print("Jumlah komentar Self    :", len(self_comment_cols))
print("Jumlah komentar Superior:", len(superior_comment_cols))

print("\nSelf comment:")
print(self_comment_cols)

print("\nSuperior comment:")
print(superior_comment_cols)

Jumlah komentar Self    : 50
Jumlah komentar Superior: 49

Self comment:
['Komentar', 'Komentar2', 'Komentar3', 'Komentar4', 'Komentar5', 'Komentar6', 'Komentar7', 'Komentar8', 'Komentar9', 'Komentar10', 'Komentar11', 'Komentar12', 'Komentar13', 'Komentar14', 'Komentar15', 'Komentar16', 'Komentar17', 'Komentar18', 'Komentar19', 'Komentar20', 'Komentar21', 'Komentar22', 'Komentar23', 'Komentar24', 'Komentar25', 'Komentar26', 'Komentar27', 'Komentar28', 'Komentar29', 'Komentar30', 'Komentar31', 'Komentar32', 'Komentar33', 'Komentar34', 'Komentar35', 'Komentar36', 'Komentar37', 'Komentar38', 'Komentar39', 'Komentar40', 'Komentar41', 'Komentar42', 'Komentar43', 'Komentar44', 'Komentar45', 'Komentar46', 'Komentar47', 'Komentar48', 'Komentar49', 'Komentar50']

Superior comment:
['Komentar', 'Komentar2', 'Komentar3', 'Komentar4', 'Komentar5', 'Komentar6', 'Komentar7', 'Komentar8', 'Komentar9', 'Komentar10', 'Komentar11', 'Komentar12', 'Komentar13', 'Komentar14', 'Komentar15', 'Komentar16', 'Komentar17', 'Komentar18', 'Komentar19', 'Komentar20', 'Komentar21', 'Komentar22', 'Komentar23', 'Komentar24', 'Komentar25', 'Komentar26', 'Komentar27', 'Komentar28', 'Komentar29', 'Komentar30', 'Komentar31', 'Komentar32', 'Komentar33', 'Komentar34', 'Komentar35', 'Komentar36', 'Komentar37', 'Komentar38', 'Komentar39', 'Komentar40', 'Komentar41', 'Komentar42', 'Komentar43', 'Komentar44', 'Komentar45', 'Komentar46', 'Komentar47', 'Komentar48', 'Komentar49']

In [13]:
#cell 11

self_question_cols = [
    col
    for col in self_df.columns
    if col not in SELF_META_COLS
    and col not in self_comment_cols
]

superior_question_cols = [
    col
    for col in superior_df.columns
    if col not in SUPERIOR_META_COLS
    and col not in superior_comment_cols
]

print("Self questions    :", len(self_question_cols))
print("Superior questions:", len(superior_question_cols))

Self questions    : 50
Superior questions: 50

In [14]:
#cell 12

for i, col in enumerate(self_question_cols, start=1):
    print(f"{i:02d}. {col}")

01. Ketika ada dalam situasi yang mengharuskan pengambilan keputusan atas masalah yang dihadapi, sikap saya adalah..
02. Ketika menghadapi konsep baru yang rumit, sikap saya adalah..
03. Ketika ada dalam yang situasi yang rumit dan belum memiliki kejelasan arah, sikap saya adalah..
04. Dalam mengidentifikasi akar masalah dalam situasi kompleks, sikap saya adalah....
05. Ketika menjelaskan ide atau masalah yang kompleks kepada orang lain, sikap saya adalah...
06. Saat menghadapi ide - ide baru yang belum terbukti efektivitasnya, sikap saya adalah...
07. Dalam menghadapi masalah lama menggunakan cara - cara baru , sikap saya adalah..
08. Ketika menghadapi ketidakpastian dalam bekerja, sikap saya adalah..
09. Saat menerima informasi, Sikap saya adalah...
10. Ketika menghadapi konsep yang tampak tidak saling berkaitan, sikap saya adalah...
11. Dalam situasi bekerja dengan orang yang memiliki latar belakang berbeda, sikap saya adalah...
12. Dalam menghadapi konflik kerja, sikap saya adalah...
13. Dalam hal menerima masukan atau umpan balik dari rekan kerja, sikap saya adalah...
14. Saat menghadapi situasi konflik antarrekan kerja, sikap saya adalah...
15. Dalam hal memahami emosi dan perasaan orang lain , sikap saya adalah...
16. Dalam situasi munculnya perbedaan sudut pandang, sikap saya adalah...
17. Dalam hal menjaga hubungan baik dengan individu yang sulit, sikap saya adalah...
18. Dalam hal menghadapi pendapat orang lain yang berbeda dengan saya, sikap saya adalah...
19. Dalam hal menyelesaikan tugas dan butuh berinteraksi dengan rekan kerja, sikap saya adalah...
20. Dalam hal mendengarkan orang lain, sikap saya adalah...
21. Ketika menghadapi perubahan mendadak, sikap saya adalah...
22. Dalam hal menilai perubahan yang terjadi, sikap saya adalah...
23. Dalam hal penerapan sistem atau prosedur baru, sikap saya adalah...
24. Dalam hal perubahan karena ketidakpastian, sikap saya adalah...
25. Ketika mencoba cara atau pendekatan baru, sikap saya adalah...
26. Dalam hal menghadapi situasi yang tidak pasti, sikap saya adalah...
27. Ketika diterapkan cara kerja baru, sikap saya adalah...
28. Dalam hal inisiatif ide/cara baru, sikap saya adalah...
29. Dalam hal rasa ingin tahu dan keinginan belajar, sikap saya adalah...
30. Dalam hal mengatisipasi perubahan, sikap saya adalah...
31. Ketika menghadapi tekanan atau hambatan, sikap saya adalah...
32. Dalam hal pengambilan keputusan dalam situasi yang tidak jelas, sikap saya adalah...
33. Dalam hal dorongan untuk mencapai hasil terbaik, sikap saya adalah....
34. Ketika menghadapi tantangan berat, sikap saya adalah...
35. Setelah mengalami keberhasilan atau kegagalan, sikap saya adalah...
36. Sikap saya terhadap tugas kerja adalah...
37. Ketika strategi kerja tidak lagi efektif, sikap saya adalah...
38. Dalam menilai keberhasilan kerja, sikap saya adalah...
39. Dalam hal melihat peluang atau masalah, sikap saya adalah...
40. Ketika menghadapi rintangan tak terduga, sikap saya adalah...
41. Dalam hal evaluasi kekuatan dan kelemahan diri, sikap saya adalah...
42. Setelah mengalami suatu pengalaman kerja, sikap saya adalah...
43. Ketika menerima kritik atau masukan, sikap saya adalah...
44. Sikap saya terhadap pengembangan diri adalah...
45. Dalam hal perilaku saya mempengaruhi orang lain, sikap saya adalah..
46. Sikap saya terhadap kinerja diri saya adalah..
47. Ketika melakukan kesalahan, sikap saya adalah...
48. Dalam menilai kemampuan diri, sikap saya adalah...
49. Dalam hal refleksi diri, sikap saya adalah...
50. Dalam situasi yang memicu emosi, sikap saya adalah...

In [15]:
#cell 13

for i, col in enumerate(superior_question_cols, start=1):
    print(f"{i:02d}. {col}")

01. Ketika ada dalam situasi yang mengharuskan pengambilan keputusan atas masalah yang dihadapi, sikap bawahan saya adalah..
02. Ketika menghadapi konsep baru yang rumit, sikap bawahan saya adalah..
03. Ketika ada dalam yang situasi yang rumit dan belum memiliki kejelasan arah, sikap bawahan saya adalah..
04. Dalam mengidentifikasi akar masalah dalam situasi kompleks, sikap bawahan saya adalah....
05. Ketika menjelaskan ide atau masalah yang kompleks kepada orang lain, sikap bawahan saya adalah...
06. Saat menghadapi ide - ide baru yang belum terbukti efektivitasnya, sikap bawahan saya adalah...
07. Dalam menghadapi masalah lama menggunakan cara - cara baru, sikap bawahan saya adalah..
08. Ketika menghadapi ketidakpastian dalam bekerja, sikap bawahan saya adalah..
09. Saat menerima informasi, Sikap bawahan saya adalah...
10. Ketika menghadapi konsep yang tampak tidak saling berkaitan, sikap bawahan saya adalah...
11. Dalam situasi bekerja dengan orang yang memiliki latar belakang berbeda, sikap bawahan saya adalah...
12. Dalam menghadapi konflik kerja, sikap bawahan saya adalah...
13. Dalam hal menerima masukan atau umpan balik dari rekan kerja, sikap bawahan saya adalah...
14. Saat menghadapi situasi konflik antarrekan kerja, sikap bawahan saya adalah...
15. Dalam hal memahami emosi dan perasaan orang lain, sikap bawahan saya adalah...
16. Dalam situasi munculnya perbedaan sudut pandang, sikap bawahan saya adalah...
17. Dalam hal menjaga hubungan baik dengan individu yang sulit, sikap bawahan saya adalah...
18. Dalam hal menghadapi pendapat orang lain yang berbeda dengan saya, sikap bawahan saya adalah...
19. Dalam hal menyelesaikan tugas dan butuh berinteraksi dengan rekan kerja, sikap bawahan saya adalah...
20. Dalam hal  mendengarkan orang lain, sikap bawahan saya adalah...
21. Ketika menghadapi perubahan mendadak, sikap bawahan saya adalah...
22. Dalam hal menilai perubahan yang terjadi, sikap bawahan saya adalah...
23. Dalam hal penerapan sistem atau prosedur baru, sikap bawahan saya adalah...
24. Dalam hal perubahan karena ketidakpastian, sikap bawahan saya adalah...
25. Ketika mencoba cara atau pendekatan baru, sikap bawahan saya adalah...
26. Dalam hal menghadapi situasi yang tidak pasti, sikap bawahan saya adalah...
27. Ketika diterapkan cara kerja baru, sikap bawahan saya adalah...
28. Dalam hal inisiatif ide/cara baru, sikap bawahan saya adalah...
29. Dalam hal rasa ingin tahu dan keinginan belajar, sikap bawahan saya adalah...
30. Dalam hal mengatisipasi perubahan, sikap bawahan saya adalah...
31. Ketika menghadapi tekanan atau hambatan, sikap bawahan saya adalah...
32. Dalam hal pengambilan keputusan dalam situasi yang tidak jelas, sikap bawahan saya adalah...
33. Dalam hal dorongan untuk mencapai hasil terbaik, sikap bawahan saya adalah....
34. Ketika menghadapi tantangan berat, sikap bawahan saya adalah...
35. Setelah mengalami keberhasilan atau kegagalan, sikap bawahan saya adalah...
36. Sikap bawahan saya terhadap tugas kerja adalah...
37. Ketika strategi kerja tidak lagi efektif, sikap bawahan saya adalah...
38. Dalam menilai keberhasilan kerja, sikap bawahan saya adalah...
39. Dalam hal melihat peluang atau masalah, sikap bawahan saya adalah...
40. Ketika menghadapi rintangan tak terduga, sikap bawahan saya adalah...
41. Dalam hal evaluasi kekuatan dan kelemahan diri, sikap bawahan saya adalah...
42. Setelah mengalami suatu pengalaman kerja, sikap bawahan saya adalah...
43. Ketika menerima kritik atau masukan, sikap bawahan saya adalah...
44. Sikap bawahan saya terhadap pengembangan diri adalah...
45. Dalam hal perilaku saya mempengaruhi orang lain, sikap bawahan saya adalah..
46. Sikap bawahan saya terhadap kinerja dirinya adalah..
47. Ketika melakukan kesalahan, sikap bawahan saya adalah...
48. Dalam menilai kemampuan diri, sikap bawahan saya adalah...
49. Dalam hal refleksi diri, sikap bawahan saya adalah...
50. Dalam situasi yang memicu emosi, sikap bawahan saya adalah...

In [16]:
#cell 14

def normalize_text(value):
    if pd.isna(value):
        return ""
    
    text = str(value)
    
    text = text.replace("\xa0", " ")
    
    text = text.strip().lower()
    
    text = re.sub(
        r"\s+",
        " ",
        text
    )
    
    return text

In [17]:
#cell 15

def normalize_question(value):
    text = normalize_text(value)
    
    text = text.replace(
        "bawahan saya",
        "saya"
    )
    
    text = text.replace(
        "bawahan",
        "saya"
    )
    
    return text

In [18]:
#cell 16

question_comparison = []

for i, (self_col, superior_col) in enumerate(
    zip(self_question_cols, superior_question_cols),
    start=1
):
    
    self_normalized = normalize_question(self_col)
    superior_normalized = normalize_question(superior_col)
    
    question_comparison.append({
        "question_no": i,
        "self_question": self_col,
        "superior_question": superior_col,
        "self_normalized": self_normalized,
        "superior_normalized": superior_normalized,
        "match": self_normalized == superior_normalized
    })

question_comparison_df = pd.DataFrame(
    question_comparison
)

question_comparison_df

,question_no,self_question,superior_question,self_normalized,superior_normalized,match
0,1,"Ketika ada dalam situasi yang mengharuskan pengambilan keputusan atas masalah yang dihadapi, sik...","Ketika ada dalam situasi yang mengharuskan pengambilan keputusan atas masalah yang dihadapi, sik...","ketika ada dalam situasi yang mengharuskan pengambilan keputusan atas masalah yang dihadapi, sik...","ketika ada dalam situasi yang mengharuskan pengambilan keputusan atas masalah yang dihadapi, sik...",True
1,2,"Ketika menghadapi konsep baru yang rumit, sikap saya adalah..","Ketika menghadapi konsep baru yang rumit, sikap bawahan saya adalah..","ketika menghadapi konsep baru yang rumit, sikap saya adalah..","ketika menghadapi konsep baru yang rumit, sikap saya adalah..",True
2,3,"Ketika ada dalam yang situasi yang rumit dan belum memiliki kejelasan arah, sikap saya adalah..","Ketika ada dalam yang situasi yang rumit dan belum memiliki kejelasan arah, sikap bawahan saya a...","ketika ada dalam yang situasi yang rumit dan belum memiliki kejelasan arah, sikap saya adalah..","ketika ada dalam yang situasi yang rumit dan belum memiliki kejelasan arah, sikap saya adalah..",True
3,4,"Dalam mengidentifikasi akar masalah dalam situasi kompleks, sikap saya adalah....","Dalam mengidentifikasi akar masalah dalam situasi kompleks, sikap bawahan saya adalah....","dalam mengidentifikasi akar masalah dalam situasi kompleks, sikap saya adalah....","dalam mengidentifikasi akar masalah dalam situasi kompleks, sikap saya adalah....",True
4,5,"Ketika menjelaskan ide atau masalah yang kompleks kepada orang lain, sikap saya adalah...","Ketika menjelaskan ide atau masalah yang kompleks kepada orang lain, sikap bawahan saya adalah...","ketika menjelaskan ide atau masalah yang kompleks kepada orang lain, sikap saya adalah...","ketika menjelaskan ide atau masalah yang kompleks kepada orang lain, sikap saya adalah...",True
5,6,"Saat menghadapi ide - ide baru yang belum terbukti efektivitasnya, sikap saya adalah...","Saat menghadapi ide - ide baru yang belum terbukti efektivitasnya, sikap bawahan saya adalah...","saat menghadapi ide - ide baru yang belum terbukti efektivitasnya, sikap saya adalah...","saat menghadapi ide - ide baru yang belum terbukti efektivitasnya, sikap saya adalah...",True
6,7,"Dalam menghadapi masalah lama menggunakan cara - cara baru , sikap saya adalah..","Dalam menghadapi masalah lama menggunakan cara - cara baru, sikap bawahan saya adalah..","dalam menghadapi masalah lama menggunakan cara - cara baru , sikap saya adalah..","dalam menghadapi masalah lama menggunakan cara - cara baru, sikap saya adalah..",False
7,8,"Ketika menghadapi ketidakpastian dalam bekerja, sikap saya adalah..","Ketika menghadapi ketidakpastian dalam bekerja, sikap bawahan saya adalah..","ketika menghadapi ketidakpastian dalam bekerja, sikap saya adalah..","ketika menghadapi ketidakpastian dalam bekerja, sikap saya adalah..",True
8,9,"Saat menerima informasi, Sikap saya adalah...","Saat menerima informasi, Sikap bawahan saya adalah...","saat menerima informasi, sikap saya adalah...","saat menerima informasi, sikap saya adalah...",True
9,10,"Ketika menghadapi konsep yang tampak tidak saling berkaitan, sikap saya adalah...","Ketika menghadapi konsep yang tampak tidak saling berkaitan, sikap bawahan saya adalah...","ketika menghadapi konsep yang tampak tidak saling berkaitan, sikap saya adalah...","ketika menghadapi konsep yang tampak tidak saling berkaitan, sikap saya adalah...",True
10,11,"Dalam situasi bekerja dengan orang yang memiliki latar belakang berbeda, sikap saya adalah...","Dalam situasi bekerja dengan orang yang memiliki latar belakang berbeda, sikap bawahan saya adal...","dalam situasi bekerja dengan orang yang memiliki latar belakang berbeda, sikap saya adalah...","dalam situasi bekerja dengan orang yang memiliki latar belakang berbeda, sikap saya adalah...",True
11,12,"Dalam menghadapi konflik kerja, sikap saya adalah...","Dalam menghadapi konflik kerja, sikap bawahan saya adalah...","dalam menghadapi konflik kerja, sikap saya adalah...","dalam menghadapi konflik kerja, sikap saya adalah...",True
12,13,"Dalam hal menerima masukan atau umpan balik dari rekan kerja, sikap saya adalah...","Dalam hal menerima masukan atau umpan balik dari rekan kerja, sikap bawahan saya adalah...","dalam hal menerima masukan atau umpan balik dari rekan kerja, sikap saya adalah...","dalam hal menerima masukan atau umpan balik dari rekan kerja, sikap saya adalah...",True
13,14,"Saat menghadapi situasi konflik antarrekan kerja, sikap saya adalah...","Saat menghadapi situasi konflik antarrekan kerja, sikap bawahan saya adalah...","saat menghadapi situasi konflik antarrekan kerja, sikap saya adalah...","saat menghadapi situasi konflik antarrekan kerja, sikap saya adalah...",True
14,15,"Dalam hal memahami emosi dan perasaan orang lain , sikap saya adalah...","Dalam hal memahami emosi dan perasaan orang lain, sikap bawahan saya adalah...","dalam hal memahami emosi dan perasaan orang lain , sikap saya adalah...","dalam hal memahami emosi dan perasaan orang lain, sikap saya adalah...",False
15,16,"Dalam situasi munculnya perbedaan sudut pandang, sikap saya adalah...","Dalam situasi munculnya perbedaan sudut pandang, sikap bawahan saya adalah...","dalam situasi munculnya perbedaan sudut pandang, sikap saya adalah...","dalam situasi munculnya perbedaan sudut pandang, sikap saya adalah...",True
16,17,"Dalam hal menjaga hubungan baik dengan individu yang sulit, sikap saya adalah...","Dalam hal menjaga hubungan baik dengan individu yang sulit, sikap bawahan saya adalah...","dalam hal menjaga hubungan baik dengan individu yang sulit, sikap saya adalah...","dalam hal menjaga hubungan baik dengan individu yang sulit, sikap saya adalah...",True
17,18,"Dalam hal menghadapi pendapat orang lain yang berbeda dengan saya, sikap saya adalah...","Dalam hal menghadapi pendapat orang lain yang berbeda dengan saya, sikap bawahan saya adalah...","dalam hal menghadapi pendapat orang lain yang berbeda dengan saya, sikap saya adalah...","dalam hal menghadapi pendapat orang lain yang berbeda dengan saya, sikap saya adalah...",True
18,19,"Dalam hal menyelesaikan tugas dan butuh berinteraksi dengan rekan kerja, sikap saya adalah...","Dalam hal menyelesaikan tugas dan butuh berinteraksi dengan rekan kerja, sikap bawahan saya adal...","dalam hal menyelesaikan tugas dan butuh berinteraksi dengan rekan kerja, sikap saya adalah...","dalam hal menyelesaikan tugas dan butuh berinteraksi dengan rekan kerja, sikap saya adalah...",True
19,20,"Dalam hal mendengarkan orang lain, sikap saya adalah...","Dalam hal mendengarkan orang lain, sikap bawahan saya adalah...","dalam hal mendengarkan orang lain, sikap saya adalah...","dalam hal mendengarkan orang lain, sikap saya adalah...",True
20,21,"Ketika menghadapi perubahan mendadak, sikap saya adalah...","Ketika menghadapi perubahan mendadak, sikap bawahan saya adalah...","ketika menghadapi perubahan mendadak, sikap saya adalah...","ketika menghadapi perubahan mendadak, sikap saya adalah...",True
21,22,"Dalam hal menilai perubahan yang terjadi, sikap saya adalah...","Dalam hal menilai perubahan yang terjadi, sikap bawahan saya adalah...","dalam hal menilai perubahan yang terjadi, sikap saya adalah...","dalam hal menilai perubahan yang terjadi, sikap saya adalah...",True
22,23,"Dalam hal penerapan sistem atau prosedur baru, sikap saya adalah...","Dalam hal penerapan sistem atau prosedur baru, sikap bawahan saya adalah...","dalam hal penerapan sistem atau prosedur baru, sikap saya adalah...","dalam hal penerapan sistem atau prosedur baru, sikap saya adalah...",True
23,24,"Dalam hal perubahan karena ketidakpastian, sikap saya adalah...","Dalam hal perubahan karena ketidakpastian, sikap bawahan saya adalah...","dalam hal perubahan karena ketidakpastian, sikap saya adalah...","dalam hal perubahan karena ketidakpastian, sikap saya adalah...",True
24,25,"Ketika mencoba cara atau pendekatan baru, sikap saya adalah...","Ketika mencoba cara atau pendekatan baru, sikap bawahan saya adalah...","ketika mencoba cara atau pendekatan baru, sikap saya adalah...","ketika mencoba cara atau pendekatan baru, sikap saya adalah...",True
25,26,"Dalam hal menghadapi situasi yang tidak pasti, sikap saya adalah...","Dalam hal menghadapi situasi yang tidak pasti, sikap bawahan saya adalah...","dalam hal menghadapi situasi yang tidak pasti, sikap saya adalah...","dalam hal menghadapi situasi yang tidak pasti, sikap saya adalah...",True
26,27,"Ketika diterapkan cara kerja baru, sikap saya adalah...","Ketika diterapkan cara kerja baru, sikap bawahan saya adalah...","ketika diterapkan cara kerja baru, sikap saya adalah...","ketika diterapkan cara kerja baru, sikap saya adalah...",True
27,28,"Dalam hal inisiatif ide/cara baru, sikap saya adalah...","Dalam hal inisiatif ide/cara baru, sikap bawahan saya adalah...","dalam hal inisiatif ide/cara baru, sikap saya adalah...","dalam hal inisiatif ide/cara baru, sikap saya adalah...",True
28,29,"Dalam hal rasa ingin tahu dan keinginan belajar, sikap saya adalah...","Dalam hal rasa ingin tahu dan keinginan belajar, sikap bawahan saya adalah...","dalam hal rasa ingin tahu dan keinginan belajar, sikap saya adalah...","dalam hal rasa ingin tahu dan keinginan belajar, sikap saya adalah...",True
29,30,"Dalam hal mengatisipasi perubahan, sikap saya adalah...","Dalam hal mengatisipasi perubahan, sikap bawahan saya adalah...","dalam hal mengatisipasi perubahan, sikap saya adalah...","dalam hal mengatisipasi perubahan, sikap saya adalah...",True
30,31,"Ketika menghadapi tekanan atau hambatan, sikap saya adalah...","Ketika menghadapi tekanan atau hambatan, sikap bawahan saya adalah...","ketika menghadapi tekanan atau hambatan, sikap saya adalah...","ketika menghadapi tekanan atau hambatan, sikap saya adalah...",True
31,32,"Dalam hal pengambilan keputusan dalam situasi yang tidak jelas, sikap saya adalah...","Dalam hal pengambilan keputusan dalam situasi yang tidak jelas, sikap bawahan saya adalah...","dalam hal pengambilan keputusan dalam situasi yang tidak jelas, sikap saya adalah...","dalam hal pengambilan keputusan dalam situasi yang tidak jelas, sikap saya adalah...",True
32,33,"Dalam hal dorongan untuk mencapai hasil terbaik, sikap saya adalah....","Dalam hal dorongan untuk mencapai hasil terbaik, sikap bawahan saya adalah....","dalam hal dorongan untuk mencapai hasil terbaik, sikap saya adalah....","dalam hal dorongan untuk mencapai hasil terbaik, sikap saya adalah....",True
33,34,"Ketika menghadapi tantangan berat, sikap saya adalah...","Ketika menghadapi tantangan berat, sikap bawahan saya adalah...","ketika menghadapi tantangan berat, sikap saya adalah...","ketika menghadapi tantangan berat, sikap saya adalah...",True
34,35,"Setelah mengalami keberhasilan atau kegagalan, sikap saya adalah...","Setelah mengalami keberhasilan atau kegagalan, sikap bawahan saya adalah...","setelah mengalami keberhasilan atau kegagalan, sikap saya adalah...","setelah mengalami keberhasilan atau kegagalan, sikap saya adalah...",True
35,36,Sikap saya terhadap tugas kerja adalah...,Sikap bawahan saya terhadap tugas kerja adalah...,sikap saya terhadap tugas kerja adalah...,sikap saya terhadap tugas kerja adalah...,True
36,37,"Ketika strategi kerja tidak lagi efektif, sikap saya adalah...","Ketika strategi kerja tidak lagi efektif, sikap bawahan saya adalah...","ketika strategi kerja tidak lagi efektif, sikap saya adalah...","ketika strategi kerja tidak lagi efektif, sikap saya adalah...",True
37,38,"Dalam menilai keberhasilan kerja, sikap saya adalah...","Dalam menilai keberhasilan kerja, sikap bawahan saya adalah...","dalam menilai keberhasilan kerja, sikap saya adalah...","dalam menilai keberhasilan kerja, sikap saya adalah...",True
38,39,"Dalam hal melihat peluang atau masalah, sikap saya adalah...","Dalam hal melihat peluang atau masalah, sikap bawahan saya adalah...","dalam hal melihat peluang atau masalah, sikap saya adalah...","dalam hal melihat peluang atau masalah, sikap saya adalah...",True
39,40,"Ketika menghadapi rintangan tak terduga, sikap saya adalah...","Ketika menghadapi rintangan tak terduga, sikap bawahan saya adalah...","ketika menghadapi rintangan tak terduga, sikap saya adalah...","ketika menghadapi rintangan tak terduga, sikap saya adalah...",True
40,41,"Dalam hal evaluasi kekuatan dan kelemahan diri, sikap saya adalah...","Dalam hal evaluasi kekuatan dan kelemahan diri, sikap bawahan saya adalah...","dalam hal evaluasi kekuatan dan kelemahan diri, sikap saya adalah...","dalam hal evaluasi kekuatan dan kelemahan diri, sikap saya adalah...",True
41,42,"Setelah mengalami suatu pengalaman kerja, sikap saya adalah...","Setelah mengalami suatu pengalaman kerja, sikap bawahan saya adalah...","setelah mengalami suatu pengalaman kerja, sikap saya adalah...","setelah mengalami suatu pengalaman kerja, sikap saya adalah...",True
42,43,"Ketika menerima kritik atau masukan, sikap saya adalah...","Ketika menerima kritik atau masukan, sikap bawahan saya adalah...","ketika menerima kritik atau masukan, sikap saya adalah...","ketika menerima kritik atau masukan, sikap saya adalah...",True
43,44,Sikap saya terhadap pengembangan diri adalah...,Sikap bawahan saya terhadap pengembangan diri adalah...,sikap saya terhadap pengembangan diri adalah...,sikap saya terhadap pengembangan diri adalah...,True
44,45,"Dalam hal perilaku saya mempengaruhi orang lain, sikap saya adalah..","Dalam hal perilaku saya mempengaruhi orang lain, sikap bawahan saya adalah..","dalam hal perilaku saya mempengaruhi orang lain, sikap saya adalah..","dalam hal perilaku saya mempengaruhi orang lain, sikap saya adalah..",True
45,46,Sikap saya terhadap kinerja diri saya adalah..,Sikap bawahan saya terhadap kinerja dirinya adalah..,sikap saya terhadap kinerja diri saya adalah..,sikap saya terhadap kinerja dirinya adalah..,False
46,47,"Ketika melakukan kesalahan, sikap saya adalah...","Ketika melakukan kesalahan, sikap bawahan saya adalah...","ketika melakukan kesalahan, sikap saya adalah...","ketika melakukan kesalahan, sikap saya adalah...",True
47,48,"Dalam menilai kemampuan diri, sikap saya adalah...","Dalam menilai kemampuan diri, sikap bawahan saya adalah...","dalam menilai kemampuan diri, sikap saya adalah...","dalam menilai kemampuan diri, sikap saya adalah...",True
48,49,"Dalam hal refleksi diri, sikap saya adalah...","Dalam hal refleksi diri, sikap bawahan saya adalah...","dalam hal refleksi diri, sikap saya adalah...","dalam hal refleksi diri, sikap saya adalah...",True
49,50,"Dalam situasi yang memicu emosi, sikap saya adalah...","Dalam situasi yang memicu emosi, sikap bawahan saya adalah...","dalam situasi yang memicu emosi, sikap saya adalah...","dalam situasi yang memicu emosi, sikap saya adalah...",True

In [19]:
#cell 17

question_comparison_df["match"].value_counts()

match
True     47
False     3
Name: count, dtype: int64

In [20]:
question_comparison_df[
    question_comparison_df["match"] == False
]

,question_no,self_question,superior_question,self_normalized,superior_normalized,match
6,7,"Dalam menghadapi masalah lama menggunakan cara - cara baru , sikap saya adalah..","Dalam menghadapi masalah lama menggunakan cara - cara baru, sikap bawahan saya adalah..","dalam menghadapi masalah lama menggunakan cara - cara baru , sikap saya adalah..","dalam menghadapi masalah lama menggunakan cara - cara baru, sikap saya adalah..",False
14,15,"Dalam hal memahami emosi dan perasaan orang lain , sikap saya adalah...","Dalam hal memahami emosi dan perasaan orang lain, sikap bawahan saya adalah...","dalam hal memahami emosi dan perasaan orang lain , sikap saya adalah...","dalam hal memahami emosi dan perasaan orang lain, sikap saya adalah...",False
45,46,Sikap saya terhadap kinerja diri saya adalah..,Sikap bawahan saya terhadap kinerja dirinya adalah..,sikap saya terhadap kinerja diri saya adalah..,sikap saya terhadap kinerja dirinya adalah..,False

In [21]:
#cell 18

wb = openpyxl.load_workbook(
    MASTER_FILE,
    data_only=False
)

print(wb.sheetnames)

c:\Users\zerox\OneDrive\Documents\Desktop\learning\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

['Identitas', 'mental agility', 'people agility', 'change agility', 'result agility', 'self awareness', 'Profile Summary', 'Kompetensi', 'sheet template', 'Dasboard', 'Aktivitas pengembangan', 'Bukti Aktivitas Pengembangan', 'Penilaian Perilaku', 'Form Penilaian Presentasi', 'panduan']

In [22]:
#cell 19

DIMENSION_SHEETS = [
    ("mental agility", "Mental Agility"),
    ("people agility", "People Agility"),
    ("change agility", "Change Agility"),
    ("result agility", "Result Agility"),
    ("self awareness", "Self Awareness")
]

DIMENSION_SHEETS

[('mental agility', 'Mental Agility'),
 ('people agility', 'People Agility'),
 ('change agility', 'Change Agility'),
 ('result agility', 'Result Agility'),
 ('self awareness', 'Self Awareness')]

In [23]:
# ============================================================
# CELL 20 — EXTRACT INDICATOR MASTER
# ============================================================

indicator_rows = []

for sheet_name, dimension_name in DIMENSION_SHEETS:

    ws = wb[sheet_name]

    print("\n" + "=" * 60)
    print("SHEET:", sheet_name)
    print("=" * 60)

    # 10 indikator selalu berada di row 13–22
    for indicator_idx, row_num in enumerate(range(13, 23), start=1):

        indicator_excel_no = ws.cell(row_num, 1).value
        indicator = ws.cell(row_num, 2).value
        situation_statement = ws.cell(row_num, 3).value

        # Gunakan nomor berdasarkan urutan baris.
        # Ini mengatasi kasus nomor di kolom A kosong.
        indicator_no = indicator_idx

        print(
            f"Row {row_num}: "
            f"No Excel={indicator_excel_no!r} | "
            f"No System={indicator_no} | "
            f"Indicator={indicator!r}"
        )

        indicator_rows.append({
            "dimension": dimension_name,
            "dimension_key": sheet_name.replace(" ", "_"),
            "indicator_no": indicator_no,
            "indicator": indicator,
            "situation_statement": situation_statement,
            "level_1": ws.cell(row_num, 4).value,
            "level_2": ws.cell(row_num, 5).value,
            "level_3": ws.cell(row_num, 6).value,
            "level_4": ws.cell(row_num, 7).value,
            "level_5": ws.cell(row_num, 8).value
        })

indicator_master = pd.DataFrame(indicator_rows)

print("\nJumlah total indikator:", len(indicator_master))

display(indicator_master)

============================================================
SHEET: mental agility
============================================================
Row 13: No Excel=1 | No System=1 | Indicator='Analytical Thinking\n(memahami data & fakta dasar)'
Row 14: No Excel='=A13+1' | No System=2 | Indicator='Root Cause Analysis\n(mencari penyebab masalah)'
Row 15: No Excel='=A14+1' | No System=3 | Indicator='Critical Thinking & Inquisitiveness\n(mempertanyakan & mengevaluasi)'
Row 16: No Excel='=A15+1' | No System=4 | Indicator='Explaining Complexity\n(menjelaskan hal kompleks secara sederhana)'
Row 17: No Excel='=A16+1' | No System=5 | Indicator='Intellectual Synthesis\n(menghubungkan berbagai informasi)'
Row 18: No Excel='=A17+1' | No System=6 | Indicator='Integrating Diverse Perspective\n(pengambilan keputusan melihat dari berbagai sudut pandang)'
Row 19: No Excel='=A18+1' | No System=7 | Indicator='Creative Exploration\n(mencari pendekatan baru)'
Row 20: No Excel='=A19+1' | No System=8 | Indicator='Breaking Patterned thinking\n(menciptakan solusi baru)'
Row 21: No Excel='=A20+1' | No System=9 | Indicator='Comfort with Ambiguity\n(tetap efektif di situasi tidak jelas)'
Row 22: No Excel='=A21+1' | No System=10 | Indicator='Tolerance for Ambiguity\xa0\n(mampu memimpin dalam uncertainty tinggi)'

============================================================
SHEET: people agility
============================================================
Row 13: No Excel=1 | No System=1 | Indicator=' Listening for understanding\n(mendengarkan & memahami dasar)'
Row 14: No Excel=2 | No System=2 | Indicator='Openness to Feedback\n(menerima & mencari masukan)'
Row 15: No Excel=3 | No System=3 | Indicator='Genuine Curiosity about Others\n(rasa ingin tahu tulus pada orang lain)'
Row 16: No Excel=4 | No System=4 | Indicator='Collaboration with Diversity\n(Bekerja efektif dalam keberagaman)'
Row 17: No Excel=5 | No System=5 | Indicator='Valuing Diverse Opinions\n(Menghargai opini berbeda dalam pengambilan keputusan)'
Row 18: No Excel=6 | No System=6 | Indicator='Understanding Different Perspectives\n(Analisis multi-sudut pandang untuk pemahaman mendalam)'
Row 19: No Excel=7 | No System=7 | Indicator='Empathy\n(Merasakan & memahami emosi orang lain)'
Row 20: No Excel=8 | No System=8 | Indicator='Conflict Navigation\n(menghadapi konflik secara konstruktif)'
Row 21: No Excel=9 | No System=9 | Indicator='Managing Challenging  Stakeholder\n(Mengelola relasi berkelanjutan dengan stakeholder sulit)'
Row 22: No Excel=10 | No System=10 | Indicator='Conflict Mediation\n(menjadi penengah & penyatu pihak berbeda)'

============================================================
SHEET: change agility
============================================================
Row 13: No Excel=1 | No System=1 | Indicator='Adapting to New Systems\n(mengikuti perubahan dasar)'
Row 14: No Excel=2 | No System=2 | Indicator='Comfort with New Ways of Working\n(mulai nyaman dengan cara kerja baru)'
Row 15: No Excel=3 | No System=3 | Indicator='Comfort with Sudden Change\n(tetap bekerja saat perubahan mendadak)'
Row 16: No Excel=4 | No System=4 | Indicator='Managing Resistance to Change\n(pengelolaan resistensi)'
Row 17: No Excel=5 | No System=5 | Indicator='Adaptive Learning & Experimentation\n(aktif belajar hal baru)'
Row 18: No Excel=6 | No System=6 | Indicator='Viewing Change as Opportunity\n(melihat perubahan sebagai peluang)'
Row 19: No Excel=7 | No System=7 | Indicator='Proposing New Ideas\n(mulai menginisiasi perubahan)'
Row 20: No Excel=8 | No System=8 | Indicator='Risk-Taking for Innovation\n(berani mencoba pendekatan baru)'
Row 21: No Excel=9 | No System=9 | Indicator='Calmness in Uncertainty\n(tetap tenang di kondisi tidak pasti)'
Row 22: No Excel=10 | No System=10 | Indicator='Proactive in Anticipating Change\n(mengantisipasi perubahan sebelum terjadi)'

============================================================
SHEET: result agility
============================================================
Row 13: No Excel=1 | No System=1 | Indicator='Task Completion Quality \n(menyelesaikan tugas dengan baik)'
Row 14: No Excel=2 | No System=2 | Indicator='Action-Oriented & Takes Initiative \n(proaktif bertindak)'
Row 15: No Excel=3 | No System=3 | Indicator='Driving for impact\n(fokus pada hasil kerja)'
Row 16: No Excel=4 | No System=4 | Indicator='Tenacity & Strategic Persistence\n(menjaga komitmen di tengah tantangan)'
Row 17: No Excel=5 | No System=5 | Indicator='Learning from Outcomes\n(belajar dari hasil & kesalahan tim)'
Row 18: No Excel=6 | No System=6 | Indicator='Deciding with Incomplete Data\n(mengambil keputusan dengan data/informasi terbatas)'
Row 19: No Excel=7 | No System=7 | Indicator='Focus Under Pressure\n(tetap fokus dalam tekanan tinggi)'
Row 20: No Excel=8 | No System=8 | Indicator='Adapting Strategy When Needed\n(mengubah strategi untuk hasil lebih baik)'
Row 21: No Excel=9 | No System=9 | Indicator='Agile Problem-Solving Under Pressure\n(rencana di tengah ketidakpastian)'
Row 22: No Excel=10 | No System=10 | Indicator='Drive for High Performance\n(sistem perencanaan berkinerja tinggi)'

============================================================
SHEET: self awareness
============================================================
Row 13: No Excel=1 | No System=1 | Indicator='Openness to Criticism\n(menerima kritik dasar)'
Row 14: No Excel=2 | No System=2 | Indicator='Admitting Mistakes\n(mengakui kesalahan)'
Row 15: No Excel=3 | No System=3 | Indicator='Seeking Feedback on Performance\n(mencari feedback)'
Row 16: No Excel=4 | No System=4 | Indicator='Understanding Strengths & Weaknesses\n(memahami kekuatan & kelemahan)'
Row 17: No Excel=5 | No System=5 | Indicator='Reflective Practices\n(melakukan refleksi diri)'
Row 18: No Excel=6 | No System=6 | Indicator='Proactive Self-Development for Adaptation\n(aktif mengembangkan diri)'
Row 19: No Excel=7 | No System=7 | Indicator='Objective Self-Assessment\n(menilai diri secara objektif)'
Row 20: No Excel=8 | No System=8 | Indicator='Awareness of Impact on Others\n(memahami dampak perilaku terhadap orang lain)'
Row 21: No Excel=9 | No System=9 | Indicator='Managing Emotions Effectively\n(mengelola emosi secara matang)'
Row 22: No Excel=10 | No System=10 | Indicator='Deep Pattern Recognition & Bias Awareness\n(refleksi diri mendalam & autentik)'

Jumlah total indikator: 50

,dimension,dimension_key,indicator_no,indicator,situation_statement,level_1,level_2,level_3,level_4,level_5
0,Mental Agility,mental_agility,1,Analytical Thinking\n(memahami data & fakta dasar),"Ketika menghadapi data, fakta, atau informasi baru dalam pekerjaan, perilaku yang paling sering ...",Kesulitan memahami informasi baru tanpa arahan detail.,"Memahami informasi dasar, tetapi masih membutuhkan bantuan untuk menarik kesimpulan.",Mampu memahami data/fakta utama dan menarik kesimpulan yang relevan.,Cepat memahami informasi kompleks dan menghubungkannya dengan konteks pekerjaan.,"Menangkap pola kompleks dan mengubahnya menjadi insight, rekomendasi, atau solusi baru."
1,Mental Agility,mental_agility,2,Root Cause Analysis\n(mencari penyebab masalah),"Ketika menghadapi masalah dalam pekerjaan, perilaku yang paling sering ditunjukkan adalah…",Cenderung melihat gejala permukaan dan belum mampu memilah informasi penting.,Mampu menemukan penyebab masalah sederhana dengan arahan.,Mampu menganalisis informasi dan menemukan akar masalah utama.,"Mampu mengurai masalah kompleks serta membedakan gejala, penyebab, dan dampak.","Cepat dan akurat menemukan akar masalah dalam situasi kompleks, ambigu, atau lintas fungsi."
2,Mental Agility,mental_agility,3,Critical Thinking & Inquisitiveness\n(mempertanyakan & mengevaluasi),"Ketika menerima informasi, arahan, data, atau usulan, perilaku yang paling sering ditunjukkan ad...",Menerima informasi apa adanya tanpa klarifikasi.,Mulai mengajukan pertanyaan dasar untuk memahami fakta.,Rutin bertanya “mengapa” dan “bagaimana” untuk memahami alasan atau akar masalah.,"Menguji asumsi, membandingkan data, dan mencari perspektif pembanding.","Membangun kerangka berpikir yang menghubungkan informasi kompleks, kontradiktif, atau belum leng..."
3,Mental Agility,mental_agility,4,Explaining Complexity\n(menjelaskan hal kompleks secara sederhana),"Ketika harus menjelaskan ide, data, atau masalah kompleks kepada orang lain, perilaku yang palin...",Penjelasan kurang terstruktur sehingga orang lain sulit memahami inti masalah.,"Mampu menjelaskan dengan contoh, tetapi masih bertele-tele atau kurang fokus.","Menjelaskan isu kompleks dengan cukup jelas, runtut, dan mudah diikuti.",Menyederhanakan konsep kompleks menjadi pesan yang mudah dipahami audiens berbeda.,"Mengemas kompleksitas menjadi narasi sederhana, meyakinkan, dan mendorong tindakan."
4,Mental Agility,mental_agility,5,Intellectual Synthesis\n(menghubungkan berbagai informasi),Ketika dihadapkan pada beragam informasi atau konsep yang tampak terfragmentasi dan belum terint...,Menggunakan pengetahuan yang sudah dikenal dan memilih solusi konvensional.,"Mulai melihat kemiripan antar informasi, tetapi belum mampu menghubungkannya menjadi solusi.","Menemukan hubungan antar informasi, data, atau konsep dari sumber berbeda.","Menyintesis berbagai informasi menjadi pendekatan, rekomendasi, atau solusi baru.",Membangun kerangka kerja baru dari berbagai informasi kompleks yang sebelumnya tampak tidak berk...
5,Mental Agility,mental_agility,6,Integrating Diverse Perspective\n(pengambilan keputusan melihat dari berbagai sudut pandang),Ketika harus mengambil keputusan yang melibatkan beragam perspektif dari para pemangku kepenting...,Cenderung mencari informasi yang mendukung pendapat awal.,"Mulai mempertimbangkan perspektif lain, tetapi masih dominan pada sudut pandang sendiri.",Mempertimbangkan berbagai faktor dan sudut pandang sebelum membuat keputusan.,Secara aktif memadukan masukan berbagai pihak untuk memperkaya analisis dan mengurangi risiko.,Menghubungkan perspektif yang berbeda atau bertentangan untuk menghasilkan solusi inovatif dan d...
6,Mental Agility,mental_agility,7,Creative Exploration\n(mencari pendekatan baru),"Ketika menghadapi ide baru atau pendekatan yang belum terbukti, perilaku yang paling sering ditu...",Hanya menggunakan metode yang familiar dan menghindari pendekatan baru.,"Mau mendengarkan ide baru, tetapi lebih nyaman dengan cara yang sudah terbukti.","Terbuka mencoba ide baru jika situasi, waktu, dan sumber daya mendukung.","Aktif mencari ide baru sebagai peluang perbaikan, efisiensi, atau inovasi.","Proaktif mengeksplorasi ide kreatif, menguji pendekatan baru, dan mendorong pembelajaran dari ek..."
7,Mental Agility,mental_agility,8,Breaking Patterned thinking\n(menciptakan solusi baru),"Ketika menghadapi masalah lama yang membutuhkan cara baru, perilaku yang paling sering ditunjukk...",Mengulang solusi lama tanpa mengevaluasi kesesuaiannya.,"Menyesuaikan solusi lama, tetapi masih menggunakan pola pikir yang sama.",Mengevaluasi efektivitas solusi lama dan mulai mencari alternatif pendekatan.,Membandingkan berbagai alternatif solusi dan memilih pendekatan yang lebih relevan.,"Menciptakan solusi baru yang efektif untuk masalah berulang, kompleks, atau tidak bisa diselesai..."
8,Mental Agility,mental_agility,9,Comfort with Ambiguity\n(tetap efektif di situasi tidak jelas),"Ketika menghadapi situasi kerja yang belum jelas arah, data, prioritas, atau keputusannya, peril...",Sulit bergerak atau mengambil tindakan tanpa arahan jelas.,"Mulai bekerja dalam ketidakjelasan, tetapi mudah ragu atau menunggu arahan tambahan.",Tetap bekerja dalam situasi ambigu dengan beberapa panduan.,"Nyaman menghadapi ketidakjelasan, tetap produktif, dan mampu membuat keputusan dengan informasi ...","Menggunakan ketidakjelasan sebagai ruang untuk menemukan peluang, pola baru, atau alternatif str..."
9,Mental Agility,mental_agility,10,Tolerance for Ambiguity \n(mampu memimpin dalam uncertainty tinggi),"Ketika menghadapi atau memimpin situasi dengan ketidakpastian tinggi dan berdampak luas, perilak...","Bingung, reaktif, atau menunda keputusan ketika arah belum jelas.",Mampu beradaptasi setelah mendapat arahan atau keputusan dari pihak lain.,Menjaga produktivitas diri/tim dalam situasi tidak pasti dengan dukungan tertentu.,"Memberi arah, menjaga ketenangan, dan mengambil keputusan dalam ketidakpastian tinggi.","Memimpin organisasi atau fungsi melewati ketidakpastian, membangun arah strategis, dan menciptak..."
10,People Agility,people_agility,1,Listening for understanding\n(mendengarkan & memahami dasar),"Ketika mendengarkan penjelasan, keluhan, masukan, atau ide dari orang lain, perilaku yang paling...",Perhatian mudah teralihkan atau cenderung menunggu giliran bicara.,Mendengarkan bagian yang dianggap relevan saja dan belum menangkap konteks utuh.,"Memberikan perhatian penuh, mengajukan klarifikasi, dan merangkum poin utama.","Mendengarkan untuk memahami makna, emosi, dan nada di balik kata-kata.","Menghubungkan isu, kebutuhan, dan emosi pihak lain untuk mendorong konsensus atau tindak lanjut."
11,People Agility,people_agility,2,Openness to Feedback\n(menerima & mencari masukan),"Ketika menerima masukan atau umpan balik dari orang lain, perilaku yang paling sering ditunjukka...","Defensif, menolak, atau membenarkan diri saat menerima feedback.","Menerima feedback positif/ringan, tetapi belum terbuka pada kritik menantang.",Meminta klarifikasi atau contoh agar memahami feedback dengan tepat.,Menindaklanjuti feedback melalui perubahan perilaku atau peningkatan keterampilan.,"Secara rutin meminta feedback spesifik, jujur, dan menantang dari berbagai sumber."
12,People Agility,people_agility,3,Genuine Curiosity about Others\n(rasa ingin tahu tulus pada orang lain),"Ketika berinteraksi dengan rekan kerja, anggota tim, atau stakeholder, perilaku yang paling seri...",Kurang menunjukkan ketertarikan memahami orang lain dan cepat menyimpulkan.,Bertanya seperlunya hanya untuk memenuhi kebutuhan tugas.,"Menunjukkan rasa ingin tahu terhadap kebutuhan, alasan, pengalaman, atau konteks orang lain.","Aktif menggali motivasi, kekhawatiran, harapan, dan cara pandang orang lain.",Membangun pemahaman mendalam sehingga tercipta kepercayaan dan kolaborasi lebih kuat.
13,People Agility,people_agility,4,Collaboration with Diversity\n(Bekerja efektif dalam keberagaman),"Dalam kolaborasi dengan pihak yang memiliki latar belakang, fungsi, gaya kerja, atau pandangan b...",Berinteraksi hanya jika dibutuhkan dan lebih memilih bekerja dengan orang yang serupa.,Bersedia bekerja dalam tim beragam jika diarahkan atasan atau pihak lain.,Menyesuaikan gaya komunikasi agar efektif bekerja dengan pihak berbeda.,"Memanfaatkan keberagaman perspektif untuk menghasilkan ide, solusi, atau keputusan lebih baik.",Membangun kolaborasi lintas perbedaan yang menghasilkan output unggul dan budaya kerja inklusif.
14,People Agility,people_agility,5,Valuing Diverse Opinions\n(Menghargai opini berbeda dalam pengambilan keputusan),"Ketika dihadapkan pada beragam pendapat dalam diskusi atau proses pengambilan keputusan, perilak...","Meremehkan, menolak, atau mengabaikan pendapat yang tidak sesuai.","Mendengarkan pendapat berbeda, tetapi masih sulit menerimanya sebagai masukan bernilai.",Menghargai perbedaan pendapat dan memberi ruang orang lain menyampaikan pandangan.,Mempertimbangkan pendapat berbeda secara serius sebelum mengambil keputusan.,Mengintegrasikan berbagai pendapat untuk menciptakan solusi terbaik yang seimbang dan dapat dite...
15,People Agility,people_agility,6,Understanding Different Perspectives\n(Analisis multi-sudut pandang untuk pemahaman mendalam),"Ketika muncul perbedaan sudut pandang, kepentingan, atau cara pandang dalam melihat suatu masala...",Sulit memahami sudut pandang lain dan bertahan pada pandangan sendiri.,"Mencoba memahami sudut pandang lain, tetapi sering kembali ke perspektif awal.",Menerima perspektif berbeda jika dijelaskan secara logis dan relevan.,"Menganalisis kebutuhan, kepentingan, batasan, dan sudut pandang berbagai pihak.",Memetakan perspektif berbeda atau bertentangan untuk membangun pemahaman dan keputusan lebih mat...
16,People Agility,people_agility,7,Empathy\n(Merasakan & memahami emosi orang lain),"Ketika menghadapi situasi yang melibatkan emosi, tekanan, atau perasaan orang lain, perilaku yan...",Kurang menyadari atau salah menafsirkan emosi orang lain sehingga respons kurang sesuai.,"Menyadari emosi yang terlihat jelas, tetapi belum memahami konteks atau penyebabnya.","Mengamati ekspresi, nada bicara, dan situasi orang lain serta menunjukkan perhatian.","Menggali penyebab perasaan orang lain dan memberi respons, dukungan, atau arahan tepat.","Membaca dinamika emosi individu/kelompok, merespons empatik, dan menjaga hubungan kerja produktif."
17,People Agility,people_agility,8,Conflict Navigation\n(menghadapi konflik secara konstruktif),"Ketika menghadapi konflik kerja atau perbedaan kepentingan dalam pekerjaan, perilaku yang paling...","Menghindari konflik, membiarkan masalah berlarut, atau merespons secara emosional.","Mencoba menghadapi konflik, tetapi mundur ketika situasi meningkat.",Menangani konflik sederhana dengan komunikasi terbuka dan dukungan bila diperlukan.,"Mengelola konflik secara konstruktif, fokus pada isu utama, dan mencari solusi adil.","Mengubah konflik menjadi kesempatan strategis untuk memperkuat kepercayaan, ekspektasi, dan kerj..."
18,People Agility,people_agility,9,Managing Challenging Stakeholder\n(Mengelola relasi berkelanjutan dengan stakeholder sulit),"Ketika harus menjaga hubungan profesional dengan individu/stakeholder yang sulit, berpengaruh, a...",Menghindari interaksi yang diperlukan atau merespons kurang tepat sehingga memperburuk hubungan.,"Berinteraksi seperlunya, tetapi masih sering terjadi gesekan dan membutuhkan bantuan pihak ketiga.","Menjaga profesionalisme, mengelola emosi, dan mulai memahami kepentingan pihak kunci.","Menyesuaikan gaya komunikasi, mencari titik temu, dan membangun hubungan kerja produktif.",Menjadi penghubung terpercaya antar kepentingan berbeda dan menjaga kerja sama berkelanjutan.
19,People Agility,people_agility,10,Conflict Mediation\n(menjadi penengah & penyatu pihak berbeda),"Ketika menghadapi konflik antarindividu, antartim, atau antarkepentingan yang membutuhkan peneng...",Kesulitan menangani konflik dan cenderung memperkeruh keadaan atau terlihat memihak.,"Membantu menyelesaikan konflik sederhana, tetapi terbatas pada situasi tidak kompleks.",Berperan sebagai penengah dan memastikan pihak terkait didengar.,Menjadi mediator efektif dalam konflik kompleks dengan memfasilitasi dialog dan kesepakatan.,Menjadi penengah terpercaya dalam konflik strategis/lintas kelompok dan membangun komitmen jangk...
20,Change Agility,change_agility,1,Adapting to New Systems\n(mengikuti perubahan dasar),"Ketika diterapkan sistem, prosedur, tools, atau mekanisme kerja baru, perilaku yang paling serin...",Lambat beradaptasi dan cenderung menolak/menghindari sistem baru.,"Mulai mencoba sistem/prosedur baru, tetapi masih membutuhkan banyak arahan.",Mampu beradaptasi jika tersedia panduan jelas.,Cepat menyesuaikan diri dan membantu orang lain memahami penggunaannya.,"Mengoptimalkan sistem/prosedur baru untuk meningkatkan efektivitas, efisiensi, atau kualitas kerja."
21,Change Agility,change_agility,2,Comfort with New Ways of Working\n(mulai nyaman dengan cara kerja baru),"Ketika diterapkan cara kerja, metode, atau pendekatan baru, perilaku yang paling sering ditunjuk...",Sangat tidak nyaman dan sulit meninggalkan cara kerja lama.,"Mencoba beradaptasi, tetapi sering kembali pada kebiasaan lama.",Menyesuaikan diri setelah memahami alasan dan manfaat perubahan.,Nyaman bekerja dengan pendekatan baru dan cepat menyesuaikan perilaku kerja.,"Antusias mencoba cara kerja baru, memberi contoh, dan mendorong perbaikan proses."
22,Change Agility,change_agility,3,Comfort with Sudden Change\n(tetap bekerja saat perubahan mendadak),"Ketika menghadapi perubahan mendadak dalam prioritas, arahan, target, atau situasi kerja, perila...","Tidak nyaman, kewalahan, atau sulit melanjutkan pekerjaan.","Berusaha menyesuaikan diri, tetapi butuh waktu lebih lama untuk kembali produktif.",Mampu beradaptasi jika perubahan dijelaskan dengan jelas.,Cepat menyesuaikan prioritas dan tetap produktif.,"Melihat perubahan mendadak sebagai peluang belajar, memperbaiki cara kerja, atau meningkatkan ha..."
23,Change Agility,change_agility,4,Managing Resistance to Change\n(pengelolaan resistensi),"Ketika menghadapi perubahan yang menimbulkan ketidakpastian, ketidaknyamanan, atau resistensi, p...",Menolak perubahan dan sulit menerima cara kerja atau arah baru.,"Mencoba menerima perubahan, tetapi sering kembali ke cara lama.","Menerima perubahan dengan bantuan penjelasan, arahan, atau dukungan tambahan.",Mengelola resistensi diri dan beradaptasi secara konstruktif.,Mendukung perubahan secara aktif dan membantu orang lain mengurangi resistensi.
24,Change Agility,change_agility,5,Adaptive Learning & Experimentation\n(aktif belajar hal baru),"Ketika perubahan menuntut pengetahuan, keterampilan, atau pendekatan baru, perilaku yang paling ...",Merasa cukup dengan kemampuan saat ini dan kurang terdorong belajar hal baru.,"Tertarik pada hal baru, tetapi belum konsisten mempelajari atau mencobanya.",Mempelajari pengetahuan/keterampilan baru yang relevan ketika dibutuhkan.,Aktif belajar lintas bidang dan mencoba penerapannya dalam pekerjaan.,"Konsisten mencari, menguji, dan menerapkan pembelajaran baru untuk menciptakan solusi lebih baik."
25,Change Agility,change_agility,6,Viewing Change as Opportunity\n(melihat perubahan sebagai peluang),"Ketika menilai perubahan yang terjadi di lingkungan kerja, perilaku yang paling sering ditunjukk...","Melihat perubahan sebagai beban, gangguan, atau ancaman rutinitas.","Menerima perubahan, tetapi masih ragu dan sangat berhati-hati.",Melihat perubahan sebagai sesuatu yang perlu diikuti dan menyesuaikan diri saat diperlukan.,"Melihat perubahan sebagai kesempatan belajar, memperbaiki proses, atau meningkatkan kinerja.","Aktif mencari peluang dari perubahan untuk menciptakan nilai, keunggulan, atau cara kerja baru."
26,Change Agility,change_agility,7,Proposing New Ideas\n(mulai menginisiasi perubahan),"Ketika melihat peluang perbaikan atau kebutuhan perubahan, perilaku yang paling sering ditunjukk...",Jarang mengusulkan ide dan lebih memilih mengikuti arahan.,Sesekali mengusulkan ide sederhana ketika diminta atau saat masalah terlihat jelas.,"Memberikan saran relevan untuk perbaikan proses, kualitas, atau penyelesaian masalah.","Konsisten mengusulkan ide baru yang relevan, realistis, dan bermanfaat.","Proaktif menciptakan ide inovatif, menginspirasi orang lain, dan mendorong implementasi perubaha..."
27,Change Agility,change_agility,8,Risk-Taking for Innovation\n(berani mencoba pendekatan baru),"Ketika perlu mencoba cara, pendekatan, atau solusi baru yang belum sepenuhnya terbukti, perilaku...",Menghindari risiko dan memilih metode aman atau biasa digunakan.,"Mencoba metode baru, tetapi masih ragu dan mudah kembali ke cara lama.",Berani mengambil risiko terukur setelah mempertimbangkan dampaknya.,"Mencoba pendekatan baru meskipun hasil belum jelas, dengan tetap mengelola risiko.","Mendorong eksperimen dalam tim, mengambil risiko terukur, dan menciptakan pembelajaran/inovasi d..."
28,Change Agility,change_agility,9,Calmness in Uncertainty\n(tetap tenang di kondisi tidak pasti),"Ketika menghadapi situasi kerja yang tidak pasti, berubah cepat, atau belum memiliki arah jelas,...","Mudah cemas, reaktif, atau sulit berpikir jernih.","Berusaha tenang, tetapi sering kehilangan fokus saat situasi belum jelas.",Mampu mengelola diri dan tetap menjalankan pekerjaan dalam ketidakpastian.,"Tetap tenang, menjaga fokus, dan mengambil keputusan tepat dalam situasi tidak pasti.","Menjaga ketenangan diri/orang lain, membaca peluang, dan mengambil langkah strategis."
29,Change Agility,change_agility,10,Proactive in Anticipating Change\n(mengantisipasi perubahan sebelum terjadi),"Ketika menghadapi kemungkinan perubahan di masa depan, perilaku yang paling sering ditunjukkan a...",Tidak mengantisipasi perubahan dan baru bergerak setelah perubahan terjadi.,"Bereaksi setelah perubahan mulai terlihat, tetapi belum memiliki persiapan memadai.",Memperhatikan tanda-tanda perubahan dan melakukan persiapan terbatas.,"Aktif memindai lingkungan, membaca tren, dan menyiapkan rencana menghadapi perubahan.","Memprediksi arah perubahan, menyiapkan skenario strategis, dan menggerakkan organisasi sebelum p..."
30,Result Agility,result_agility,1,Task Completion Quality \n(menyelesaikan tugas dengan baik),"Ketika menyelesaikan tugas atau tanggung jawab kerja, perilaku yang paling sering ditunjukkan ad...","Sering tidak menyelesaikan tugas sesuai standar, tenggat waktu, atau ekspektasi.","Menyelesaikan tugas, tetapi kualitas/ketepatan waktu belum konsisten.","Menyelesaikan tugas dengan kualitas cukup baik, stabil, dan sesuai standar.","Konsisten menghasilkan pekerjaan berkualitas tinggi, tepat waktu, dan dapat diandalkan.","Menghasilkan output melampaui ekspektasi, memberi nilai tambah, dan menjadi contoh standar kuali..."
31,Result Agility,result_agility,2,Action-Oriented & Takes Initiative \n(proaktif bertindak),"Ketika melihat peluang perbaikan, masalah, atau kebutuhan tindakan dalam pekerjaan, perilaku yan...",Menunggu instruksi jelas sebelum bertindak.,"Mengidentifikasi peluang/masalah, tetapi masih menunggu persetujuan atau dorongan.",Mengambil inisiatif menangani masalah dalam area tanggung jawab.,Aktif menciptakan peluang perbaikan dan mengantisipasi masalah sebelum berdampak.,Mengambil inisiatif yang menciptakan perubahan positif dan menggerakkan orang lain.
32,Result Agility,result_agility,3,Driving for impact\n(fokus pada hasil kerja),"Ketika menilai keberhasilan kerja, perilaku yang paling sering ditunjukkan adalah…","Mengukur keberhasilan dari aktivitas yang dilakukan, bukan hasil/dampak.","Fokus menyelesaikan pekerjaan sesuai prosedur, tetapi belum memastikan efektivitas hasil.",Memahami tujuan akhir pekerjaan dan bertanggung jawab terhadap pencapaiannya.,"Mengidentifikasi hambatan, menyesuaikan proses, menyusun rencana, dan menggunakan metrik keberha...","Berorientasi pada dampak nyata dan memastikan hasil kerja memberi nilai bagi tim, pelanggan, fun..."

In [24]:
# ============================================================
# CELL 21 — CEK NOMOR INDIKATOR
# ============================================================

print("Jumlah total indikator:", len(indicator_master))

print("\nJumlah indikator per dimension:")
display(
    indicator_master.groupby("dimension").size()
)

print("\nData indicator_no:")
display(
    indicator_master[
        [
            "dimension",
            "indicator_no",
            "indicator"
        ]
    ]
)

Jumlah total indikator: 50

Jumlah indikator per dimension:

dimension
Change Agility    10
Mental Agility    10
People Agility    10
Result Agility    10
Self Awareness    10
dtype: int64

Data indicator_no:

         dimension  indicator_no                                                                                      indicator
0   Mental Agility             1                                             Analytical Thinking\n(memahami data & fakta dasar)
1   Mental Agility             2                                                Root Cause Analysis\n(mencari penyebab masalah)
2   Mental Agility             3                           Critical Thinking & Inquisitiveness\n(mempertanyakan & mengevaluasi)
3   Mental Agility             4                             Explaining Complexity\n(menjelaskan hal kompleks secara sederhana)
4   Mental Agility             5                                     Intellectual Synthesis\n(menghubungkan berbagai informasi)
5   Mental Agility             6   Integrating Diverse Perspective\n(pengambilan keputusan melihat dari berbagai sudut pandang)
6   Mental Agility             7                                                Creative Exploration\n(mencari pendekatan baru)
7   Mental Agility             8                                         Breaking Patterned thinking\n(menciptakan solusi baru)
8   Mental Agility             9                                 Comfort with Ambiguity\n(tetap efektif di situasi tidak jelas)
9   Mental Agility            10                            Tolerance for Ambiguity \n(mampu memimpin dalam uncertainty tinggi)
10  People Agility             1                                   Listening for understanding\n(mendengarkan & memahami dasar)
11  People Agility             2                                             Openness to Feedback\n(menerima & mencari masukan)
12  People Agility             3                        Genuine Curiosity about Others\n(rasa ingin tahu tulus pada orang lain)
13  People Agility             4                              Collaboration with Diversity\n(Bekerja efektif dalam keberagaman)
14  People Agility             5               Valuing Diverse Opinions\n(Menghargai opini berbeda dalam pengambilan keputusan)
15  People Agility             6  Understanding Different Perspectives\n(Analisis multi-sudut pandang untuk pemahaman mendalam)
16  People Agility             7                                               Empathy\n(Merasakan & memahami emosi orang lain)
17  People Agility             8                                   Conflict Navigation\n(menghadapi konflik secara konstruktif)
18  People Agility             9   Managing Challenging  Stakeholder\n(Mengelola relasi berkelanjutan dengan stakeholder sulit)
19  People Agility            10                                 Conflict Mediation\n(menjadi penengah & penyatu pihak berbeda)
20  Change Agility             1                                           Adapting to New Systems\n(mengikuti perubahan dasar)
21  Change Agility             2                        Comfort with New Ways of Working\n(mulai nyaman dengan cara kerja baru)
22  Change Agility             3                            Comfort with Sudden Change\n(tetap bekerja saat perubahan mendadak)
23  Change Agility             4                                        Managing Resistance to Change\n(pengelolaan resistensi)
24  Change Agility             5                                  Adaptive Learning & Experimentation\n(aktif belajar hal baru)
25  Change Agility             6                             Viewing Change as Opportunity\n(melihat perubahan sebagai peluang)
26  Change Agility             7                                            Proposing New Ideas\n(mulai menginisiasi perubahan)
27  Change Agility             8                                   Risk-Taking for Innovation\n(berani mencoba pendekatan baru)
28  Change Agility             9                                 Calmness in Uncertainty\n(tetap tenang di kondisi tidak pasti)
29  Change Agility            10                   Proactive in Anticipating Change\n(mengantisipasi perubahan sebelum terjadi)
30  Result Agility             1                                    Task Completion Quality \n(menyelesaikan tugas dengan baik)
31  Result Agility             2                                      Action-Oriented & Takes Initiative \n(proaktif bertindak)
32  Result Agility             3                                                   Driving for impact\n(fokus pada hasil kerja)
33  Result Agility             4                       Tenacity & Strategic Persistence\n(menjaga komitmen di tengah tantangan)
34  Result Agility             5                                   Learning from Outcomes\n(belajar dari hasil & kesalahan tim)
35  Result Agility             6            Deciding with Incomplete Data\n(mengambil keputusan dengan data/informasi terbatas)
36  Result Agility             7                                       Focus Under Pressure\n(tetap fokus dalam tekanan tinggi)
37  Result Agility             8                      Adapting Strategy When Needed\n(mengubah strategi untuk hasil lebih baik)
38  Result Agility             9                       Agile Problem-Solving Under Pressure\n(rencana di tengah ketidakpastian)
39  Result Agility            10                             Drive for High Performance\n(sistem perencanaan berkinerja tinggi)
40  Self Awareness             1                                                 Openness to Criticism\n(menerima kritik dasar)
41  Self Awareness             2                                                       Admitting Mistakes\n(mengakui kesalahan)
42  Self Awareness             3                                            Seeking Feedback on Performance\n(mencari feedback)
43  Self Awareness             4                          Understanding Strengths & Weaknesses\n(memahami kekuatan & kelemahan)
44  Self Awareness             5                                                Reflective Practices\n(melakukan refleksi diri)
45  Self Awareness             6                          Proactive Self-Development for Adaptation\n(aktif mengembangkan diri)
46  Self Awareness             7                                      Objective Self-Assessment\n(menilai diri secara objektif)
47  Self Awareness             8                  Awareness of Impact on Others\n(memahami dampak perilaku terhadap orang lain)
48  Self Awareness             9                                 Managing Emotions Effectively\n(mengelola emosi secara matang)
49  Self Awareness            10                 Deep Pattern Recognition & Bias Awareness\n(refleksi diri mendalam & autentik)

In [25]:
# ============================================================
# CELL 22 — BUAT INDICATOR ID
# ============================================================

indicator_master["indicator_no"] = pd.to_numeric(
    indicator_master["indicator_no"],
    errors="coerce"
)

# Validasi nomor indikator
if indicator_master["indicator_no"].isna().any():

    print("❌ Masih ada indicator_no yang kosong:")

    display(
        indicator_master[
            indicator_master["indicator_no"].isna()
        ][
            [
                "dimension",
                "indicator_no",
                "indicator"
            ]
        ]
    )

    raise ValueError(
        "indicator_no masih memiliki nilai kosong."
    )

# Pastikan integer
indicator_master["indicator_no"] = (
    indicator_master["indicator_no"]
    .astype(int)
)

# Bersihkan dimension key
indicator_master["dimension_key"] = (
    indicator_master["dimension_key"]
    .astype(str)
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
)

# Buat indicator ID
indicator_master["indicator_id"] = (
    indicator_master["dimension_key"]
    + "_"
    + indicator_master["indicator_no"]
        .astype(str)
        .str.zfill(2)
)

print("Indicator ID berhasil dibuat.")

display(
    indicator_master[
        [
            "dimension",
            "indicator_no",
            "indicator_id",
            "indicator"
        ]
    ]
)

Indicator ID berhasil dibuat.

         dimension  indicator_no       indicator_id                                                                                      indicator
0   Mental Agility             1  mental_agility_01                                             Analytical Thinking\n(memahami data & fakta dasar)
1   Mental Agility             2  mental_agility_02                                                Root Cause Analysis\n(mencari penyebab masalah)
2   Mental Agility             3  mental_agility_03                           Critical Thinking & Inquisitiveness\n(mempertanyakan & mengevaluasi)
3   Mental Agility             4  mental_agility_04                             Explaining Complexity\n(menjelaskan hal kompleks secara sederhana)
4   Mental Agility             5  mental_agility_05                                     Intellectual Synthesis\n(menghubungkan berbagai informasi)
5   Mental Agility             6  mental_agility_06   Integrating Diverse Perspective\n(pengambilan keputusan melihat dari berbagai sudut pandang)
6   Mental Agility             7  mental_agility_07                                                Creative Exploration\n(mencari pendekatan baru)
7   Mental Agility             8  mental_agility_08                                         Breaking Patterned thinking\n(menciptakan solusi baru)
8   Mental Agility             9  mental_agility_09                                 Comfort with Ambiguity\n(tetap efektif di situasi tidak jelas)
9   Mental Agility            10  mental_agility_10                            Tolerance for Ambiguity \n(mampu memimpin dalam uncertainty tinggi)
10  People Agility             1  people_agility_01                                   Listening for understanding\n(mendengarkan & memahami dasar)
11  People Agility             2  people_agility_02                                             Openness to Feedback\n(menerima & mencari masukan)
12  People Agility             3  people_agility_03                        Genuine Curiosity about Others\n(rasa ingin tahu tulus pada orang lain)
13  People Agility             4  people_agility_04                              Collaboration with Diversity\n(Bekerja efektif dalam keberagaman)
14  People Agility             5  people_agility_05               Valuing Diverse Opinions\n(Menghargai opini berbeda dalam pengambilan keputusan)
15  People Agility             6  people_agility_06  Understanding Different Perspectives\n(Analisis multi-sudut pandang untuk pemahaman mendalam)
16  People Agility             7  people_agility_07                                               Empathy\n(Merasakan & memahami emosi orang lain)
17  People Agility             8  people_agility_08                                   Conflict Navigation\n(menghadapi konflik secara konstruktif)
18  People Agility             9  people_agility_09   Managing Challenging  Stakeholder\n(Mengelola relasi berkelanjutan dengan stakeholder sulit)
19  People Agility            10  people_agility_10                                 Conflict Mediation\n(menjadi penengah & penyatu pihak berbeda)
20  Change Agility             1  change_agility_01                                           Adapting to New Systems\n(mengikuti perubahan dasar)
21  Change Agility             2  change_agility_02                        Comfort with New Ways of Working\n(mulai nyaman dengan cara kerja baru)
22  Change Agility             3  change_agility_03                            Comfort with Sudden Change\n(tetap bekerja saat perubahan mendadak)
23  Change Agility             4  change_agility_04                                        Managing Resistance to Change\n(pengelolaan resistensi)
24  Change Agility             5  change_agility_05                                  Adaptive Learning & Experimentation\n(aktif belajar hal baru)
25  Change Agility             6  change_agility_06                             Viewing Change as Opportunity\n(melihat perubahan sebagai peluang)
26  Change Agility             7  change_agility_07                                            Proposing New Ideas\n(mulai menginisiasi perubahan)
27  Change Agility             8  change_agility_08                                   Risk-Taking for Innovation\n(berani mencoba pendekatan baru)
28  Change Agility             9  change_agility_09                                 Calmness in Uncertainty\n(tetap tenang di kondisi tidak pasti)
29  Change Agility            10  change_agility_10                   Proactive in Anticipating Change\n(mengantisipasi perubahan sebelum terjadi)
30  Result Agility             1  result_agility_01                                    Task Completion Quality \n(menyelesaikan tugas dengan baik)
31  Result Agility             2  result_agility_02                                      Action-Oriented & Takes Initiative \n(proaktif bertindak)
32  Result Agility             3  result_agility_03                                                   Driving for impact\n(fokus pada hasil kerja)
33  Result Agility             4  result_agility_04                       Tenacity & Strategic Persistence\n(menjaga komitmen di tengah tantangan)
34  Result Agility             5  result_agility_05                                   Learning from Outcomes\n(belajar dari hasil & kesalahan tim)
35  Result Agility             6  result_agility_06            Deciding with Incomplete Data\n(mengambil keputusan dengan data/informasi terbatas)
36  Result Agility             7  result_agility_07                                       Focus Under Pressure\n(tetap fokus dalam tekanan tinggi)
37  Result Agility             8  result_agility_08                      Adapting Strategy When Needed\n(mengubah strategi untuk hasil lebih baik)
38  Result Agility             9  result_agility_09                       Agile Problem-Solving Under Pressure\n(rencana di tengah ketidakpastian)
39  Result Agility            10  result_agility_10                             Drive for High Performance\n(sistem perencanaan berkinerja tinggi)
40  Self Awareness             1  self_awareness_01                                                 Openness to Criticism\n(menerima kritik dasar)
41  Self Awareness             2  self_awareness_02                                                       Admitting Mistakes\n(mengakui kesalahan)
42  Self Awareness             3  self_awareness_03                                            Seeking Feedback on Performance\n(mencari feedback)
43  Self Awareness             4  self_awareness_04                          Understanding Strengths & Weaknesses\n(memahami kekuatan & kelemahan)
44  Self Awareness             5  self_awareness_05                                                Reflective Practices\n(melakukan refleksi diri)
45  Self Awareness             6  self_awareness_06                          Proactive Self-Development for Adaptation\n(aktif mengembangkan diri)
46  Self Awareness             7  self_awareness_07                                      Objective Self-Assessment\n(menilai diri secara objektif)
47  Self Awareness             8  self_awareness_08                  Awareness of Impact on Others\n(memahami dampak perilaku terhadap orang lain)
48  Self Awareness             9  self_awareness_09                                 Managing Emotions Effectively\n(mengelola emosi secara matang)
49  Self Awareness            10  self_awareness_10                 Deep Pattern Recognition & Bias Awareness\n(refleksi diri mendalam & autentik)

In [26]:
#cell 23

indicator_count = (
    indicator_master
    .groupby("dimension")
    .size()
)

indicator_count

dimension
Change Agility    10
Mental Agility    10
People Agility    10
Result Agility    10
Self Awareness    10
dtype: int64

In [27]:
# ============================================================
# CELL 23 — VALIDASI INDICATOR ID
# ============================================================

print("Indicator ID yang tersedia:")
print(
    indicator_master["indicator_id"]
    .tolist()
)

print("\nJumlah indicator:")
print(
    indicator_master["indicator_id"].nunique()
)

Indicator ID yang tersedia:
['mental_agility_01', 'mental_agility_02', 'mental_agility_03', 'mental_agility_04', 'mental_agility_05', 'mental_agility_06', 'mental_agility_07', 'mental_agility_08', 'mental_agility_09', 'mental_agility_10', 'people_agility_01', 'people_agility_02', 'people_agility_03', 'people_agility_04', 'people_agility_05', 'people_agility_06', 'people_agility_07', 'people_agility_08', 'people_agility_09', 'people_agility_10', 'change_agility_01', 'change_agility_02', 'change_agility_03', 'change_agility_04', 'change_agility_05', 'change_agility_06', 'change_agility_07', 'change_agility_08', 'change_agility_09', 'change_agility_10', 'result_agility_01', 'result_agility_02', 'result_agility_03', 'result_agility_04', 'result_agility_05', 'result_agility_06', 'result_agility_07', 'result_agility_08', 'result_agility_09', 'result_agility_10', 'self_awareness_01', 'self_awareness_02', 'self_awareness_03', 'self_awareness_04', 'self_awareness_05', 'self_awareness_06', 'self_awareness_07', 'self_awareness_08', 'self_awareness_09', 'self_awareness_10']

Jumlah indicator:
50

In [28]:
#cell 24

question_indicator_map = {
    1: "mental_agility_06",
    2: "mental_agility_05",
    3: "mental_agility_09",
    4: "mental_agility_02",
    5: "mental_agility_04",
    6: "mental_agility_07",
    7: "mental_agility_08",
    8: "mental_agility_10",
    9: "mental_agility_03",
    10: "mental_agility_01",

    11: "people_agility_04",
    12: "people_agility_08",
    13: "people_agility_02",
    14: "people_agility_10",
    15: "people_agility_07",
    16: "people_agility_06",
    17: "people_agility_09",
    18: "people_agility_05",
    19: "people_agility_03",
    20: "people_agility_01",

    21: "change_agility_03",
    22: "change_agility_06",
    23: "change_agility_01",
    24: "change_agility_04",
    25: "change_agility_08",
    26: "change_agility_09",
    27: "change_agility_02",
    28: "change_agility_07",
    29: "change_agility_05",
    30: "change_agility_10",

    31: "result_agility_07",
    32: "result_agility_06",
    33: "result_agility_10",
    34: "result_agility_04",
    35: "result_agility_05",
    36: "result_agility_01",
    37: "result_agility_08",
    38: "result_agility_03",
    39: "result_agility_02",
    40: "result_agility_09",

    41: "self_awareness_04",
    42: "self_awareness_05",
    43: "self_awareness_01",
    44: "self_awareness_06",
    45: "self_awareness_08",
    46: "self_awareness_03",
    47: "self_awareness_02",
    48: "self_awareness_07",
    49: "self_awareness_10",
    50: "self_awareness_09"
}

In [29]:
# ============================================================
# CELL 25 — VALIDASI QUESTION → INDICATOR MAPPING
# ============================================================

mapped_indicator_ids = set(
    question_indicator_map.values()
)

master_indicator_ids = set(
    indicator_master["indicator_id"].dropna()
)

missing_indicator_ids = sorted(
    mapped_indicator_ids - master_indicator_ids
)

extra_indicator_ids = sorted(
    master_indicator_ids - mapped_indicator_ids
)

print("Jumlah question mapping :", len(question_indicator_map))
print("Jumlah indicator unik   :", len(mapped_indicator_ids))
print("Jumlah indicator master :", len(master_indicator_ids))

print("\n" + "=" * 60)

if missing_indicator_ids:

    print("❌ INDICATOR YANG TIDAK DITEMUKAN:")

    for x in missing_indicator_ids:
        print(" -", x)

    raise ValueError(
        "Masih ada indicator_id pada mapping "
        "yang tidak ditemukan di indicator_master."
    )

else:

    print(
        "✅ Semua indicator dari question mapping ditemukan."
    )

print("\n" + "=" * 60)

if extra_indicator_ids:

    print("Indicator master yang tidak digunakan:")

    for x in extra_indicator_ids:
        print(" -", x)

else:

    print("✅ Semua indicator master digunakan.")

print("\nVALIDASI BERHASIL.")

Jumlah question mapping : 50
Jumlah indicator unik   : 50
Jumlah indicator master : 50

============================================================
✅ Semua indicator dari question mapping ditemukan.

============================================================
✅ Semua indicator master digunakan.

VALIDASI BERHASIL.

In [30]:
mapped_indicator_ids = set(
    question_indicator_map.values()
)

master_indicator_ids = set(
    indicator_master["indicator_id"]
)

print(
    "Semua indicator ditemukan:",
    mapped_indicator_ids.issubset(master_indicator_ids)
)

Semua indicator ditemukan: True

In [31]:
#cell 26

question_mapping_df = pd.DataFrame({
    "question_no": list(question_indicator_map.keys()),
    "indicator_id": list(question_indicator_map.values())
})

question_mapping_df = question_mapping_df.merge(
    indicator_master[
        [
            "indicator_id",
            "dimension",
            "indicator_no",
            "indicator"
        ]
    ],
    on="indicator_id",
    how="left"
)

question_mapping_df

    question_no       indicator_id       dimension  indicator_no                                                                                      indicator
0             1  mental_agility_06  Mental Agility             6   Integrating Diverse Perspective\n(pengambilan keputusan melihat dari berbagai sudut pandang)
1             2  mental_agility_05  Mental Agility             5                                     Intellectual Synthesis\n(menghubungkan berbagai informasi)
2             3  mental_agility_09  Mental Agility             9                                 Comfort with Ambiguity\n(tetap efektif di situasi tidak jelas)
3             4  mental_agility_02  Mental Agility             2                                                Root Cause Analysis\n(mencari penyebab masalah)
4             5  mental_agility_04  Mental Agility             4                             Explaining Complexity\n(menjelaskan hal kompleks secara sederhana)
5             6  mental_agility_07  Mental Agility             7                                                Creative Exploration\n(mencari pendekatan baru)
6             7  mental_agility_08  Mental Agility             8                                         Breaking Patterned thinking\n(menciptakan solusi baru)
7             8  mental_agility_10  Mental Agility            10                            Tolerance for Ambiguity \n(mampu memimpin dalam uncertainty tinggi)
8             9  mental_agility_03  Mental Agility             3                           Critical Thinking & Inquisitiveness\n(mempertanyakan & mengevaluasi)
9            10  mental_agility_01  Mental Agility             1                                             Analytical Thinking\n(memahami data & fakta dasar)
10           11  people_agility_04  People Agility             4                              Collaboration with Diversity\n(Bekerja efektif dalam keberagaman)
11           12  people_agility_08  People Agility             8                                   Conflict Navigation\n(menghadapi konflik secara konstruktif)
12           13  people_agility_02  People Agility             2                                             Openness to Feedback\n(menerima & mencari masukan)
13           14  people_agility_10  People Agility            10                                 Conflict Mediation\n(menjadi penengah & penyatu pihak berbeda)
14           15  people_agility_07  People Agility             7                                               Empathy\n(Merasakan & memahami emosi orang lain)
15           16  people_agility_06  People Agility             6  Understanding Different Perspectives\n(Analisis multi-sudut pandang untuk pemahaman mendalam)
16           17  people_agility_09  People Agility             9   Managing Challenging  Stakeholder\n(Mengelola relasi berkelanjutan dengan stakeholder sulit)
17           18  people_agility_05  People Agility             5               Valuing Diverse Opinions\n(Menghargai opini berbeda dalam pengambilan keputusan)
18           19  people_agility_03  People Agility             3                        Genuine Curiosity about Others\n(rasa ingin tahu tulus pada orang lain)
19           20  people_agility_01  People Agility             1                                   Listening for understanding\n(mendengarkan & memahami dasar)
20           21  change_agility_03  Change Agility             3                            Comfort with Sudden Change\n(tetap bekerja saat perubahan mendadak)
21           22  change_agility_06  Change Agility             6                             Viewing Change as Opportunity\n(melihat perubahan sebagai peluang)
22           23  change_agility_01  Change Agility             1                                           Adapting to New Systems\n(mengikuti perubahan dasar)
23           24  change_agility_04  Change Agility             4                                        Managing Resistance to Change\n(pengelolaan resistensi)
24           25  change_agility_08  Change Agility             8                                   Risk-Taking for Innovation\n(berani mencoba pendekatan baru)
25           26  change_agility_09  Change Agility             9                                 Calmness in Uncertainty\n(tetap tenang di kondisi tidak pasti)
26           27  change_agility_02  Change Agility             2                        Comfort with New Ways of Working\n(mulai nyaman dengan cara kerja baru)
27           28  change_agility_07  Change Agility             7                                            Proposing New Ideas\n(mulai menginisiasi perubahan)
28           29  change_agility_05  Change Agility             5                                  Adaptive Learning & Experimentation\n(aktif belajar hal baru)
29           30  change_agility_10  Change Agility            10                   Proactive in Anticipating Change\n(mengantisipasi perubahan sebelum terjadi)
30           31  result_agility_07  Result Agility             7                                       Focus Under Pressure\n(tetap fokus dalam tekanan tinggi)
31           32  result_agility_06  Result Agility             6            Deciding with Incomplete Data\n(mengambil keputusan dengan data/informasi terbatas)
32           33  result_agility_10  Result Agility            10                             Drive for High Performance\n(sistem perencanaan berkinerja tinggi)
33           34  result_agility_04  Result Agility             4                       Tenacity & Strategic Persistence\n(menjaga komitmen di tengah tantangan)
34           35  result_agility_05  Result Agility             5                                   Learning from Outcomes\n(belajar dari hasil & kesalahan tim)
35           36  result_agility_01  Result Agility             1                                    Task Completion Quality \n(menyelesaikan tugas dengan baik)
36           37  result_agility_08  Result Agility             8                      Adapting Strategy When Needed\n(mengubah strategi untuk hasil lebih baik)
37           38  result_agility_03  Result Agility             3                                                   Driving for impact\n(fokus pada hasil kerja)
38           39  result_agility_02  Result Agility             2                                      Action-Oriented & Takes Initiative \n(proaktif bertindak)
39           40  result_agility_09  Result Agility             9                       Agile Problem-Solving Under Pressure\n(rencana di tengah ketidakpastian)
40           41  self_awareness_04  Self Awareness             4                          Understanding Strengths & Weaknesses\n(memahami kekuatan & kelemahan)
41           42  self_awareness_05  Self Awareness             5                                                Reflective Practices\n(melakukan refleksi diri)
42           43  self_awareness_01  Self Awareness             1                                                 Openness to Criticism\n(menerima kritik dasar)
43           44  self_awareness_06  Self Awareness             6                          Proactive Self-Development for Adaptation\n(aktif mengembangkan diri)
44           45  self_awareness_08  Self Awareness             8                  Awareness of Impact on Others\n(memahami dampak perilaku terhadap orang lain)
45           46  self_awareness_03  Self Awareness             3                                            Seeking Feedback on Performance\n(mencari feedback)
46           47  self_awareness_02  Self Awareness             2                                                       Admitting Mistakes\n(mengakui kesalahan)
47           48  self_awareness_07  Self Awareness             7                                      Objective Self-Assessment\n(menilai diri secara objektif)
48           49  self_awareness_10  Self Awareness            10                 Deep Pattern Recognition & Bias Awareness\n(refleksi diri mendalam & autentik)
49           50  self_awareness_09  Self Awareness             9                                 Managing Emotions Effectively\n(mengelola emosi secara matang)

In [32]:
#cell 27

question_mapping_df["self_question"] = [
    self_question_cols[i - 1]
    for i in question_mapping_df["question_no"]
]

question_mapping_df["superior_question"] = [
    superior_question_cols[i - 1]
    for i in question_mapping_df["question_no"]
]

question_mapping_df = question_mapping_df[
    [
        "question_no",
        "dimension",
        "indicator_no",
        "indicator_id",
        "indicator",
        "self_question",
        "superior_question"
    ]
]

question_mapping_df

,question_no,dimension,indicator_no,indicator_id,indicator,self_question,superior_question
0,1,Mental Agility,6,mental_agility_06,Integrating Diverse Perspective\n(pengambilan keputusan melihat dari berbagai sudut pandang),"Ketika ada dalam situasi yang mengharuskan pengambilan keputusan atas masalah yang dihadapi, sik...","Ketika ada dalam situasi yang mengharuskan pengambilan keputusan atas masalah yang dihadapi, sik..."
1,2,Mental Agility,5,mental_agility_05,Intellectual Synthesis\n(menghubungkan berbagai informasi),"Ketika menghadapi konsep baru yang rumit, sikap saya adalah..","Ketika menghadapi konsep baru yang rumit, sikap bawahan saya adalah.."
2,3,Mental Agility,9,mental_agility_09,Comfort with Ambiguity\n(tetap efektif di situasi tidak jelas),"Ketika ada dalam yang situasi yang rumit dan belum memiliki kejelasan arah, sikap saya adalah..","Ketika ada dalam yang situasi yang rumit dan belum memiliki kejelasan arah, sikap bawahan saya a..."
3,4,Mental Agility,2,mental_agility_02,Root Cause Analysis\n(mencari penyebab masalah),"Dalam mengidentifikasi akar masalah dalam situasi kompleks, sikap saya adalah....","Dalam mengidentifikasi akar masalah dalam situasi kompleks, sikap bawahan saya adalah...."
4,5,Mental Agility,4,mental_agility_04,Explaining Complexity\n(menjelaskan hal kompleks secara sederhana),"Ketika menjelaskan ide atau masalah yang kompleks kepada orang lain, sikap saya adalah...","Ketika menjelaskan ide atau masalah yang kompleks kepada orang lain, sikap bawahan saya adalah..."
5,6,Mental Agility,7,mental_agility_07,Creative Exploration\n(mencari pendekatan baru),"Saat menghadapi ide - ide baru yang belum terbukti efektivitasnya, sikap saya adalah...","Saat menghadapi ide - ide baru yang belum terbukti efektivitasnya, sikap bawahan saya adalah..."
6,7,Mental Agility,8,mental_agility_08,Breaking Patterned thinking\n(menciptakan solusi baru),"Dalam menghadapi masalah lama menggunakan cara - cara baru , sikap saya adalah..","Dalam menghadapi masalah lama menggunakan cara - cara baru, sikap bawahan saya adalah.."
7,8,Mental Agility,10,mental_agility_10,Tolerance for Ambiguity \n(mampu memimpin dalam uncertainty tinggi),"Ketika menghadapi ketidakpastian dalam bekerja, sikap saya adalah..","Ketika menghadapi ketidakpastian dalam bekerja, sikap bawahan saya adalah.."
8,9,Mental Agility,3,mental_agility_03,Critical Thinking & Inquisitiveness\n(mempertanyakan & mengevaluasi),"Saat menerima informasi, Sikap saya adalah...","Saat menerima informasi, Sikap bawahan saya adalah..."
9,10,Mental Agility,1,mental_agility_01,Analytical Thinking\n(memahami data & fakta dasar),"Ketika menghadapi konsep yang tampak tidak saling berkaitan, sikap saya adalah...","Ketika menghadapi konsep yang tampak tidak saling berkaitan, sikap bawahan saya adalah..."
10,11,People Agility,4,people_agility_04,Collaboration with Diversity\n(Bekerja efektif dalam keberagaman),"Dalam situasi bekerja dengan orang yang memiliki latar belakang berbeda, sikap saya adalah...","Dalam situasi bekerja dengan orang yang memiliki latar belakang berbeda, sikap bawahan saya adal..."
11,12,People Agility,8,people_agility_08,Conflict Navigation\n(menghadapi konflik secara konstruktif),"Dalam menghadapi konflik kerja, sikap saya adalah...","Dalam menghadapi konflik kerja, sikap bawahan saya adalah..."
12,13,People Agility,2,people_agility_02,Openness to Feedback\n(menerima & mencari masukan),"Dalam hal menerima masukan atau umpan balik dari rekan kerja, sikap saya adalah...","Dalam hal menerima masukan atau umpan balik dari rekan kerja, sikap bawahan saya adalah..."
13,14,People Agility,10,people_agility_10,Conflict Mediation\n(menjadi penengah & penyatu pihak berbeda),"Saat menghadapi situasi konflik antarrekan kerja, sikap saya adalah...","Saat menghadapi situasi konflik antarrekan kerja, sikap bawahan saya adalah..."
14,15,People Agility,7,people_agility_07,Empathy\n(Merasakan & memahami emosi orang lain),"Dalam hal memahami emosi dan perasaan orang lain , sikap saya adalah...","Dalam hal memahami emosi dan perasaan orang lain, sikap bawahan saya adalah..."
15,16,People Agility,6,people_agility_06,Understanding Different Perspectives\n(Analisis multi-sudut pandang untuk pemahaman mendalam),"Dalam situasi munculnya perbedaan sudut pandang, sikap saya adalah...","Dalam situasi munculnya perbedaan sudut pandang, sikap bawahan saya adalah..."
16,17,People Agility,9,people_agility_09,Managing Challenging Stakeholder\n(Mengelola relasi berkelanjutan dengan stakeholder sulit),"Dalam hal menjaga hubungan baik dengan individu yang sulit, sikap saya adalah...","Dalam hal menjaga hubungan baik dengan individu yang sulit, sikap bawahan saya adalah..."
17,18,People Agility,5,people_agility_05,Valuing Diverse Opinions\n(Menghargai opini berbeda dalam pengambilan keputusan),"Dalam hal menghadapi pendapat orang lain yang berbeda dengan saya, sikap saya adalah...","Dalam hal menghadapi pendapat orang lain yang berbeda dengan saya, sikap bawahan saya adalah..."
18,19,People Agility,3,people_agility_03,Genuine Curiosity about Others\n(rasa ingin tahu tulus pada orang lain),"Dalam hal menyelesaikan tugas dan butuh berinteraksi dengan rekan kerja, sikap saya adalah...","Dalam hal menyelesaikan tugas dan butuh berinteraksi dengan rekan kerja, sikap bawahan saya adal..."
19,20,People Agility,1,people_agility_01,Listening for understanding\n(mendengarkan & memahami dasar),"Dalam hal mendengarkan orang lain, sikap saya adalah...","Dalam hal mendengarkan orang lain, sikap bawahan saya adalah..."
20,21,Change Agility,3,change_agility_03,Comfort with Sudden Change\n(tetap bekerja saat perubahan mendadak),"Ketika menghadapi perubahan mendadak, sikap saya adalah...","Ketika menghadapi perubahan mendadak, sikap bawahan saya adalah..."
21,22,Change Agility,6,change_agility_06,Viewing Change as Opportunity\n(melihat perubahan sebagai peluang),"Dalam hal menilai perubahan yang terjadi, sikap saya adalah...","Dalam hal menilai perubahan yang terjadi, sikap bawahan saya adalah..."
22,23,Change Agility,1,change_agility_01,Adapting to New Systems\n(mengikuti perubahan dasar),"Dalam hal penerapan sistem atau prosedur baru, sikap saya adalah...","Dalam hal penerapan sistem atau prosedur baru, sikap bawahan saya adalah..."
23,24,Change Agility,4,change_agility_04,Managing Resistance to Change\n(pengelolaan resistensi),"Dalam hal perubahan karena ketidakpastian, sikap saya adalah...","Dalam hal perubahan karena ketidakpastian, sikap bawahan saya adalah..."
24,25,Change Agility,8,change_agility_08,Risk-Taking for Innovation\n(berani mencoba pendekatan baru),"Ketika mencoba cara atau pendekatan baru, sikap saya adalah...","Ketika mencoba cara atau pendekatan baru, sikap bawahan saya adalah..."
25,26,Change Agility,9,change_agility_09,Calmness in Uncertainty\n(tetap tenang di kondisi tidak pasti),"Dalam hal menghadapi situasi yang tidak pasti, sikap saya adalah...","Dalam hal menghadapi situasi yang tidak pasti, sikap bawahan saya adalah..."
26,27,Change Agility,2,change_agility_02,Comfort with New Ways of Working\n(mulai nyaman dengan cara kerja baru),"Ketika diterapkan cara kerja baru, sikap saya adalah...","Ketika diterapkan cara kerja baru, sikap bawahan saya adalah..."
27,28,Change Agility,7,change_agility_07,Proposing New Ideas\n(mulai menginisiasi perubahan),"Dalam hal inisiatif ide/cara baru, sikap saya adalah...","Dalam hal inisiatif ide/cara baru, sikap bawahan saya adalah..."
28,29,Change Agility,5,change_agility_05,Adaptive Learning & Experimentation\n(aktif belajar hal baru),"Dalam hal rasa ingin tahu dan keinginan belajar, sikap saya adalah...","Dalam hal rasa ingin tahu dan keinginan belajar, sikap bawahan saya adalah..."
29,30,Change Agility,10,change_agility_10,Proactive in Anticipating Change\n(mengantisipasi perubahan sebelum terjadi),"Dalam hal mengatisipasi perubahan, sikap saya adalah...","Dalam hal mengatisipasi perubahan, sikap bawahan saya adalah..."
30,31,Result Agility,7,result_agility_07,Focus Under Pressure\n(tetap fokus dalam tekanan tinggi),"Ketika menghadapi tekanan atau hambatan, sikap saya adalah...","Ketika menghadapi tekanan atau hambatan, sikap bawahan saya adalah..."
31,32,Result Agility,6,result_agility_06,Deciding with Incomplete Data\n(mengambil keputusan dengan data/informasi terbatas),"Dalam hal pengambilan keputusan dalam situasi yang tidak jelas, sikap saya adalah...","Dalam hal pengambilan keputusan dalam situasi yang tidak jelas, sikap bawahan saya adalah..."
32,33,Result Agility,10,result_agility_10,Drive for High Performance\n(sistem perencanaan berkinerja tinggi),"Dalam hal dorongan untuk mencapai hasil terbaik, sikap saya adalah....","Dalam hal dorongan untuk mencapai hasil terbaik, sikap bawahan saya adalah...."
33,34,Result Agility,4,result_agility_04,Tenacity & Strategic Persistence\n(menjaga komitmen di tengah tantangan),"Ketika menghadapi tantangan berat, sikap saya adalah...","Ketika menghadapi tantangan berat, sikap bawahan saya adalah..."
34,35,Result Agility,5,result_agility_05,Learning from Outcomes\n(belajar dari hasil & kesalahan tim),"Setelah mengalami keberhasilan atau kegagalan, sikap saya adalah...","Setelah mengalami keberhasilan atau kegagalan, sikap bawahan saya adalah..."
35,36,Result Agility,1,result_agility_01,Task Completion Quality \n(menyelesaikan tugas dengan baik),Sikap saya terhadap tugas kerja adalah...,Sikap bawahan saya terhadap tugas kerja adalah...
36,37,Result Agility,8,result_agility_08,Adapting Strategy When Needed\n(mengubah strategi untuk hasil lebih baik),"Ketika strategi kerja tidak lagi efektif, sikap saya adalah...","Ketika strategi kerja tidak lagi efektif, sikap bawahan saya adalah..."
37,38,Result Agility,3,result_agility_03,Driving for impact\n(fokus pada hasil kerja),"Dalam menilai keberhasilan kerja, sikap saya adalah...","Dalam menilai keberhasilan kerja, sikap bawahan saya adalah..."
38,39,Result Agility,2,result_agility_02,Action-Oriented & Takes Initiative \n(proaktif bertindak),"Dalam hal melihat peluang atau masalah, sikap saya adalah...","Dalam hal melihat peluang atau masalah, sikap bawahan saya adalah..."
39,40,Result Agility,9,result_agility_09,Agile Problem-Solving Under Pressure\n(rencana di tengah ketidakpastian),"Ketika menghadapi rintangan tak terduga, sikap saya adalah...","Ketika menghadapi rintangan tak terduga, sikap bawahan saya adalah..."
40,41,Self Awareness,4,self_awareness_04,Understanding Strengths & Weaknesses\n(memahami kekuatan & kelemahan),"Dalam hal evaluasi kekuatan dan kelemahan diri, sikap saya adalah...","Dalam hal evaluasi kekuatan dan kelemahan diri, sikap bawahan saya adalah..."
41,42,Self Awareness,5,self_awareness_05,Reflective Practices\n(melakukan refleksi diri),"Setelah mengalami suatu pengalaman kerja, sikap saya adalah...","Setelah mengalami suatu pengalaman kerja, sikap bawahan saya adalah..."
42,43,Self Awareness,1,self_awareness_01,Openness to Criticism\n(menerima kritik dasar),"Ketika menerima kritik atau masukan, sikap saya adalah...","Ketika menerima kritik atau masukan, sikap bawahan saya adalah..."
43,44,Self Awareness,6,self_awareness_06,Proactive Self-Development for Adaptation\n(aktif mengembangkan diri),Sikap saya terhadap pengembangan diri adalah...,Sikap bawahan saya terhadap pengembangan diri adalah...
44,45,Self Awareness,8,self_awareness_08,Awareness of Impact on Others\n(memahami dampak perilaku terhadap orang lain),"Dalam hal perilaku saya mempengaruhi orang lain, sikap saya adalah..","Dalam hal perilaku saya mempengaruhi orang lain, sikap bawahan saya adalah.."
45,46,Self Awareness,3,self_awareness_03,Seeking Feedback on Performance\n(mencari feedback),Sikap saya terhadap kinerja diri saya adalah..,Sikap bawahan saya terhadap kinerja dirinya adalah..
46,47,Self Awareness,2,self_awareness_02,Admitting Mistakes\n(mengakui kesalahan),"Ketika melakukan kesalahan, sikap saya adalah...","Ketika melakukan kesalahan, sikap bawahan saya adalah..."
47,48,Self Awareness,7,self_awareness_07,Objective Self-Assessment\n(menilai diri secara objektif),"Dalam menilai kemampuan diri, sikap saya adalah...","Dalam menilai kemampuan diri, sikap bawahan saya adalah..."
48,49,Self Awareness,10,self_awareness_10,Deep Pattern Recognition & Bias Awareness\n(refleksi diri mendalam & autentik),"Dalam hal refleksi diri, sikap saya adalah...","Dalam hal refleksi diri, sikap bawahan saya adalah..."
49,50,Self Awareness,9,self_awareness_09,Managing Emotions Effectively\n(mengelola emosi secara matang),"Dalam situasi yang memicu emosi, sikap saya adalah...","Dalam situasi yang memicu emosi, sikap bawahan saya adalah..."

In [33]:
# ============================================================
# CELL 28 — WIDE TO LONG
# ============================================================

def wide_to_long(
    df,
    question_cols,
    comment_cols,
    rater_type
):

    records = []

    # --------------------------------------------------------
    # Validasi jumlah pertanyaan
    # --------------------------------------------------------

    if len(question_cols) != 50:

        raise ValueError(
            f"{rater_type}: jumlah question = "
            f"{len(question_cols)}, seharusnya 50."
        )

    # --------------------------------------------------------
    # Buat lookup indicator
    # --------------------------------------------------------

    indicator_lookup = (
        indicator_master
        .drop_duplicates("indicator_id")
        .set_index("indicator_id")
        .to_dict("index")
    )

    print(
        f"{rater_type}: "
        f"{len(indicator_lookup)} indicator tersedia."
    )

    # --------------------------------------------------------
    # Validasi semua mapping
    # --------------------------------------------------------

    missing_mapping = []

    for question_no in range(1, 51):

        indicator_id = question_indicator_map.get(
            question_no
        )

        if indicator_id not in indicator_lookup:

            missing_mapping.append({
                "question_no": question_no,
                "indicator_id": indicator_id
            })

    if missing_mapping:

        print("❌ Mapping yang bermasalah:")

        display(
            pd.DataFrame(missing_mapping)
        )

        raise ValueError(
            f"{rater_type}: ada indicator mapping "
            "yang tidak ditemukan."
        )

    # --------------------------------------------------------
    # Loop setiap submission
    # --------------------------------------------------------

    for row_idx, row in df.iterrows():

        # ----------------------------------------------------
        # Tentukan employee & rater
        # ----------------------------------------------------

        if rater_type == "Self":

            employee_name = row.get("Nama")
            rater_name = row.get("Name")

        else:

            employee_name = row.get(
                "Nama bawahan yang dinilai"
            )

            rater_name = row.get("Name")

        # ----------------------------------------------------
        # Loop 50 pertanyaan
        # ----------------------------------------------------

        for question_no, question_col in enumerate(
            question_cols,
            start=1
        ):

            # ------------------------------------------------
            # Ambil jawaban
            # ------------------------------------------------

            answer = row.get(question_col)

            # Skip jawaban kosong
            if pd.isna(answer):
                continue

            if str(answer).strip() == "":
                continue

            # ------------------------------------------------
            # Ambil indicator ID
            # ------------------------------------------------

            indicator_id = question_indicator_map.get(
                question_no
            )

            if indicator_id is None:

                raise ValueError(
                    f"""
Question mapping tidak ditemukan.

Question No : {question_no}
Question    : {question_col}
Rater       : {rater_type}
"""
                )

            # ------------------------------------------------
            # Ambil indicator master
            # ------------------------------------------------

            indicator_info = indicator_lookup.get(
                indicator_id
            )

            if indicator_info is None:

                raise ValueError(
                    f"""
Indicator ID tidak ditemukan.

Indicator ID : {indicator_id}
Question No  : {question_no}
Question     : {question_col}
Rater        : {rater_type}
Source Row   : {row_idx + 2}
"""
                )

            # ------------------------------------------------
            # Comment
            # ------------------------------------------------

            comment = np.nan

            if question_no <= len(comment_cols):

                comment_col = comment_cols[
                    question_no - 1
                ]

                comment = row.get(
                    comment_col
                )

            # ------------------------------------------------
            # Simpan record
            # ------------------------------------------------

            records.append({

                "source_row":
                    row_idx + 2,

                "submission_id":
                    row.get("ID"),

                "submission_start":
                    row.get("Start time"),

                "submission_completion":
                    row.get("Completion time"),

                "last_modified_time":
                    row.get("Last modified time"),

                "rater_type":
                    rater_type,

                "rater_name":
                    rater_name,

                "employee_name":
                    employee_name,

                "employee_email":
                    (
                        row.get("Email")
                        if rater_type == "Self"
                        else np.nan
                    ),

                "direktorat":
                    row.get("Direktorat"),

                "departemen":
                    row.get("Departemen"),

                "unit":
                    row.get("Unit"),

                "question_no":
                    question_no,

                "question_text_raw":
                    question_col,

                "indicator_id":
                    indicator_id,

                "dimension":
                    indicator_info["dimension"],

                "indicator_no":
                    indicator_info["indicator_no"],

                "indicator":
                    indicator_info["indicator"],

                "answer_text":
                    str(answer),

                "comment":
                    comment
            })

    # --------------------------------------------------------
    # Convert ke DataFrame
    # --------------------------------------------------------

    result = pd.DataFrame(records)

    return result

In [34]:
#cell 29

self_long = wide_to_long(
    df=self_df,
    question_cols=self_question_cols,
    comment_cols=self_comment_cols,
    rater_type="Self"
)

print(
    "Self canonical rows:",
    len(self_long)
)

#cell 30self_long.head()

Self: 50 indicator tersedia.
Self canonical rows: 1600

In [35]:
#cell 30

superior_long = wide_to_long(
    df=superior_df,
    question_cols=superior_question_cols,
    comment_cols=superior_comment_cols,
    rater_type="Superior"
)

print(
    "Superior canonical rows:",
    len(superior_long)
)

superior_long.head()

Superior: 50 indicator tersedia.
Superior canonical rows: 1500

,source_row,submission_id,submission_start,submission_completion,last_modified_time,rater_type,rater_name,employee_name,employee_email,direktorat,departemen,unit,question_no,question_text_raw,indicator_id,dimension,indicator_no,indicator,answer_text,comment
0,2,1,2026-01-21 15:07:03,2026-01-21 15:27:00,NaN,Superior,Agung Sedayu,Deddie Yunawan Wicaksono Drajat,NaN,CEO Office,Internal Audit & Risk Management,Risk Management,1,"Ketika ada dalam situasi yang mengharuskan pengambilan keputusan atas masalah yang dihadapi, sik...",mental_agility_06,Mental Agility,6,Integrating Diverse Perspective\n(pengambilan keputusan melihat dari berbagai sudut pandang),Melihat beberapa sudut pandang ketika situasi mengharuskan.,NaN
1,2,1,2026-01-21 15:07:03,2026-01-21 15:27:00,NaN,Superior,Agung Sedayu,Deddie Yunawan Wicaksono Drajat,NaN,CEO Office,Internal Audit & Risk Management,Risk Management,2,"Ketika menghadapi konsep baru yang rumit, sikap bawahan saya adalah..",mental_agility_05,Mental Agility,5,Intellectual Synthesis\n(menghubungkan berbagai informasi),Memahami konsep baru dengan baik jika ada penjelasan bertahap.,NaN
2,2,1,2026-01-21 15:07:03,2026-01-21 15:27:00,NaN,Superior,Agung Sedayu,Deddie Yunawan Wicaksono Drajat,NaN,CEO Office,Internal Audit & Risk Management,Risk Management,3,"Ketika ada dalam yang situasi yang rumit dan belum memiliki kejelasan arah, sikap bawahan saya a...",mental_agility_09,Mental Agility,9,Comfort with Ambiguity\n(tetap efektif di situasi tidak jelas),Menghadapi kerumitan sebagai peluang untuk menciptakan terobosan.,NaN
3,2,1,2026-01-21 15:07:03,2026-01-21 15:27:00,NaN,Superior,Agung Sedayu,Deddie Yunawan Wicaksono Drajat,NaN,CEO Office,Internal Audit & Risk Management,Risk Management,4,"Dalam mengidentifikasi akar masalah dalam situasi kompleks, sikap bawahan saya adalah....",mental_agility_02,Mental Agility,2,Root Cause Analysis\n(mencari penyebab masalah),Menemukan akar masalah setelah melakukan analisis.,NaN
4,2,1,2026-01-21 15:07:03,2026-01-21 15:27:00,NaN,Superior,Agung Sedayu,Deddie Yunawan Wicaksono Drajat,NaN,CEO Office,Internal Audit & Risk Management,Risk Management,5,"Ketika menjelaskan ide atau masalah yang kompleks kepada orang lain, sikap bawahan saya adalah...",mental_agility_04,Mental Agility,4,Explaining Complexity\n(menjelaskan hal kompleks secara sederhana),Menjelaskan konsep kompleks dengan cara yang mudah dipahami.,NaN

In [36]:
#cell 31

canonical_df = pd.concat(
    [
        self_long,
        superior_long
    ],
    ignore_index=True
)

print(
    "Total canonical rows:",
    len(canonical_df)
)

canonical_df.head()

Total canonical rows: 3100

,source_row,submission_id,submission_start,submission_completion,last_modified_time,rater_type,rater_name,employee_name,employee_email,direktorat,departemen,unit,question_no,question_text_raw,indicator_id,dimension,indicator_no,indicator,answer_text,comment
0,2,2,2026-01-21 13:46:01,2026-01-21 14:12:57,NaN,Self,Rachma Deyana,Rachma Deyana,rachma.deyana@fiberstar.co.id,CEO Office,Internal Audit & Risk Management,Internal Audit Non Network,1,"Ketika ada dalam situasi yang mengharuskan pengambilan keputusan atas masalah yang dihadapi, sik...",mental_agility_06,Mental Agility,6,Integrating Diverse Perspective\n(pengambilan keputusan melihat dari berbagai sudut pandang),Secara alami menghubungkan berbagai perspektif untuk menemukan pendekatan inovatif.,NaN
1,2,2,2026-01-21 13:46:01,2026-01-21 14:12:57,NaN,Self,Rachma Deyana,Rachma Deyana,rachma.deyana@fiberstar.co.id,CEO Office,Internal Audit & Risk Management,Internal Audit Non Network,2,"Ketika menghadapi konsep baru yang rumit, sikap saya adalah..",mental_agility_05,Mental Agility,5,Intellectual Synthesis\n(menghubungkan berbagai informasi),Cepat memahami konsep baru yang kompleks dan terdorong untuk mengkajinya lebih dalam.,AI sangat membantu saya jika kesulitan memahami konsep baru jd tinggal self learning dan penjela...
2,2,2,2026-01-21 13:46:01,2026-01-21 14:12:57,NaN,Self,Rachma Deyana,Rachma Deyana,rachma.deyana@fiberstar.co.id,CEO Office,Internal Audit & Risk Management,Internal Audit Non Network,3,"Ketika ada dalam yang situasi yang rumit dan belum memiliki kejelasan arah, sikap saya adalah..",mental_agility_09,Mental Agility,9,Comfort with Ambiguity\n(tetap efektif di situasi tidak jelas),Menghadapi kerumitan dengan beberapa panduan.,kadang tergantung case
3,2,2,2026-01-21 13:46:01,2026-01-21 14:12:57,NaN,Self,Rachma Deyana,Rachma Deyana,rachma.deyana@fiberstar.co.id,CEO Office,Internal Audit & Risk Management,Internal Audit Non Network,4,"Dalam mengidentifikasi akar masalah dalam situasi kompleks, sikap saya adalah....",mental_agility_02,Mental Agility,2,Root Cause Analysis\n(mencari penyebab masalah),Menemukan akar masalah untuk situasi yang sederhana.,NaN
4,2,2,2026-01-21 13:46:01,2026-01-21 14:12:57,NaN,Self,Rachma Deyana,Rachma Deyana,rachma.deyana@fiberstar.co.id,CEO Office,Internal Audit & Risk Management,Internal Audit Non Network,5,"Ketika menjelaskan ide atau masalah yang kompleks kepada orang lain, sikap saya adalah...",mental_agility_04,Mental Agility,4,Explaining Complexity\n(menjelaskan hal kompleks secara sederhana),Menjelaskan konsep kompleks dengan cara yang mudah dipahami.,NaN

In [37]:
#cell 32

def normalize_name(value):
    
    if pd.isna(value):
        return ""
    
    text = str(value)
    
    text = text.lower().strip()
    
    text = re.sub(
        r"[^a-z0-9\s]",
        " ",
        text
    )
    
    text = re.sub(
        r"\s+",
        " ",
        text
    )
    
    return text.strip()

In [38]:
canonical_df["employee_name_key"] = (
    canonical_df["employee_name"]
    .apply(normalize_name)
)

canonical_df[
    [
        "rater_type",
        "employee_name",
        "employee_name_key"
    ]
].head(20)

   rater_type  employee_name employee_name_key
0        Self  Rachma Deyana     rachma deyana
1        Self  Rachma Deyana     rachma deyana
2        Self  Rachma Deyana     rachma deyana
3        Self  Rachma Deyana     rachma deyana
4        Self  Rachma Deyana     rachma deyana
5        Self  Rachma Deyana     rachma deyana
6        Self  Rachma Deyana     rachma deyana
7        Self  Rachma Deyana     rachma deyana
8        Self  Rachma Deyana     rachma deyana
9        Self  Rachma Deyana     rachma deyana
10       Self  Rachma Deyana     rachma deyana
11       Self  Rachma Deyana     rachma deyana
12       Self  Rachma Deyana     rachma deyana
13       Self  Rachma Deyana     rachma deyana
14       Self  Rachma Deyana     rachma deyana
15       Self  Rachma Deyana     rachma deyana
16       Self  Rachma Deyana     rachma deyana
17       Self  Rachma Deyana     rachma deyana
18       Self  Rachma Deyana     rachma deyana
19       Self  Rachma Deyana     rachma deyana

In [39]:
#cell 33

canonical_df["submission_start"] = pd.to_datetime(
    canonical_df["submission_start"],
    errors="coerce"
)

canonical_df["submission_completion"] = pd.to_datetime(
    canonical_df["submission_completion"],
    errors="coerce"
)

canonical_df["last_modified_time"] = pd.to_datetime(
    canonical_df["last_modified_time"],
    errors="coerce"
)

In [40]:
#cell 34

employee_summary = (
    canonical_df
    .groupby("rater_type")
    .agg(
        unique_employee=(
            "employee_name_key",
            "nunique"
        ),
        total_response=(
            "answer_text",
            "count"
        )
    )
    .reset_index()
)

employee_summary

  rater_type  unique_employee  total_response
0       Self               32            1600
1   Superior               30            1500

In [41]:
#cell 35

submission_summary = (
    canonical_df
    .groupby(
        [
            "employee_name_key",
            "rater_type",
            "submission_id"
        ],
        dropna=False
    )
    .agg(
        employee_name=(
            "employee_name",
            "first"
        ),
        completion=(
            "submission_completion",
            "max"
        ),
        last_modified=(
            "last_modified_time",
            "max"
        ),
        answer_count=(
            "answer_text",
            "count"
        )
    )
    .reset_index()
)

submission_summary.head()

      employee_name_key rater_type  submission_id         employee_name          completion last_modified  answer_count
0      ade rizqie fonna       Self             13      Ade Rizqie Fonna 2026-01-21 16:44:20           NaT            50
1      ade rizqie fonna   Superior              2      Ade Rizqie Fonna 2026-01-22 09:43:55           NaT            50
2  adelia irma mulianti   Superior              7  Adelia Irma Mulianti 2026-01-22 16:16:15           NaT            50
3       agung dwi cahyo       Self             22       AGUNG DWI CAHYO 2026-01-26 09:04:35           NaT            50
4       agung dwi cahyo   Superior             12       Agung Dwi Cahyo 2026-01-23 17:49:06           NaT            50

In [42]:
submission_summary["sort_date"] = (
    submission_summary["last_modified"]
    .fillna(
        submission_summary["completion"]
    )
)

submission_summary = submission_summary.sort_values(
    [
        "employee_name_key",
        "rater_type",
        "sort_date"
    ],
    ascending=[
        True,
        True,
        False
    ]
)

submission_summary["submission_rank"] = (
    submission_summary
    .groupby(
        [
            "employee_name_key",
            "rater_type"
        ],
        dropna=False
    )
    .cumcount()
    + 1
)

submission_summary["is_latest_submission"] = (
    submission_summary["submission_rank"] == 1
)

submission_summary.head(20)

,employee_name_key,rater_type,submission_id,employee_name,completion,last_modified,answer_count,sort_date,submission_rank,is_latest_submission
0,ade rizqie fonna,Self,13,Ade Rizqie Fonna,2026-01-21 16:44:20,NaT,50,2026-01-21 16:44:20,1,True
1,ade rizqie fonna,Superior,2,Ade Rizqie Fonna,2026-01-22 09:43:55,NaT,50,2026-01-22 09:43:55,1,True
2,adelia irma mulianti,Superior,7,Adelia Irma Mulianti,2026-01-22 16:16:15,NaT,50,2026-01-22 16:16:15,1,True
3,agung dwi cahyo,Self,22,AGUNG DWI CAHYO,2026-01-26 09:04:35,NaT,50,2026-01-26 09:04:35,1,True
4,agung dwi cahyo,Superior,12,Agung Dwi Cahyo,2026-01-23 17:49:06,NaT,50,2026-01-23 17:49:06,1,True
5,agung sedayu,Self,3,Agung Sedayu,2026-01-21 14:38:56,NaT,50,2026-01-21 14:38:56,1,True
6,ana kholifah,Self,30,Ana Kholifah,2026-01-28 13:27:54,NaT,50,2026-01-28 13:27:54,1,True
7,ana kholifah,Superior,28,Ana Kholifah,2026-01-28 19:07:53,NaT,50,2026-01-28 19:07:53,1,True
8,anggit catur nugroho,Self,5,Anggit Catur Nugroho,2026-01-21 15:25:42,NaT,50,2026-01-21 15:25:42,1,True
9,anggit catur nugroho,Superior,23,Anggit Catur Nugroho,2026-01-26 22:18:11,NaT,50,2026-01-26 22:18:11,1,True
10,charli sanjuan siahaan,Self,15,Charli Sanjuan Siahaan,2026-01-22 15:56:05,NaT,50,2026-01-22 15:56:05,1,True
11,charli sanjuan siahaan,Superior,26,Charli Sanjuan Siahaan,2026-01-28 13:23:28,NaT,50,2026-01-28 13:23:28,1,True
12,deddie yunawan wicaksono drajat,Self,19,Deddie Yunawan Wicaksono Drajat,2026-01-23 15:41:36,NaT,50,2026-01-23 15:41:36,1,True
13,deddie yunawan wicaksono drajat,Superior,1,Deddie Yunawan Wicaksono Drajat,2026-01-21 15:27:00,NaT,50,2026-01-21 15:27:00,1,True
14,dedek saputra,Self,25,Dedek Saputra,2026-01-26 14:17:37,NaT,50,2026-01-26 14:17:37,1,True
15,dedek saputra,Superior,13,Dedek Saputra,2026-01-26 09:07:07,NaT,50,2026-01-26 09:07:07,1,True
16,diah puspita,Self,20,Diah Puspita,2026-01-23 16:13:36,NaT,50,2026-01-23 16:13:36,1,True
17,elisabeth riviany dosi,Self,24,Elisabeth Riviany Dosi,2026-01-26 10:16:42,NaT,50,2026-01-26 10:16:42,1,True
18,elisabeth riviany dosi,Superior,8,Elisabeth Riviany Dosi,2026-01-22 16:28:21,NaT,50,2026-01-22 16:28:21,1,True
19,elrangga leonardo falloan,Self,33,Elrangga Leonardo Falloan,2026-01-29 12:02:38,NaT,50,2026-01-29 12:02:38,1,True

In [43]:
#cell 37

canonical_df = canonical_df.merge(
    submission_summary[
        [
            "employee_name_key",
            "rater_type",
            "submission_id",
            "submission_rank",
            "is_latest_submission"
        ]
    ],
    on=[
        "employee_name_key",
        "rater_type",
        "submission_id"
    ],
    how="left"
)

In [44]:
#cell 38

canonical_df.shape

(3100, 23)

In [45]:
canonical_df[
    [
        "rater_type",
        "employee_name",
        "question_no",
        "indicator_id",
        "dimension",
        "indicator",
        "answer_text",
        "submission_rank",
        "is_latest_submission"
    ]
].head(30)

,rater_type,employee_name,question_no,indicator_id,dimension,indicator,answer_text,submission_rank,is_latest_submission
0,Self,Rachma Deyana,1,mental_agility_06,Mental Agility,Integrating Diverse Perspective\n(pengambilan keputusan melihat dari berbagai sudut pandang),Secara alami menghubungkan berbagai perspektif untuk menemukan pendekatan inovatif.,1,True
1,Self,Rachma Deyana,2,mental_agility_05,Mental Agility,Intellectual Synthesis\n(menghubungkan berbagai informasi),Cepat memahami konsep baru yang kompleks dan terdorong untuk mengkajinya lebih dalam.,1,True
2,Self,Rachma Deyana,3,mental_agility_09,Mental Agility,Comfort with Ambiguity\n(tetap efektif di situasi tidak jelas),Menghadapi kerumitan dengan beberapa panduan.,1,True
3,Self,Rachma Deyana,4,mental_agility_02,Mental Agility,Root Cause Analysis\n(mencari penyebab masalah),Menemukan akar masalah untuk situasi yang sederhana.,1,True
4,Self,Rachma Deyana,5,mental_agility_04,Mental Agility,Explaining Complexity\n(menjelaskan hal kompleks secara sederhana),Menjelaskan konsep kompleks dengan cara yang mudah dipahami.,1,True
5,Self,Rachma Deyana,6,mental_agility_07,Mental Agility,Creative Exploration\n(mencari pendekatan baru),"Terbuka pada ide baru dalam konteks tertentu, terutama jika ada waktu dan sumber daya.",1,True
6,Self,Rachma Deyana,7,mental_agility_08,Mental Agility,Breaking Patterned thinking\n(menciptakan solusi baru),Mencari beberapa variasi solusi dan mencoba menggunakan cara baru.,1,True
7,Self,Rachma Deyana,8,mental_agility_10,Mental Agility,Tolerance for Ambiguity \n(mampu memimpin dalam uncertainty tinggi),Tetap bertumbuh dalam kondisi ketidakpastian dan memanfaatkannya untuk menciptakan solusi baru.,1,True
8,Self,Rachma Deyana,9,mental_agility_03,Mental Agility,Critical Thinking & Inquisitiveness\n(mempertanyakan & mengevaluasi),"Secara rutin bertanya ""mengapa"" dan ""bagaimana"" untuk memahami akar masalah.",1,True
9,Self,Rachma Deyana,10,mental_agility_01,Mental Agility,Analytical Thinking\n(memahami data & fakta dasar),Melihat hubungan yang jelas dan langsung antar konsep yang serupa.,1,True
10,Self,Rachma Deyana,11,people_agility_04,People Agility,Collaboration with Diversity\n(Bekerja efektif dalam keberagaman),Mudah beradaptasi dengan berbagai tipe orang dan menjaga kerja sama positif.,1,True
11,Self,Rachma Deyana,12,people_agility_08,People Agility,Conflict Navigation\n(menghadapi konflik secara konstruktif),Mengelola konflik secara terbuka dan mencari solusi yang adil.,1,True
12,Self,Rachma Deyana,13,people_agility_02,People Agility,Openness to Feedback\n(menerima & mencari masukan),Secara aktif meminta masukan dan memanfaatkannya untuk berkembang lebih cepat.,1,True
13,Self,Rachma Deyana,14,people_agility_10,People Agility,Conflict Mediation\n(menjadi penengah & penyatu pihak berbeda),Menjadi penengah yang dipercaya dan menyelesaikan konflik secara konstruktif.,1,True
14,Self,Rachma Deyana,15,people_agility_07,People Agility,Empathy\n(Merasakan & memahami emosi orang lain),Merasakan empati dan memahami perspektif orang lain secara mendalam.,1,True
15,Self,Rachma Deyana,16,people_agility_06,People Agility,Understanding Different Perspectives\n(Analisis multi-sudut pandang untuk pemahaman mendalam),Secara aktif mengeksplorasi dan mengintegrasikan sudut pandang berbeda untuk keputusan yang lebi...,1,True
16,Self,Rachma Deyana,17,people_agility_09,People Agility,Managing Challenging Stakeholder\n(Mengelola relasi berkelanjutan dengan stakeholder sulit),Bekerja dengan orang berkepribadian sulit dengan menetapkan batasan yang jelas.,1,True
17,Self,Rachma Deyana,18,people_agility_05,People Agility,Valuing Diverse Opinions\n(Menghargai opini berbeda dalam pengambilan keputusan),Mengintegrasikan berbagai pandangan untuk menciptakan solusi terbaik.,1,True
18,Self,Rachma Deyana,19,people_agility_03,People Agility,Genuine Curiosity about Others\n(rasa ingin tahu tulus pada orang lain),Menunjukkan rasa ingin tahu yang tulus dan membangun hubungan bermakna.,1,True
19,Self,Rachma Deyana,20,people_agility_01,People Agility,Listening for understanding\n(mendengarkan & memahami dasar),"Fokus pada pembicara, menjaga kontak mata, dan merangkum poin-poin penting.",1,True
20,Self,Rachma Deyana,21,change_agility_03,Change Agility,Comfort with Sudden Change\n(tetap bekerja saat perubahan mendadak),Beradaptasi dengan cepat dan tetap produktif dalam perubahan mendadak.,1,True
21,Self,Rachma Deyana,22,change_agility_06,Change Agility,Viewing Change as Opportunity\n(melihat perubahan sebagai peluang),Melihat perubahan sebagai kesempatan belajar dan peningkatan diri.,1,True
22,Self,Rachma Deyana,23,change_agility_01,Change Agility,Adapting to New Systems\n(mengikuti perubahan dasar),Cepat menyesuaikan diri dan mengoptimalkan sistem atau prosedur baru.,1,True
23,Self,Rachma Deyana,24,change_agility_04,Change Agility,Managing Resistance to Change\n(pengelolaan resistensi),Menerima perubahan dengan bantuan dan penjelasan tambahan.,1,True
24,Self,Rachma Deyana,25,change_agility_08,Change Agility,Risk-Taking for Innovation\n(berani mencoba pendekatan baru),Secara aktif mencari cara atau pendekatan baru dan mendorong inovasi.,1,True
25,Self,Rachma Deyana,26,change_agility_09,Change Agility,Calmness in Uncertainty\n(tetap tenang di kondisi tidak pasti),Memanfaatkan ketidakpastian untuk mengambil langkah strategis.,1,True
26,Self,Rachma Deyana,27,change_agility_02,Change Agility,Comfort with New Ways of Working\n(mulai nyaman dengan cara kerja baru),Menyesuaikan diri setelah memahami dasar perubahan.,1,True
27,Self,Rachma Deyana,28,change_agility_07,Change Agility,Proposing New Ideas\n(mulai menginisiasi perubahan),Secara konsisten mengusulkan ide baru yang relevan dan bermanfaat.,1,True
28,Self,Rachma Deyana,29,change_agility_05,Change Agility,Adaptive Learning & Experimentation\n(aktif belajar hal baru),Memiliki keinginan untuk memiliki pengetahuan dan belajar lintas bidang.,1,True
29,Self,Rachma Deyana,30,change_agility_10,Change Agility,Proactive in Anticipating Change\n(mengantisipasi perubahan sebelum terjadi),"Tidak hanya mengantisipasi perubahan, tetapi secara aktif prediksi situasi kedepannya.",1,True

In [46]:
#cell 39

qa_question = (
    canonical_df
    .groupby(
        [
            "rater_type",
            "question_no"
        ]
    )
    .agg(
        response_count=(
            "answer_text",
            "count"
        )
    )
    .reset_index()
)

qa_question

   rater_type  question_no  response_count
0        Self            1              32
1        Self            2              32
2        Self            3              32
3        Self            4              32
4        Self            5              32
..        ...          ...             ...
95   Superior           46              30
96   Superior           47              30
97   Superior           48              30
98   Superior           49              30
99   Superior           50              30

[100 rows x 3 columns]

In [47]:
#cell 40

qa_indicator = (
    canonical_df
    .groupby(
        [
            "rater_type",
            "dimension",
            "indicator_id",
            "indicator"
        ]
    )
    .agg(
        response_count=(
            "answer_text",
            "count"
        )
    )
    .reset_index()
)

qa_indicator

   rater_type       dimension       indicator_id                                                                       indicator  response_count
0        Self  Change Agility  change_agility_01                            Adapting to New Systems\n(mengikuti perubahan dasar)              32
1        Self  Change Agility  change_agility_02         Comfort with New Ways of Working\n(mulai nyaman dengan cara kerja baru)              32
2        Self  Change Agility  change_agility_03             Comfort with Sudden Change\n(tetap bekerja saat perubahan mendadak)              32
3        Self  Change Agility  change_agility_04                         Managing Resistance to Change\n(pengelolaan resistensi)              32
4        Self  Change Agility  change_agility_05                   Adaptive Learning & Experimentation\n(aktif belajar hal baru)              32
..        ...             ...                ...                                                                             ...             ...
95   Superior  Self Awareness  self_awareness_06           Proactive Self-Development for Adaptation\n(aktif mengembangkan diri)              30
96   Superior  Self Awareness  self_awareness_07                       Objective Self-Assessment\n(menilai diri secara objektif)              30
97   Superior  Self Awareness  self_awareness_08   Awareness of Impact on Others\n(memahami dampak perilaku terhadap orang lain)              30
98   Superior  Self Awareness  self_awareness_09                  Managing Emotions Effectively\n(mengelola emosi secara matang)              30
99   Superior  Self Awareness  self_awareness_10  Deep Pattern Recognition & Bias Awareness\n(refleksi diri mendalam & autentik)              30

[100 rows x 5 columns]

In [48]:
#cell 41

answer_variations = (
    canonical_df
    .groupby(
        [
            "question_no",
            "indicator_id",
            "indicator",
            "rater_type",
            "answer_text"
        ],
        dropna=False
    )
    .size()
    .reset_index(
        name="count"
    )
    .sort_values(
        [
            "question_no",
            "rater_type",
            "count"
        ],
        ascending=[
            True,
            True,
            False
        ]
    )
)

answer_variations.head(50)

,question_no,indicator_id,indicator,rater_type,answer_text,count
3,1,mental_agility_06,Integrating Diverse Perspective\n(pengambilan keputusan melihat dari berbagai sudut pandang),Self,Secara aktif mempertimbangkan banyak perspektif sebelum memutuskan sesuatu.,17
4,1,mental_agility_06,Integrating Diverse Perspective\n(pengambilan keputusan melihat dari berbagai sudut pandang),Self,Secara alami menghubungkan berbagai perspektif untuk menemukan pendekatan inovatif.,10
0,1,mental_agility_06,Integrating Diverse Perspective\n(pengambilan keputusan melihat dari berbagai sudut pandang),Self,Melihat beberapa sudut pandang ketika situasi mengharuskan.,3
1,1,mental_agility_06,Integrating Diverse Perspective\n(pengambilan keputusan melihat dari berbagai sudut pandang),Self,"Mencoba melihat perspektif lain, tetapi sering kembali ke sudut pandang awal.",1
2,1,mental_agility_06,Integrating Diverse Perspective\n(pengambilan keputusan melihat dari berbagai sudut pandang),Self,Mengandalkan satu cara berpikir dan kesulitan melihat perspektif lain.,1
8,1,mental_agility_06,Integrating Diverse Perspective\n(pengambilan keputusan melihat dari berbagai sudut pandang),Superior,Secara aktif mempertimbangkan banyak perspektif sebelum memutuskan sesuatu.,10
6,1,mental_agility_06,Integrating Diverse Perspective\n(pengambilan keputusan melihat dari berbagai sudut pandang),Superior,"Mencoba melihat perspektif lain, tetapi sering kembali ke sudut pandang awal.",7
5,1,mental_agility_06,Integrating Diverse Perspective\n(pengambilan keputusan melihat dari berbagai sudut pandang),Superior,Melihat beberapa sudut pandang ketika situasi mengharuskan.,5
7,1,mental_agility_06,Integrating Diverse Perspective\n(pengambilan keputusan melihat dari berbagai sudut pandang),Superior,Mengandalkan satu cara berpikir dan kesulitan melihat perspektif lain.,5
9,1,mental_agility_06,Integrating Diverse Perspective\n(pengambilan keputusan melihat dari berbagai sudut pandang),Superior,Secara alami menghubungkan berbagai perspektif untuk menemukan pendekatan inovatif.,3
11,2,mental_agility_05,Intellectual Synthesis\n(menghubungkan berbagai informasi),Self,Memahami konsep baru dengan baik jika ada penjelasan bertahap.,13
10,2,mental_agility_05,Intellectual Synthesis\n(menghubungkan berbagai informasi),Self,Cepat memahami konsep baru yang kompleks dan terdorong untuk mengkajinya lebih dalam.,10
12,2,mental_agility_05,Intellectual Synthesis\n(menghubungkan berbagai informasi),Self,Memahami konsep baru tetapi membutuhkan waktu yang lebih lama.,5
14,2,mental_agility_05,Intellectual Synthesis\n(menghubungkan berbagai informasi),Self,Sangat cepat menangkap konsep yang rumit dan mengaitkannya dengan solusi baru.,3
13,2,mental_agility_05,Intellectual Synthesis\n(menghubungkan berbagai informasi),Self,Mengalami kesulitan memahami konsep baru tanpa panduan yang jelas.,1
16,2,mental_agility_05,Intellectual Synthesis\n(menghubungkan berbagai informasi),Superior,Memahami konsep baru dengan baik jika ada penjelasan bertahap.,14
15,2,mental_agility_05,Intellectual Synthesis\n(menghubungkan berbagai informasi),Superior,Cepat memahami konsep baru yang kompleks dan terdorong untuk mengkajinya lebih dalam.,8
18,2,mental_agility_05,Intellectual Synthesis\n(menghubungkan berbagai informasi),Superior,Mengalami kesulitan memahami konsep baru tanpa panduan yang jelas.,5
17,2,mental_agility_05,Intellectual Synthesis\n(menghubungkan berbagai informasi),Superior,Memahami konsep baru tetapi membutuhkan waktu yang lebih lama.,3
21,3,mental_agility_09,Comfort with Ambiguity\n(tetap efektif di situasi tidak jelas),Self,Menghadapi kerumitan sebagai peluang untuk menciptakan terobosan.,13
20,3,mental_agility_09,Comfort with Ambiguity\n(tetap efektif di situasi tidak jelas),Self,Menghadapi kerumitan dengan beberapa panduan.,8
23,3,mental_agility_09,Comfort with Ambiguity\n(tetap efektif di situasi tidak jelas),Self,Merasa nyaman menghadapi kerumitan dan menganalisis tantangan baru.,5
19,3,mental_agility_09,Comfort with Ambiguity\n(tetap efektif di situasi tidak jelas),Self,"Mencoba menghadapi kerumitan, tetapi saat situasi membingungkan akan memilih masalah yang lebih...",3
22,3,mental_agility_09,Comfort with Ambiguity\n(tetap efektif di situasi tidak jelas),Self,Menghindari kerumitan dan memilih masalah yang lebih sederhana.,3
25,3,mental_agility_09,Comfort with Ambiguity\n(tetap efektif di situasi tidak jelas),Superior,Menghadapi kerumitan dengan beberapa panduan.,14
24,3,mental_agility_09,Comfort with Ambiguity\n(tetap efektif di situasi tidak jelas),Superior,"Mencoba menghadapi kerumitan, tetapi saat situasi membingungkan akan memilih masalah yang lebih...",8
26,3,mental_agility_09,Comfort with Ambiguity\n(tetap efektif di situasi tidak jelas),Superior,Menghadapi kerumitan sebagai peluang untuk menciptakan terobosan.,6
27,3,mental_agility_09,Comfort with Ambiguity\n(tetap efektif di situasi tidak jelas),Superior,Menghindari kerumitan dan memilih masalah yang lebih sederhana.,2
29,4,mental_agility_02,Root Cause Analysis\n(mencari penyebab masalah),Self,Menemukan akar masalah setelah melakukan analisis.,18
28,4,mental_agility_02,Root Cause Analysis\n(mencari penyebab masalah),Self,Mampu mengurai masalah kompleks dan menemukan akar penyebabnya.,11
30,4,mental_agility_02,Root Cause Analysis\n(mencari penyebab masalah),Self,Menemukan akar masalah untuk situasi yang sederhana.,2
31,4,mental_agility_02,Root Cause Analysis\n(mencari penyebab masalah),Self,Secara cepat dan akurat mengidentifikasi akar masalah dalam situasi ambigu.,1
33,4,mental_agility_02,Root Cause Analysis\n(mencari penyebab masalah),Superior,Menemukan akar masalah setelah melakukan analisis.,16
35,4,mental_agility_02,Root Cause Analysis\n(mencari penyebab masalah),Superior,Mengalami kesulitan memilah informasi dan menentukan inti masalah.,6
34,4,mental_agility_02,Root Cause Analysis\n(mencari penyebab masalah),Superior,Menemukan akar masalah untuk situasi yang sederhana.,5
32,4,mental_agility_02,Root Cause Analysis\n(mencari penyebab masalah),Superior,Mampu mengurai masalah kompleks dan menemukan akar penyebabnya.,3
38,5,mental_agility_04,Explaining Complexity\n(menjelaskan hal kompleks secara sederhana),Self,Menjelaskan konsep kompleks dengan cara yang mudah dipahami.,12
37,5,mental_agility_04,Explaining Complexity\n(menjelaskan hal kompleks secara sederhana),Self,Menjelaskan ide dengan menggunakan banyak contoh.,11
36,5,mental_agility_04,Explaining Complexity\n(menjelaskan hal kompleks secara sederhana),Self,Mengemas ide kompleks menjadi penjelasan yang sederhana dan inspiratif.,8
39,5,mental_agility_04,Explaining Complexity\n(menjelaskan hal kompleks secara sederhana),Self,Sulit menjelaskan ide tanpa membuat orang lain kebingungan.,1
43,5,mental_agility_04,Explaining Complexity\n(menjelaskan hal kompleks secara sederhana),Superior,Menjelaskan konsep kompleks dengan cara yang mudah dipahami.,12
41,5,mental_agility_04,Explaining Complexity\n(menjelaskan hal kompleks secara sederhana),Superior,Menjelaskan ide dengan menggunakan banyak contoh.,10
44,5,mental_agility_04,Explaining Complexity\n(menjelaskan hal kompleks secara sederhana),Superior,Sulit menjelaskan ide tanpa membuat orang lain kebingungan.,4
40,5,mental_agility_04,Explaining Complexity\n(menjelaskan hal kompleks secara sederhana),Superior,Mengemas ide kompleks menjadi penjelasan yang sederhana dan inspiratif.,2
42,5,mental_agility_04,Explaining Complexity\n(menjelaskan hal kompleks secara sederhana),Superior,Menjelaskan ide rumit dengan cukup jelas.,2
45,6,mental_agility_07,Creative Exploration\n(mencari pendekatan baru),Self,Aktif mencari ide baru dan melihatnya sebagai peluang perbaikan dan inovasi.,11
48,6,mental_agility_07,Creative Exploration\n(mencari pendekatan baru),Self,Secara alami tertarik pada ide baru dan memulai eksplorasi ide kreatif tanpa diminta.,9
49,6,mental_agility_07,Creative Exploration\n(mencari pendekatan baru),Self,"Terbuka pada ide baru dalam konteks tertentu, terutama jika ada waktu dan sumber daya.",8
46,6,mental_agility_07,Creative Exploration\n(mencari pendekatan baru),Self,Hanya menggunakan metode yang sudah sangat familiar.,2
47,6,mental_agility_07,Creative Exploration\n(mencari pendekatan baru),Self,Mendengarkan ide baru namun merasa metode yang telah terbukti lebih baik.,2

In [49]:
#cell 42

output_file = (
    OUTPUT_DIR
    / "STEP_1_Raw_to_Canonical.xlsx"
)

with pd.ExcelWriter(
    output_file,
    engine="openpyxl"
) as writer:
    
    canonical_df.to_excel(
        writer,
        sheet_name="Canonical_Data",
        index=False
    )
    
    indicator_master.to_excel(
        writer,
        sheet_name="Indicator_Master",
        index=False
    )
    
    question_mapping_df.to_excel(
        writer,
        sheet_name="Question_Mapping",
        index=False
    )
    
    qa_question.to_excel(
        writer,
        sheet_name="QA_By_Question",
        index=False
    )
    
    qa_indicator.to_excel(
        writer,
        sheet_name="QA_By_Indicator",
        index=False
    )
    
    answer_variations.to_excel(
        writer,
        sheet_name="Answer_Variations",
        index=False
    )
    
    submission_summary.to_excel(
        writer,
        sheet_name="Submission_Summary",
        index=False
    )

print(
    "File berhasil dibuat:"
)

print(
    output_file.resolve()
)

File berhasil dibuat:
C:\Users\zerox\OneDrive\Documents\Desktop\learning\data\processed\STEP_1_Raw_to_Canonical.xlsx

In [50]:
#cell 43

print("=" * 60)
print("STEP 1 FINAL CHECK")
print("=" * 60)

print(
    "Self submissions     :",
    len(self_df)
)

print(
    "Superior submissions :",
    len(superior_df)
)

print(
    "Self questions       :",
    len(self_question_cols)
)

print(
    "Superior questions   :",
    len(superior_question_cols)
)

print(
    "Indicators           :",
    len(indicator_master)
)

print(
    "Canonical rows       :",
    len(canonical_df)
)

print(
    "Unique employees     :",
    canonical_df[
        "employee_name_key"
    ].nunique()
)

print(
    "Output file          :",
    output_file.resolve()
)

print("=" * 60)

============================================================
STEP 1 FINAL CHECK
============================================================
Self submissions     : 32
Superior submissions : 30
Self questions       : 50
Superior questions   : 50
Indicators           : 50
Canonical rows       : 3100
Unique employees     : 38
Output file          : C:\Users\zerox\OneDrive\Documents\Desktop\learning\data\processed\STEP_1_Raw_to_Canonical.xlsx
============================================================